package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestProcessPath_SingleFileUsesContainingDir(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "processpath-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(pkgDir)
	})
	sourceFile := filepath.Join(pkgDir, "in.go")
	if err := os.WriteFile(sourceFile, []byte("// LITTEST\npackage main\n\nfunc main() { helper() }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "helper.go"), []byte("package main\n\nfunc helper() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if err := processPath(sourceFile, commandOptions{allFuncs: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(sourceFile)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if strings.Contains(text, "command-line-arguments") {
		t.Fatalf("single-file mode should compile the containing package, got:\n%s", text)
	}
	want := `// CHECK-LABEL: define void @main.main(){{.*}} {`
	if !strings.Contains(text, want) {
		t.Fatalf("missing canonical main check:\n%s", text)
	}
	if !strings.Contains(text, `call void @main.helper()`) {
		t.Fatalf("single-file mode did not include the containing package:\n%s", text)
	}
}

func TestProcessPath_UsesFlagsFileTarget(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "flags-target-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(pkgDir)
	})
	sourceFile := filepath.Join(pkgDir, "in.go")
	if err := os.WriteFile(sourceFile, []byte("// LITTEST\npackage main\n\nfunc main() { defer func() {}() }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "flags.txt"), []byte("-target=wasm\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if err := processPath(sourceFile, commandOptions{allFuncs: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(sourceFile)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "// CHECK-NEXT:   switch i32") {
		t.Fatalf("litgen did not use the wasm target from flags.txt:\n%s", text)
	}
	if strings.Contains(text, "blockaddress") || strings.Contains(text, "indirectbr") {
		t.Fatalf("litgen generated native defer dispatch for a wasm target:\n%s", text)
	}
}

func TestProcessPath_UpdateOnlyPreservesManualChecks(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "manual-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(pkgDir) })
	path := filepath.Join(pkgDir, "in.go")
	want := "// LITTEST\npackage main\n\n// CHECK: ret void\nfunc main() {}\n"
	if err := os.WriteFile(path, []byte(want), 0644); err != nil {
		t.Fatal(err)
	}
	if err := processPath(path, commandOptions{updateOnly: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Fatalf("manual checks changed:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestProcessPath_UpdateOnlyWalksUnderscoreSuites(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root, err := os.MkdirTemp(wd, "tree-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(root) })
	pkgDir := filepath.Join(root, "_testgo", "generated")
	if err := os.MkdirAll(pkgDir, 0755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(pkgDir, "in.go")
	source := "// LITTEST\n// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=value --check-globals=none\npackage main\n\nfunc value() int { return 1 }\n"
	if err := os.WriteFile(path, []byte(source), 0644); err != nil {
		t.Fatal(err)
	}
	if err := processPath(root, commandOptions{updateOnly: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), `// CHECK-LABEL: define i64 @main.value(){{.*}} {`) {
		t.Fatalf("underscore suite was not refreshed:\n%s", data)
	}
}

func TestProcessPath_CheckDetectsStaleGeneratedChecks(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "check-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(pkgDir) })
	path := filepath.Join(pkgDir, "in.go")
	if err := os.WriteFile(path, []byte("// LITTEST\npackage main\n\nfunc value() int { return 1 }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := processPath(path, commandOptions{functions: []string{"value"}, globals: "none"}); err != nil {
		t.Fatal(err)
	}
	checkOpts := commandOptions{updateOnly: true, check: true, globals: "smart"}
	if err := processPath(path, checkOpts); err != nil {
		t.Fatalf("fresh generated checks reported stale: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	stale := strings.Replace(string(data), "return 1", "return 2", 1)
	if err := os.WriteFile(path, []byte(stale), 0644); err != nil {
		t.Fatal(err)
	}
	err = processPath(path, checkOpts)
	if err == nil || !strings.Contains(err.Error(), "autogenerated assertions are stale") {
		t.Fatalf("unexpected stale-check error: %v", err)
	}
}
