/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/goplus/llgo/internal/littest"
	"github.com/goplus/llgo/xtool/env/llvm"
)

type stringListFlag []string

func (v *stringListFlag) String() string {
	return strings.Join(*v, ",")
}

func (v *stringListFlag) Set(value string) error {
	if value == "" {
		return errors.New("empty function pattern")
	}
	*v = append(*v, value)
	return nil
}

type commandOptions struct {
	updateOnly  bool
	check       bool
	allFuncs    bool
	functions   stringListFlag
	globals     string
	configFlags map[string]bool
}

var errSkippedManual = errors.New("manual LITTEST is not autogenerated")

func main() {
	llvm.SetupPath()
	var opts commandOptions
	flag.BoolVar(&opts.updateOnly, "u", false, "update only tests already marked as autogenerated")
	flag.BoolVar(&opts.updateOnly, "update-only", false, "update only tests already marked as autogenerated")
	flag.BoolVar(&opts.check, "check", false, "check that autogenerated assertions are current without writing files")
	flag.BoolVar(&opts.allFuncs, "all-functions", false, "generate assertions for every emitted function")
	flag.Var(&opts.functions, "function", "generate assertions for functions matching this regular expression (repeatable)")
	flag.StringVar(&opts.globals, "check-globals", "smart", "global assertion policy: none, smart, or all")
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "Usage: %s [flags] <file-or-dir> [<file-or-dir>...]\n", filepath.Base(os.Args[0]))
		flag.PrintDefaults()
	}
	flag.Parse()
	if flag.NArg() == 0 {
		flag.Usage()
		os.Exit(2)
	}
	opts.configFlags = make(map[string]bool)
	flag.Visit(func(f *flag.Flag) {
		opts.configFlags[f.Name] = true
	})
	if opts.check {
		opts.updateOnly = true
	}
	if err := opts.validate(); err != nil {
		fatal(err)
	}
	for _, arg := range flag.Args() {
		fatal(processPath(arg, opts))
	}
}

func (o commandOptions) validate() error {
	if o.allFuncs && len(o.functions) != 0 {
		return errors.New("--all-functions and --function cannot be used together")
	}
	switch o.globals {
	case "none", "smart", "all":
	default:
		return fmt.Errorf("invalid --check-globals value %q: want none, smart, or all", o.globals)
	}
	for _, pattern := range o.functions {
		if _, err := regexp.Compile(pattern); err != nil {
			return fmt.Errorf("invalid --function pattern %q: %w", pattern, err)
		}
	}
	return nil
}

func processPath(path string, opts commandOptions) error {
	abs, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	fi, err := os.Stat(abs)
	if err != nil {
		return err
	}
	if fi.IsDir() {
		return processTree(abs, opts)
	}
	if filepath.Ext(abs) != ".go" {
		return fmt.Errorf("%s: expected .go file or directory", abs)
	}
	ok, err := littest.HasMarker(abs)
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf("%s: missing // LITTEST marker", abs)
	}
	if opts.updateOnly {
		autogenerated, err := isAutogeneratedSource(abs)
		if err != nil {
			return err
		}
		if !autogenerated {
			fmt.Fprintln(os.Stderr, "skip", abs, "(manual LITTEST)")
			return nil
		}
	}
	target, err := resolveTarget(abs, filepath.Dir(abs))
	if err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "litgen", target.sourceFile)
	err = generateFile(target, opts)
	if errors.Is(err, errSkippedManual) && opts.updateOnly {
		fmt.Fprintln(os.Stderr, "skip", target.sourceFile, "(manual LITTEST)")
		return nil
	}
	return err
}

func processTree(root string, opts commandOptions) error {
	var targets []resolvedTarget
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		marked, found, err := littest.FindMarkedSourceFile(path)
		if err != nil {
			return err
		}
		if !found {
			return nil
		}
		if opts.updateOnly {
			autogenerated, err := isAutogeneratedSource(marked)
			if err != nil {
				return err
			}
			if !autogenerated {
				return nil
			}
		}
		target, err := resolveTarget(marked, path)
		if err != nil {
			return err
		}
		targets = append(targets, target)
		return nil
	})
	if err != nil {
		return err
	}
	if len(targets) == 0 {
		return fmt.Errorf("%s: no // LITTEST sources found", root)
	}
	sort.Slice(targets, func(i, j int) bool {
		return targets[i].sourceFile < targets[j].sourceFile
	})
	processed := 0
	for _, target := range targets {
		fmt.Fprintln(os.Stderr, "litgen", target.sourceFile)
		if err := generateFile(target, opts); errors.Is(err, errSkippedManual) && opts.updateOnly {
			fmt.Fprintln(os.Stderr, "skip", target.sourceFile, "(manual LITTEST)")
			continue
		} else if err != nil {
			return err
		}
		processed++
	}
	if processed == 0 {
		return fmt.Errorf("%s: no autogenerated LITTEST sources found", root)
	}
	return nil
}

func isAutogeneratedSource(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	_, autogenerated, err := parseAutogeneratedNote(string(data))
	if err != nil {
		return false, fmt.Errorf("%s: %w", path, err)
	}
	return autogenerated, nil
}

func fatal(err error) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "litgen: %v\n", err)
		os.Exit(1)
	}
}
