package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestProcessPath_SingleFileUsesContainingDir(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "processpath-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(pkgDir)
	})
	sourceFile := filepath.Join(pkgDir, "in.go")
	if err := os.WriteFile(sourceFile, []byte("// LITTEST\npackage main\n\nfunc main() { helper() }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "helper.go"), []byte("package main\n\nfunc helper() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if err := processPath(sourceFile, commandOptions{allFuncs: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(sourceFile)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if strings.Contains(text, "command-line-arguments") {
		t.Fatalf("single-file mode should compile the containing package, got:\n%s", text)
	}
	want := `// CHECK-LABEL: define void @main.main(){{.*}} {`
	if !strings.Contains(text, want) {
		t.Fatalf("missing canonical main check:\n%s", text)
	}
	if !strings.Contains(text, `call void @main.helper()`) {
		t.Fatalf("single-file mode did not include the containing package:\n%s", text)
	}
}

func TestProcessPath_UsesFlagsFileTarget(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "flags-target-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(pkgDir)
	})
	sourceFile := filepath.Join(pkgDir, "in.go")
	if err := os.WriteFile(sourceFile, []byte("// LITTEST\npackage main\n\nfunc main() { defer func() {}() }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "flags.txt"), []byte("-target=emscripten\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if err := processPath(sourceFile, commandOptions{allFuncs: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(sourceFile)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "// CHECK-NEXT:   switch i32") {
		t.Fatalf("litgen did not use the wasm target from flags.txt:\n%s", text)
	}
	if strings.Contains(text, "blockaddress") || strings.Contains(text, "indirectbr") {
		t.Fatalf("litgen generated native defer dispatch for a wasm target:\n%s", text)
	}
}

func TestProcessPath_UpdateOnlyPreservesManualChecks(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "manual-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(pkgDir) })
	path := filepath.Join(pkgDir, "in.go")
	want := "// LITTEST\npackage main\n\n// CHECK: ret void\nfunc main() {}\n"
	if err := os.WriteFile(path, []byte(want), 0644); err != nil {
		t.Fatal(err)
	}
	if err := processPath(path, commandOptions{updateOnly: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Fatalf("manual checks changed:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestProcessPathRequiresExplicitPostABITargets(t *testing.T) {
	path := filepath.Join(t.TempDir(), "in.go")
	if err := os.WriteFile(path, []byte("// LITTEST: POST-ABI\npackage main\n\nfunc main() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	err := processPath(path, commandOptions{allFuncs: true, globals: "smart"})
	if err == nil || !strings.Contains(err.Error(), "require explicit GOOS/GOARCH targets") {
		t.Fatalf("processPath error = %v, want explicit post-ABI targets requirement", err)
	}
}

func TestProcessPathGeneratesPostABITargetMatrix(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "postabi-matrix-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(pkgDir) })
	path := filepath.Join(pkgDir, "in.go")
	source := "// LITTEST: POST-ABI darwin/arm64 linux/amd64 linux/arm64\npackage main\n\nfunc value(v float32) uint32 { return uint32(v) }\n"
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := processPath(path, commandOptions{functions: []string{"value"}, globals: "none"}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	generated := string(data)
	for _, want := range []string{
		"// NOTE: Assertions have been autogenerated by chore/litgen",
		"// CHECK-LABEL: define i32 @main.value(",
		"// ARM64-NEXT:",
		"// LINUX-AMD64-NEXT:",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated POST-ABI matrix is missing %q:\n%s", want, generated)
		}
	}
	for _, unwanted := range []string{"// DARWIN-ARM64-", "// LINUX-ARM64-"} {
		if strings.Contains(generated, unwanted) {
			t.Fatalf("generated POST-ABI matrix kept redundant %q checks:\n%s", unwanted, generated)
		}
	}
	checkOpts := commandOptions{updateOnly: true, check: true, globals: "smart"}
	if err := processPath(path, checkOpts); err != nil {
		t.Fatalf("fresh POST-ABI matrix reported stale: %v", err)
	}
}

func TestProcessPathGeneratesDefaultStageTargetMatrix(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "preabi-matrix-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(pkgDir) })
	path := filepath.Join(pkgDir, "in.go")
	source := "// LITTEST darwin/arm64 linux/amd64\npackage main\n\nfunc makeValue(v int) func() int { return func() int { return v } }\n"
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}

	opts := commandOptions{
		functions: []string{`makeValue\$1`},
		globals:   "none",
	}
	if err := processPath(path, opts); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	generated := string(data)
	for _, want := range []string{
		"// LITTEST darwin/arm64 linux/amd64",
		"// CHECK-LABEL: define i64",
		"// DARWIN-ARM64-SAME: ptr swiftself",
		"// LINUX-AMD64-SAME: ptr nest",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated pre-ABI matrix is missing %q:\n%s", want, generated)
		}
	}
	checkOpts := commandOptions{updateOnly: true, check: true, globals: "smart"}
	if err := processPath(path, checkOpts); err != nil {
		t.Fatalf("fresh pre-ABI matrix reported stale: %v", err)
	}
}

func TestProcessTreeKeepsManualPostABIAndUpdatesAutogenerated(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root, err := os.MkdirTemp(wd, "postabi-tree-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(root) })

	defaultDir := filepath.Join(root, "default")
	manualPostABIDir := filepath.Join(root, "postabi-manual")
	autogeneratedPostABIDir := filepath.Join(root, "postabi-autogenerated")
	if err := os.Mkdir(defaultDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(manualPostABIDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(autogeneratedPostABIDir, 0o755); err != nil {
		t.Fatal(err)
	}
	defaultPath := filepath.Join(defaultDir, "in.go")
	manualPostABIPath := filepath.Join(manualPostABIDir, "in.go")
	autogeneratedPostABIPath := filepath.Join(autogeneratedPostABIDir, "in.go")
	if err := os.WriteFile(defaultPath, []byte("// LITTEST\npackage main\n\nfunc value() int { return 1 }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	manualPostABISource := "// LITTEST: POST-ABI\npackage main\n\n// CHECK: ret void\nfunc main() {}\n"
	if err := os.WriteFile(manualPostABIPath, []byte(manualPostABISource), 0o644); err != nil {
		t.Fatal(err)
	}
	autogeneratedPostABISource := "// LITTEST: POST-ABI linux/amd64 linux/arm64\n// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=convert --check-globals=none\npackage main\n\nfunc convert(v float32) uint32 { return uint32(v) }\n"
	if err := os.WriteFile(autogeneratedPostABIPath, []byte(autogeneratedPostABISource), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := processPath(root, commandOptions{functions: []string{"value"}, globals: "none"}); err != nil {
		t.Fatal(err)
	}
	generated, err := os.ReadFile(defaultPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generated), "// CHECK-LABEL: define i64 @main.value()") {
		t.Fatalf("default-stage sibling was not generated:\n%s", generated)
	}
	manualPostABI, err := os.ReadFile(manualPostABIPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(manualPostABI) != manualPostABISource {
		t.Fatalf("manual post-ABI source changed:\n%s", manualPostABI)
	}
	autogeneratedPostABI, err := os.ReadFile(autogeneratedPostABIPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"// CHECK-LABEL: define i32 @main.convert(", "// LINUX-AMD64-NEXT:", "// LINUX-ARM64-NEXT:"} {
		if !strings.Contains(string(autogeneratedPostABI), want) {
			t.Fatalf("autogenerated post-ABI matrix is missing %q:\n%s", want, autogeneratedPostABI)
		}
	}
}

func TestProcessPath_UpdateOnlyWalksUnderscoreSuites(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root, err := os.MkdirTemp(wd, "tree-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(root) })
	pkgDir := filepath.Join(root, "_testgo", "generated")
	if err := os.MkdirAll(pkgDir, 0755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(pkgDir, "in.go")
	source := "// LITTEST\n// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=value --check-globals=none\npackage main\n\nfunc value() int { return 1 }\n"
	if err := os.WriteFile(path, []byte(source), 0644); err != nil {
		t.Fatal(err)
	}
	if err := processPath(root, commandOptions{updateOnly: true, globals: "smart"}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), `// CHECK-LABEL: define i64 @main.value(){{.*}} {`) {
		t.Fatalf("underscore suite was not refreshed:\n%s", data)
	}
}

func TestProcessPath_CheckDetectsStaleGeneratedChecks(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	pkgDir, err := os.MkdirTemp(wd, "check-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(pkgDir) })
	path := filepath.Join(pkgDir, "in.go")
	if err := os.WriteFile(path, []byte("// LITTEST\npackage main\n\nfunc value() int { return 1 }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := processPath(path, commandOptions{functions: []string{"value"}, globals: "none"}); err != nil {
		t.Fatal(err)
	}
	checkOpts := commandOptions{updateOnly: true, check: true, globals: "smart"}
	if err := processPath(path, checkOpts); err != nil {
		t.Fatalf("fresh generated checks reported stale: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	stale := strings.Replace(string(data), "return 1", "return 2", 1)
	if err := os.WriteFile(path, []byte(stale), 0644); err != nil {
		t.Fatal(err)
	}
	err = processPath(path, checkOpts)
	if err == nil || !strings.Contains(err.Error(), "autogenerated assertions are stale") {
		t.Fatalf("unexpected stale-check error: %v", err)
	}
}
