/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime/debug"
	"sort"
	"strings"

	"github.com/goplus/llgo/internal/llgen"
	"github.com/goplus/mod"
	"golang.org/x/mod/modfile"
)

type resolvedTarget struct {
	sourceFile string
	genTarget  string
	pkgDir     string
	modulePath string
	pkgPath    string
}

type irProgram struct {
	globals []irGlobal
	funcs   []irFunction
}

type irGlobal struct {
	symbol string
	line   string
}

type irFunction struct {
	symbol string
	lines  []string
}

type generationConfig struct {
	allFunctions bool
	functions    []string
	functionREs  []*regexp.Regexp
	checkGlobals string
}

const (
	autogeneratedNote = "// NOTE: Assertions have been autogenerated by chore/litgen"
	utcArgsKey        = " UTC_ARGS:"
)

var (
	defineQuotedRE  = regexp.MustCompile(`^define\b.* @"([^"]+)"\(`)
	definePlainRE   = regexp.MustCompile(`^define\b.* @([^\s(]+)\(`)
	globalQuotedRE  = regexp.MustCompile(`^@"([^"]+)"\s*=`)
	globalPlainRE   = regexp.MustCompile(`^@([A-Za-z0-9$._-]+)\s*=`)
	globalRefRE     = regexp.MustCompile(`@"([^"]+)"|@([A-Za-z0-9$._-]+)`)
	checkLineRE     = regexp.MustCompile(`^\s*//\s*CHECK(?:-[A-Z]+)?:`)
	debugMetaRE     = regexp.MustCompile(`, ![A-Za-z0-9_.-]+ ![0-9]+`)
	closureEnvRE    = regexp.MustCompile(`(\s)(?:nest|swiftself)(\s)`)
	cgoSymbolHashRE = regexp.MustCompile(`_cgo_[0-9a-f]+_`)
	numericNameRE   = regexp.MustCompile(`^\d+$`)
	predsCommentRE  = regexp.MustCompile(`\s+; preds =.*$`)
	numericGlobalRE = regexp.MustCompile(`@([0-9]+)\b`)
	numericLocalRE  = regexp.MustCompile(`%([0-9]+)\b`)
	numericBlockRE  = regexp.MustCompile(`_llgo_([0-9]+)\b`)
)

func generateFile(target resolvedTarget, opts commandOptions) error {
	data, err := os.ReadFile(target.sourceFile)
	if err != nil {
		return err
	}
	cfg, autogenerated, err := generationConfigForSource(string(data), opts)
	if err != nil {
		return fmt.Errorf("%s: %w", target.sourceFile, err)
	}
	if !autogenerated && opts.updateOnly {
		return errSkippedManual
	}
	cleaned := setAutogeneratedNote(stripCheckDirectives(string(data)), cfg)
	ir, err := genIR(target.genTarget)
	if err != nil {
		return err
	}
	updated, err := rewriteSource(cleaned, target.sourceFile, target.pkgPath, target.modulePath, ir, cfg)
	if err != nil {
		return err
	}
	formatted, err := format.Source([]byte(updated))
	if err != nil {
		return fmt.Errorf("%s: gofmt failed: %w", target.sourceFile, err)
	}
	if bytes.Equal(data, formatted) {
		return nil
	}
	if opts.check {
		return fmt.Errorf("%s: autogenerated assertions are stale", target.sourceFile)
	}
	return writeFileAtomically(target.sourceFile, formatted, 0644)
}

func generationConfigForSource(src string, opts commandOptions) (generationConfig, bool, error) {
	embedded, autogenerated, err := parseAutogeneratedNote(src)
	if err != nil {
		return generationConfig{}, autogenerated, err
	}
	if !autogenerated && opts.updateOnly {
		return generationConfig{}, false, nil
	}
	cfg := embedded
	if !autogenerated {
		cfg = generationConfig{
			allFunctions: opts.allFuncs,
			functions:    append([]string(nil), opts.functions...),
			checkGlobals: opts.globals,
		}
	}
	if opts.configFlags["all-functions"] || opts.configFlags["function"] {
		cfg.allFunctions = opts.allFuncs
		cfg.functions = append([]string(nil), opts.functions...)
	}
	if opts.configFlags["check-globals"] {
		cfg.checkGlobals = opts.globals
	}
	if cfg.checkGlobals == "" {
		cfg.checkGlobals = "smart"
	}
	if err := cfg.compile(); err != nil {
		return generationConfig{}, autogenerated, err
	}
	return cfg, autogenerated, nil
}

func (cfg *generationConfig) compile() error {
	if cfg.allFunctions && len(cfg.functions) != 0 {
		return fmt.Errorf("autogenerated arguments contain both --all-functions and --function")
	}
	if !cfg.allFunctions && len(cfg.functions) == 0 {
		return fmt.Errorf("refusing to replace manual CHECK lines: pass --all-functions or at least one --function")
	}
	switch cfg.checkGlobals {
	case "none", "smart", "all":
	default:
		return fmt.Errorf("invalid autogenerated --check-globals value %q", cfg.checkGlobals)
	}
	cfg.functionREs = cfg.functionREs[:0]
	for _, pattern := range cfg.functions {
		re, err := regexp.Compile("^(?:" + pattern + ")$")
		if err != nil {
			return fmt.Errorf("invalid autogenerated --function pattern %q: %w", pattern, err)
		}
		cfg.functionREs = append(cfg.functionREs, re)
	}
	return nil
}

func parseAutogeneratedNote(src string) (generationConfig, bool, error) {
	for _, line := range strings.Split(src, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, autogeneratedNote) {
			continue
		}
		cfg := generationConfig{checkGlobals: "smart"}
		rest := strings.TrimSpace(strings.TrimPrefix(line, autogeneratedNote))
		if rest == "" {
			return cfg, true, errors.New("autogenerated note is missing UTC_ARGS")
		}
		if !strings.HasPrefix(rest, strings.TrimSpace(utcArgsKey)) {
			return cfg, true, fmt.Errorf("malformed autogenerated note %q", line)
		}
		args := strings.Fields(strings.TrimSpace(strings.TrimPrefix(rest, strings.TrimSpace(utcArgsKey))))
		for _, arg := range args {
			switch {
			case arg == "--all-functions":
				cfg.allFunctions = true
			case strings.HasPrefix(arg, "--function="):
				pattern := strings.TrimPrefix(arg, "--function=")
				if pattern == "" {
					return cfg, true, errors.New("empty --function in autogenerated note")
				}
				cfg.functions = append(cfg.functions, pattern)
			case strings.HasPrefix(arg, "--check-globals="):
				cfg.checkGlobals = strings.TrimPrefix(arg, "--check-globals=")
			default:
				return cfg, true, fmt.Errorf("unsupported autogenerated argument %q", arg)
			}
		}
		return cfg, true, nil
	}
	return generationConfig{}, false, nil
}

func setAutogeneratedNote(src string, cfg generationConfig) string {
	lines := strings.Split(strings.ReplaceAll(src, "\r\n", "\n"), "\n")
	out := make([]string, 0, len(lines)+1)
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), autogeneratedNote) {
			continue
		}
		out = append(out, line)
	}
	note := autogeneratedNote + utcArgsKey
	if cfg.allFunctions {
		note += " --all-functions"
	} else {
		for _, pattern := range cfg.functions {
			note += " --function=" + pattern
		}
	}
	note += " --check-globals=" + cfg.checkGlobals
	if len(out) == 0 {
		return note + "\n"
	}
	out = append(out[:1], append([]string{note}, out[1:]...)...)
	return strings.Join(out, "\n")
}

func resolveTarget(sourceFile, genTarget string) (resolvedTarget, error) {
	pkgDir := filepath.Dir(sourceFile)
	root, goMod, err := mod.FindGoMod(pkgDir)
	if err != nil {
		return resolvedTarget{}, err
	}
	modulePath, err := readModulePath(goMod)
	if err != nil {
		return resolvedTarget{}, err
	}
	pkgPath, err := packagePath(modulePath, root, pkgDir)
	if err != nil {
		return resolvedTarget{}, err
	}
	return resolvedTarget{
		sourceFile: sourceFile,
		genTarget:  genTarget,
		pkgDir:     pkgDir,
		modulePath: modulePath,
		pkgPath:    pkgPath,
	}, nil
}

func genIR(target string) (ret string, err error) {
	defer func() {
		if r := recover(); r != nil {
			switch v := r.(type) {
			case error:
				err = fmt.Errorf("llgen failed for %s: %w", target, v)
			case string:
				err = fmt.Errorf("llgen failed for %s: %s", target, v)
			default:
				_, _ = os.Stderr.Write(debug.Stack())
				panic(r)
			}
		}
	}()
	return llgen.GenFrom(target), nil
}

func readModulePath(goMod string) (string, error) {
	data, err := os.ReadFile(goMod)
	if err != nil {
		return "", err
	}
	modulePath := modfile.ModulePath(data)
	if modulePath == "" {
		return "", fmt.Errorf("%s: module directive not found", goMod)
	}
	return modulePath, nil
}

func packagePath(modulePath, root, pkgDir string) (string, error) {
	rel, err := filepath.Rel(root, pkgDir)
	if err != nil {
		return "", err
	}
	if rel == "." {
		return modulePath, nil
	}
	return path.Join(modulePath, filepath.ToSlash(rel)), nil
}

func rewriteSource(src, srcPath, pkgPath, modulePath, ir string, cfg generationConfig) (string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, srcPath, src, parser.ParseComments)
	if err != nil {
		return "", err
	}
	prog := parseIR(ir)
	anchors, topPos := collectAnchors(src, fset, file)
	injections := make(map[int][]string)

	generalizer := newIRGeneralizer()
	if globals := buildGlobalChecks(prog, pkgPath, modulePath, cfg, generalizer); len(globals) != 0 {
		injections[topPos] = append(injections[topPos], formatDirectiveBlock(indentAt(src, topPos), globals))
	}
	eof := len(src)
	lastOffset := topPos
	for _, fn := range prog.funcs {
		if shouldSkipFunctionCheck(fn.symbol) || !cfg.matchesFunction(fn.symbol, pkgPath) {
			continue
		}
		lines := buildFunctionChecks(fn, modulePath, generalizer)
		if len(lines) == 0 {
			continue
		}
		offset := eof
		if name, ok := trimPkgPrefix(fn.symbol, pkgPath); ok {
			if pos, found := anchors[name]; found {
				offset = pos
			}
		}
		if offset < lastOffset {
			offset = lastOffset
		}
		injections[offset] = append(injections[offset], formatDirectiveBlock(indentAt(src, offset), lines))
		lastOffset = offset
	}
	return applyInjections(src, injections), nil
}

func (cfg generationConfig) matchesFunction(symbol, pkgPath string) bool {
	if cfg.allFunctions {
		return true
	}
	candidates := []string{symbol}
	if name, ok := trimPkgPrefix(symbol, pkgPath); ok {
		candidates = append(candidates, name)
	}
	if strings.HasPrefix(symbol, "main.") {
		candidates = append(candidates, strings.TrimPrefix(symbol, "main."))
	}
	if dot := strings.LastIndex(symbol, "."); dot >= 0 && dot+1 < len(symbol) {
		candidates = append(candidates, symbol[dot+1:])
	}
	for _, re := range cfg.functionREs {
		for _, candidate := range candidates {
			if re.MatchString(candidate) {
				return true
			}
		}
	}
	return false
}

func collectAnchors(src string, fset *token.FileSet, file *ast.File) (map[string]int, int) {
	anchors := make(map[string]int)
	counts := make(map[string]int)
	topPos := topInsertPos(src, fset, file)
	if initPos, ok := syntheticInitPos(src, fset, file); ok {
		anchors["init"] = initPos
	}
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			name := inPkgFuncName(d)
			anchors[name] = declInsertPos(src, fset, d.Pos(), d.Doc)
			collectFuncLitAnchors(src, fset, d.Body, name, anchors, counts, declDocAnchors(src, fset, d))
		case *ast.GenDecl:
			if d.Tok == token.IMPORT {
				continue
			}
			collectFuncLitAnchors(src, fset, d, "init", anchors, counts, declDocAnchors(src, fset, d))
		}
	}
	return anchors, topPos
}

func topInsertPos(src string, fset *token.FileSet, file *ast.File) int {
	for _, decl := range file.Decls {
		// Insert before declaration docs so compiler directives stay attached.
		switch d := decl.(type) {
		case *ast.FuncDecl:
			return declInsertPos(src, fset, d.Pos(), d.Doc)
		case *ast.GenDecl:
			if d.Tok == token.IMPORT {
				continue
			}
			return declInsertPos(src, fset, d.Pos(), d.Doc)
		}
	}
	return len(src)
}

func syntheticInitPos(src string, fset *token.FileSet, file *ast.File) (int, bool) {
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Name.Name == "init" {
				return declInsertPos(src, fset, d.Pos(), d.Doc), true
			}
		case *ast.GenDecl:
			if d.Tok != token.IMPORT {
				return declInsertPos(src, fset, d.Pos(), d.Doc), true
			}
		}
	}
	return 0, false
}

func declInsertPos(src string, fset *token.FileSet, pos token.Pos, doc *ast.CommentGroup) int {
	if doc != nil {
		pos = doc.Pos()
	}
	return lineStart(src, offsetOf(fset, pos))
}

func declDocAnchors(src string, fset *token.FileSet, decl ast.Decl) map[int]int {
	var anchors map[int]int
	add := func(pos token.Pos, doc *ast.CommentGroup) {
		if doc == nil {
			return
		}
		if anchors == nil {
			anchors = make(map[int]int)
		}
		anchors[lineStart(src, offsetOf(fset, pos))] = declInsertPos(src, fset, pos, doc)
	}
	switch d := decl.(type) {
	case *ast.FuncDecl:
		add(d.Pos(), d.Doc)
	case *ast.GenDecl:
		add(d.Pos(), d.Doc)
		for _, spec := range d.Specs {
			if s, ok := spec.(*ast.ValueSpec); ok {
				add(s.Pos(), s.Doc)
			}
		}
	}
	return anchors
}

func collectFuncLitAnchors(src string, fset *token.FileSet, node ast.Node, parent string, anchors map[string]int, counts map[string]int, docAnchors map[int]int) {
	if isNilNode(node) {
		return
	}
	var walk func(ast.Node, string)
	walk = func(root ast.Node, current string) {
		if isNilNode(root) {
			return
		}
		ast.Inspect(root, func(n ast.Node) bool {
			lit, ok := n.(*ast.FuncLit)
			if !ok {
				return true
			}
			counts[current]++
			name := fmt.Sprintf("%s$%d", current, counts[current])
			pos := lineStart(src, offsetOf(fset, lit.Pos()))
			// Keep declaration docs attached when a closure shares the declaration line.
			if docPos, ok := docAnchors[pos]; ok {
				pos = docPos
			}
			anchors[name] = pos
			walk(lit.Body, name)
			return false
		})
	}
	walk(node, parent)
}

func isNilNode(node ast.Node) bool {
	if node == nil {
		return true
	}
	v := reflect.ValueOf(node)
	switch v.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return v.IsNil()
	default:
		return false
	}
}

func inPkgFuncName(fn *ast.FuncDecl) string {
	name := fn.Name.Name
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return name
	}
	recv := fn.Recv.List[0].Type
	if star, ok := recv.(*ast.StarExpr); ok {
		return "(*" + recvTypeName(star.X) + ")." + name
	}
	return recvTypeName(recv) + "." + name
}

func recvTypeName(expr ast.Expr) string {
	switch v := expr.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.SelectorExpr:
		return recvTypeName(v.X) + "." + v.Sel.Name
	case *ast.IndexExpr:
		return recvTypeName(v.X)
	case *ast.IndexListExpr:
		return recvTypeName(v.X)
	default:
		return ""
	}
}

func parseIR(ir string) irProgram {
	lines := splitIRLines(ir)
	var prog irProgram
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if strings.HasPrefix(line, "define ") {
			j := i + 1
			for j < len(lines) {
				if lines[j] == "}" {
					j++
					break
				}
				j++
			}
			block := append([]string(nil), lines[i:j]...)
			prog.funcs = append(prog.funcs, irFunction{
				symbol: extractDefineSymbol(line),
				lines:  block,
			})
			i = j - 1
			continue
		}
		if symbol, ok := extractGlobalSymbol(line); ok {
			prog.globals = append(prog.globals, irGlobal{symbol: symbol, line: line})
		}
	}
	return prog
}

func splitIRLines(ir string) []string {
	ir = strings.ReplaceAll(ir, "\r\n", "\n")
	ir = strings.TrimSuffix(ir, "\n")
	if ir == "" {
		return nil
	}
	return strings.Split(ir, "\n")
}

func extractDefineSymbol(line string) string {
	if m := defineQuotedRE.FindStringSubmatch(line); m != nil {
		return m[1]
	}
	if m := definePlainRE.FindStringSubmatch(line); m != nil {
		return m[1]
	}
	return ""
}

func extractGlobalSymbol(line string) (string, bool) {
	if m := globalQuotedRE.FindStringSubmatch(line); m != nil {
		return m[1], true
	}
	if m := globalPlainRE.FindStringSubmatch(line); m != nil {
		return m[1], true
	}
	return "", false
}

func buildGlobalChecks(prog irProgram, pkgPath, modulePath string, cfg generationConfig, generalizer *irGeneralizer) []string {
	if cfg.checkGlobals == "none" {
		return nil
	}
	defs := make(map[string]string, len(prog.globals))
	order := make([]string, 0, len(prog.globals))
	for _, g := range prog.globals {
		if cfg.checkGlobals != "all" && !shouldCheckGlobal(g.symbol) {
			continue
		}
		defs[g.symbol] = g.line
		order = append(order, g.symbol)
	}
	if len(defs) == 0 {
		return nil
	}
	needed := make(map[string]bool)
	for _, fn := range prog.funcs {
		if shouldSkipFunctionCheck(fn.symbol) || !cfg.matchesFunction(fn.symbol, pkgPath) {
			continue
		}
		for _, line := range fn.lines[1:] {
			for _, ref := range collectRefs(line) {
				if _, ok := defs[ref]; ok {
					needed[ref] = true
				}
			}
		}
	}
	var lines []string
	for _, symbol := range order {
		if cfg.checkGlobals == "smart" && !needed[symbol] {
			continue
		}
		line := generalizeIRLine(defs[symbol], modulePath)
		lines = append(lines, "// CHECK: {{^}}"+generalizer.generalizeGlobal(line)+"{{$}}")
	}
	return lines
}

func buildFunctionChecks(fn irFunction, modulePath string, generalizer *irGeneralizer) []string {
	if len(fn.lines) == 0 {
		return nil
	}
	generalizer.startFunction()
	lines := make([]string, 0, len(fn.lines))
	define := generalizeDefineLine(fn.lines[0], modulePath)
	lines = append(lines, generalizeFunctionHeader(define, generalizer)...)
	for _, line := range fn.lines[1:] {
		if strings.TrimSpace(line) == "" {
			lines = append(lines, "// CHECK-EMPTY:")
			continue
		}
		line = generalizeIRLine(line, modulePath)
		line = predsCommentRE.ReplaceAllString(line, "")
		lines = append(lines, "// CHECK-NEXT: "+generalizer.generalizeFunctionLine(line))
	}
	return lines
}

// FileCheck forbids variable definitions and uses in CHECK-LABEL directives.
// Keep the function identity in CHECK-LABEL, capture numbered parameters in a
// following CHECK-SAME, and reuse those captures throughout the body. This is
// the same shape used by LLVM's update_*_test_checks.py scripts and preserves
// argument-to-body relationships in an autogenerated full-function snapshot.
func generalizeFunctionHeader(line string, generalizer *irGeneralizer) []string {
	if !numericLocalRE.MatchString(line) {
		return []string{"// CHECK-LABEL: " + generalizeFunctionLabel(line)}
	}
	open := functionArgsOpen(line)
	if open < 0 {
		return []string{"// CHECK-LABEL: " + generalizeFunctionLabel(line)}
	}
	label := generalizeFunctionLabel(line[:open+1])
	signature := generalizer.generalizeFunctionLine(line[open+1:])
	return []string{
		"// CHECK-LABEL: " + label,
		"// CHECK-SAME: " + signature,
	}
}

func functionArgsOpen(line string) int {
	if loc := defineQuotedRE.FindStringIndex(line); loc != nil {
		return loc[1] - 1
	}
	if loc := definePlainRE.FindStringIndex(line); loc != nil {
		return loc[1] - 1
	}
	return -1
}

func generalizeFunctionLabel(line string) string {
	return rewriteOutsideQuotes(line, func(segment string) string {
		segment = numericGlobalRE.ReplaceAllString(segment, `@{{[0-9]+}}`)
		segment = numericBlockRE.ReplaceAllString(segment, `%_llgo_{{[0-9]+}}`)
		return numericLocalRE.ReplaceAllString(segment, `%{{[0-9]+}}`)
	})
}

type irGeneralizer struct {
	globals map[string]string
	locals  map[string]string
	blocks  map[string]string
}

func newIRGeneralizer() *irGeneralizer {
	return &irGeneralizer{globals: make(map[string]string)}
}

func (g *irGeneralizer) startFunction() {
	g.locals = make(map[string]string)
	g.blocks = make(map[string]string)
}

func (g *irGeneralizer) generalizeGlobal(line string) string {
	return rewriteOutsideQuotes(line, func(segment string) string {
		return replaceNumberedIRValues(segment, numericGlobalRE, "GLOB", "[0-9]+", g.globals)
	})
}

func (g *irGeneralizer) generalizeFunctionLine(line string) string {
	return rewriteOutsideQuotes(line, func(segment string) string {
		segment = replaceNumberedIRValues(segment, numericGlobalRE, "GLOB", "[0-9]+", g.globals)
		segment = replaceNumberedIRValues(segment, numericBlockRE, "BB", "[0-9]+", g.blocks)
		return replaceNumberedIRValues(segment, numericLocalRE, "TMP", "[0-9]+", g.locals)
	})
}

func replaceNumberedIRValues(segment string, re *regexp.Regexp, prefix, valueRE string, seen map[string]string) string {
	return re.ReplaceAllStringFunc(segment, func(token string) string {
		match := re.FindStringSubmatch(token)
		if len(match) != 2 {
			return token
		}
		number := match[1]
		name, ok := seen[number]
		if !ok {
			name = prefix + number
			seen[number] = name
			return strings.Replace(token, number, "[["+name+":"+valueRE+"]]", 1)
		}
		return strings.Replace(token, number, "[["+name+"]]", 1)
	})
}

func rewriteOutsideQuotes(line string, rewrite func(string) string) string {
	var out strings.Builder
	start := 0
	inQuote := false
	for i := 0; i < len(line); i++ {
		if line[i] != '"' || isEscapedQuote(line, i) {
			continue
		}
		if !inQuote {
			out.WriteString(rewrite(line[start:i]))
			out.WriteByte('"')
			start = i + 1
			inQuote = true
			continue
		}
		out.WriteString(line[start : i+1])
		start = i + 1
		inQuote = false
	}
	if inQuote {
		out.WriteString(line[start:])
	} else {
		out.WriteString(rewrite(line[start:]))
	}
	return out.String()
}

func generalizeDefineLine(line, modulePath string) string {
	line = scrubIRLine(line)
	if idx := strings.LastIndex(line, " {"); idx >= 0 {
		head := line[:idx]
		if sigEnd := strings.LastIndex(head, ")"); sigEnd >= 0 {
			line = head[:sigEnd+1] + "{{.*}}" + line[idx:]
		}
	}
	return generalizeModulePath(line, modulePath)
}

func generalizeIRLine(line, modulePath string) string {
	return generalizeModulePath(scrubIRLine(line), modulePath)
}

func scrubIRLine(line string) string {
	line = debugMetaRE.ReplaceAllString(line, "")
	line = generalizeClosureEnvAttrs(line)
	line = cgoSymbolHashRE.ReplaceAllString(line, `_cgo_{{[0-9a-f]+}}_`)
	line = strings.ReplaceAll(line, `[[`, `{{\[\[}}`)
	return strings.TrimRight(line, " \t")
}

func generalizeClosureEnvAttrs(line string) string {
	var b strings.Builder
	start := 0
	inQuote := false
	for i := 0; i < len(line); i++ {
		if line[i] != '"' || isEscapedQuote(line, i) {
			continue
		}
		if !inQuote {
			b.WriteString(closureEnvRE.ReplaceAllString(line[start:i], `${1}{{(nest|swiftself)}}${2}`))
			b.WriteByte('"')
			start = i + 1
			inQuote = true
			continue
		}
		b.WriteString(line[start : i+1])
		start = i + 1
		inQuote = false
	}
	if inQuote {
		b.WriteString(line[start:])
	} else {
		b.WriteString(closureEnvRE.ReplaceAllString(line[start:], `${1}{{(nest|swiftself)}}${2}`))
	}
	return b.String()
}

func generalizeModulePath(line, modulePath string) string {
	if modulePath == "" {
		return line
	}
	var b strings.Builder
	start := 0
	inQuote := false
	for i := 0; i < len(line); i++ {
		if line[i] != '"' || isEscapedQuote(line, i) {
			continue
		}
		if !inQuote {
			b.WriteString(line[start : i+1])
			start = i + 1
			inQuote = true
			continue
		}
		b.WriteString(strings.ReplaceAll(line[start:i], modulePath, "{{.*}}"))
		b.WriteByte('"')
		start = i + 1
		inQuote = false
	}
	b.WriteString(line[start:])
	return b.String()
}

func isEscapedQuote(line string, idx int) bool {
	backslashes := 0
	for i := idx - 1; i >= 0 && line[i] == '\\'; i-- {
		backslashes++
	}
	return backslashes%2 == 1
}

func shouldCheckGlobal(symbol string) bool {
	return numericNameRE.MatchString(symbol)
}

func collectRefs(line string) []string {
	matches := globalRefRE.FindAllStringSubmatch(line, -1)
	if len(matches) == 0 {
		return nil
	}
	refs := make([]string, 0, len(matches))
	for _, m := range matches {
		if m[1] != "" {
			refs = append(refs, m[1])
			continue
		}
		if m[2] != "" {
			refs = append(refs, m[2])
		}
	}
	return refs
}

func shouldSkipFunctionCheck(symbol string) bool {
	return strings.HasSuffix(symbol, "/runtime/internal/runtime.memequal32") ||
		strings.HasSuffix(symbol, "/runtime/internal/runtime.memequalptr") ||
		strings.HasSuffix(symbol, "/runtime/internal/runtime.strequal")
}

func trimPkgPrefix(symbol, pkgPath string) (string, bool) {
	prefix := pkgPath + "."
	if strings.HasPrefix(symbol, prefix) {
		return strings.TrimPrefix(symbol, prefix), true
	}
	return "", false
}

func applyInjections(src string, injections map[int][]string) string {
	if len(injections) == 0 {
		return src
	}
	offsets := make([]int, 0, len(injections))
	for offset := range injections {
		offsets = append(offsets, offset)
	}
	sort.Sort(sort.Reverse(sort.IntSlice(offsets)))
	out := src
	for _, offset := range offsets {
		block := strings.Join(injections[offset], "")
		out = out[:offset] + block + out[offset:]
	}
	return out
}

func formatDirectiveBlock(indent string, lines []string) string {
	var b strings.Builder
	for _, line := range lines {
		b.WriteString(indent)
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteByte('\n')
	return b.String()
}

func stripCheckDirectives(src string) string {
	src = strings.ReplaceAll(src, "\r\n", "\n")
	lines := strings.SplitAfter(src, "\n")
	if len(lines) == 0 {
		return src
	}
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimRight(line, "\n")
		if checkLineRE.MatchString(trimmed) {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "")
}

func lineStart(src string, offset int) int {
	if offset < 0 {
		return 0
	}
	if offset > len(src) {
		return len(src)
	}
	for offset > 0 && src[offset-1] != '\n' {
		offset--
	}
	return offset
}

func indentAt(src string, offset int) string {
	if offset >= len(src) {
		return ""
	}
	start := lineStart(src, offset)
	end := start
	for end < len(src) && (src[end] == ' ' || src[end] == '\t') {
		end++
	}
	return src[start:end]
}

func offsetOf(fset *token.FileSet, pos token.Pos) int {
	return fset.PositionFor(pos, false).Offset
}

func writeFileAtomically(path string, data []byte, perm os.FileMode) (err error) {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".litgen-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() {
		_ = tmp.Close()
		if err != nil {
			_ = os.Remove(tmpPath)
		}
	}()
	if err = tmp.Chmod(perm); err != nil {
		return err
	}
	if _, err = tmp.Write(data); err != nil {
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
