ignore:
  - "chore"
  - "cmd"
  - "cl/cltest"
  - "internal/build"
  - "internal/cabi"
  - "internal/llgen"
  - "internal/mockable"
  - "internal/packages"
  - "internal/typepatch"
  - "internal/github"
  - "internal/firmware"
  - "internal/flash"
  - "internal/monitor"
  - "runtime/_patch"
  - "runtime/build.go"
  - "test/go"
  - "xtool"
