/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package filecheck

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/goplus/llgo/xtool/env/llvm"
)

var invalidPrefixChars = regexp.MustCompile(`[^A-Z0-9_-]+`)

func Match(filename, input string) error {
	return MatchWithPrefixes(filename, input)
}

func MatchWithPrefixes(filename, input string, prefixes ...string) error {
	args := make([]string, 0, len(prefixes)+2)
	if len(prefixes) != 0 {
		// A source usually contains either CHECK directives or a target-specific
		// snapshot, not one directive for every enabled OS/architecture axis.
		args = append(args, "--allow-unused-prefixes")
	}
	for _, prefix := range prefixes {
		args = append(args, "--check-prefix="+prefix)
	}
	args = append(args, filename)
	cmd, err := llvm.New("").FileCheck(args...)
	if err != nil {
		return err
	}
	cmd.Stdin = strings.NewReader(input)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		if stderr.Len() > 0 {
			return fmt.Errorf("%w\n%s", err, strings.TrimRight(stderr.String(), "\n"))
		}
		return err
	}
	return nil
}

// MatchTextWithPrefixes runs FileCheck with an in-memory check specification.
// It is primarily used when an autogenerated source fixture is checked one
// function at a time so function order in the LLVM module is not part of the
// contract.
func MatchTextWithPrefixes(checkText, input string, prefixes ...string) error {
	f, err := os.CreateTemp("", "llgo-filecheck-*.txt")
	if err != nil {
		return err
	}
	name := f.Name()
	defer os.Remove(name)
	if _, err := f.WriteString(checkText); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return MatchWithPrefixes(name, input, prefixes...)
}

// TargetPrefixes returns the FileCheck prefixes enabled for a compile target.
// CHECK remains available for target-independent assertions, while the other
// prefixes let one source file carry target-specific expectations.
func TargetPrefixes(goos, goarch, target string) []string {
	prefixes := []string{"CHECK"}
	osPrefix := normalizePrefix(goos)
	archPrefix := normalizePrefix(goarch)
	if osPrefix != "" {
		prefixes = append(prefixes, osPrefix)
	}
	if archPrefix != "" {
		if archPrefix[0] >= '0' && archPrefix[0] <= '9' {
			archPrefix = "ARCH-" + archPrefix
		}
		prefixes = append(prefixes, archPrefix)
	}
	if osPrefix != "" && archPrefix != "" {
		prefixes = append(prefixes, osPrefix+"-"+archPrefix)
	}
	if targetPrefix := normalizePrefix(target); targetPrefix != "" {
		prefixes = append(prefixes, "TARGET-"+targetPrefix)
	}
	return dedupPrefixes(prefixes)
}

// TargetSnapshotPrefix returns the most specific prefix used by autogenerated
// snapshots for a compile target.
func TargetSnapshotPrefix(goos, goarch, target string) string {
	if targetPrefix := normalizePrefix(target); targetPrefix != "" {
		return "TARGET-" + targetPrefix
	}
	osPrefix := normalizePrefix(goos)
	archPrefix := normalizePrefix(goarch)
	if archPrefix != "" && archPrefix[0] >= '0' && archPrefix[0] <= '9' {
		archPrefix = "ARCH-" + archPrefix
	}
	switch {
	case osPrefix != "" && archPrefix != "":
		return osPrefix + "-" + archPrefix
	case osPrefix != "":
		return osPrefix
	case archPrefix != "":
		return archPrefix
	default:
		return "CHECK"
	}
}

func normalizePrefix(value string) string {
	value = strings.ToUpper(strings.TrimSpace(value))
	value = invalidPrefixChars.ReplaceAllString(value, "-")
	return strings.Trim(value, "-_")
}

func dedupPrefixes(prefixes []string) []string {
	seen := make(map[string]bool, len(prefixes))
	out := prefixes[:0]
	for _, prefix := range prefixes {
		if prefix == "" || seen[prefix] {
			continue
		}
		seen[prefix] = true
		out = append(out, prefix)
	}
	return out
}
