// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.ReadFile\E|\Qmain.ReadFile$1\E|\Qmain.main\E|\Qmain.main$1\E|\Qmain.Async[main.Tuple[error]]\E|\Qmain.Tuple[error].Get\E|\Qmain.(*future[main.Tuple[error]]).Then\E|\Qmain.(*Tuple[error]).Get\E) --check-globals=smart
package main

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [7 x i8] c"foo.txt", align 1{{$}}
// CHECK: {{^}}@[[GLOB7:[0-9]+]] = private unnamed_addr constant [3 x i8] c"Get", align 1{{$}}
// CHECK: {{^}}@[[GLOB16:[0-9]+]] = private unnamed_addr constant [55 x i8] c"{{.*}}/cl/_testrt/tpmethod.Tuple[error]", align 1{{$}}

type Tuple[T any] struct {
	v T
}

func (t Tuple[T]) Get() T {
	return t.v
}

type Future[T any] interface {
	Then(func(T))
}

type future[T any] struct {
	fn func(func(T))
}

func (f *future[T]) Then(callback func(T)) {
	f.fn(callback)
}

func Async[T any](fn func(func(T))) Future[T] {
	return &future[T]{fn: fn}
}

func ReadFile(fileName string) Future[Tuple[error]] {

	return Async[Tuple[error]](func(resolve func(Tuple[error])) {
		resolve(Tuple[error]{v: nil})
	})
}

func main() {

	ReadFile("foo.txt").Then(func(v Tuple[error]) {
		println(v.Get())
	})
}

// CHECK-LABEL: define %"{{.*}}/runtime/internal/runtime.iface" @main.ReadFile(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.String" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.iface" @"main.Async[main.Tuple[error]]"({ ptr, ptr } { ptr @"main.ReadFile$1", ptr null })
// CHECK-NEXT:   ret %"{{.*}}/runtime/internal/runtime.iface" %[[TMP1]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.ReadFile$1"(
// CHECK-SAME: { ptr, ptr } %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"main.Tuple[error]", align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP1]], i8 0, i64 16, i1 false)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.Tuple[error]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" zeroinitializer, ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"main.Tuple[error]", ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP0]], 0
// CHECK-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP5]])
// CHECK-NEXT:   call void %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP4]], %"main.Tuple[error]" %[[TMP3]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.iface" @main.ReadFile(%"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 7 })
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP0]])
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr ptr, ptr %[[TMP2]], i64 3
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = load ptr, ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP4]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP5]], ptr %[[TMP1]], 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP6]], 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP6]], 0
// CHECK-NEXT:   call void %[[TMP8]](ptr %[[TMP7]], { ptr, ptr } { ptr @"main.main$1", ptr null })
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.main$1"(
// CHECK-SAME: %"main.Tuple[error]" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.iface" @"main.Tuple[error].Get"(%"main.Tuple[error]" %[[TMP0]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintIface"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP1]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce %"{{.*}}/runtime/internal/runtime.iface" @"main.Async[main.Tuple[error]]"(
// CHECK-SAME: { ptr, ptr } %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.future[main.Tuple[error]]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   store { ptr, ptr } %[[TMP0]], ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewItab"(ptr @"_llgo_iface$DoRJPuBst8Lp1uEP2e7OnwiP-bLraZwFmeGcjrik3Mw", ptr @"*_llgo_main.future[main.Tuple[error]]")
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" undef, ptr %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP4]], ptr %[[TMP1]], 1
// CHECK-NEXT:   ret %"{{.*}}/runtime/internal/runtime.iface" %[[TMP5]]
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce %"{{.*}}/runtime/internal/runtime.iface" @"main.Tuple[error].Get"(
// CHECK-SAME: %"main.Tuple[error]" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"main.Tuple[error]", align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP1]], i8 0, i64 16, i1 false)
// CHECK-NEXT:   store %"main.Tuple[error]" %[[TMP0]], ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.Tuple[error]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.iface", ptr %[[TMP2]], align 8
// CHECK-NEXT:   ret %"{{.*}}/runtime/internal/runtime.iface" %[[TMP3]]
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*future[main.Tuple[error]]).Then"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]], { ptr, ptr } %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.future[main.Tuple[error]]", ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP3]], 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP3]], 0
// CHECK-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP5]])
// CHECK-NEXT:   call void %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP4]], { ptr, ptr } %[[TMP1]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce %"{{.*}}/runtime/internal/runtime.iface" @"main.(*Tuple[error]).Get"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq ptr %[[TMP0]], null
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicWrapNilPointer"(i1 %[[TMP1]], %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB16]], i64 55 }, %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB7]], i64 3 })
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load %"main.Tuple[error]", ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.iface" @"main.Tuple[error].Get"(%"main.Tuple[error]" %[[TMP2]])
// CHECK-NEXT:   ret %"{{.*}}/runtime/internal/runtime.iface" %[[TMP3]]
// CHECK-NEXT: }
