// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain._Cfunc_test_structs\E|\Qmain.main\E) --check-globals=smart
package main

/*
#include "in.h"
*/
import "C"
import "fmt"

// Check the C aggregate ABI boundary: all five differently sized structs are
// passed by pointer through one generated C wrapper.

// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [19 x i8] c"test_structs failed", align 1{{$}}

func main() {
	r := C.test_structs(&C.s4{a: 1}, &C.s8{a: 1, b: 2}, &C.s12{a: 1, b: 2, c: 3}, &C.s16{a: 1, b: 2, c: 3, d: 4}, &C.s20{a: 1, b: 2, c: 3, d: 4, e: 5})
	fmt.Println(r)
	if r != 35 {
		panic("test_structs failed")
	}
}

// CHECK-LABEL: define i32 @main._Cfunc_test_structs(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr %[[TMP2:[0-9]+]], ptr %[[TMP3:[0-9]+]], ptr %[[TMP4:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr @main._cgo_{{[0-9a-f]+}}_Cfunc_test_structs, align 8
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = load ptr, ptr %[[TMP6]], align 8
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call i32 %[[TMP7]](ptr %[[TMP0]], ptr %[[TMP1]], ptr %[[TMP2]], ptr %[[TMP3]], ptr %[[TMP4]])
// CHECK-NEXT:   ret i32 %[[TMP8]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___3, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   store i32 1, ptr %[[TMP1]], align 4
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___4, ptr %[[TMP2]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___4, ptr %[[TMP2]], i32 0, i32 1
// CHECK-NEXT:   store i32 1, ptr %[[TMP3]], align 4
// CHECK-NEXT:   store i32 2, ptr %[[TMP4]], align 4
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 12)
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___0, ptr %[[TMP5]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___0, ptr %[[TMP5]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___0, ptr %[[TMP5]], i32 0, i32 2
// CHECK-NEXT:   store i32 1, ptr %[[TMP6]], align 4
// CHECK-NEXT:   store i32 2, ptr %[[TMP7]], align 4
// CHECK-NEXT:   store i32 3, ptr %[[TMP8]], align 4
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___1, ptr %[[TMP9]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___1, ptr %[[TMP9]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___1, ptr %[[TMP9]], i32 0, i32 2
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___1, ptr %[[TMP9]], i32 0, i32 3
// CHECK-NEXT:   store i32 1, ptr %[[TMP10]], align 4
// CHECK-NEXT:   store i32 2, ptr %[[TMP11]], align 4
// CHECK-NEXT:   store i32 3, ptr %[[TMP12]], align 4
// CHECK-NEXT:   store i32 4, ptr %[[TMP13]], align 4
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 20)
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___2, ptr %[[TMP14]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___2, ptr %[[TMP14]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___2, ptr %[[TMP14]], i32 0, i32 2
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___2, ptr %[[TMP14]], i32 0, i32 3
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds %main._Ctype_struct___2, ptr %[[TMP14]], i32 0, i32 4
// CHECK-NEXT:   store i32 1, ptr %[[TMP15]], align 4
// CHECK-NEXT:   store i32 2, ptr %[[TMP16]], align 4
// CHECK-NEXT:   store i32 3, ptr %[[TMP17]], align 4
// CHECK-NEXT:   store i32 4, ptr %[[TMP18]], align 4
// CHECK-NEXT:   store i32 5, ptr %[[TMP19]], align 4
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = call i32 @main._Cfunc_test_structs(ptr %[[TMP0]], ptr %[[TMP2]], ptr %[[TMP5]], ptr %[[TMP9]], ptr %[[TMP14]])
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP21]], i64 0
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 4)
// CHECK-NEXT:   store i32 %[[TMP20]], ptr %[[TMP23]], align 4
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_main._Ctype_int, ptr undef }, ptr %[[TMP23]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP24]], ptr %[[TMP22]], align 8
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP21]], 0
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP25]], i64 1, 1
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP26]], i64 1, 2
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = call { i64, %"{{.*}}/runtime/internal/runtime.iface" } @fmt.Println(%"{{.*}}/runtime/internal/runtime.Slice" %[[TMP27]])
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = icmp ne i32 %[[TMP20]], 35
// CHECK-NEXT:   br i1 %[[TMP29]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB2]], i64 19 }, ptr %[[TMP30]], align 8
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP30]], 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP31]])
// CHECK-NEXT:   unreachable
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
