// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.main$1\E) --check-globals=smart
package main

import (
	"fmt"
	"sync"
)

// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [5 x i8] c"hello", align 1{{$}}
// CHECK: {{^}}@[[GLOB3:[0-9]+]] = private unnamed_addr constant [1 x i8] c"1", align 1{{$}}
// CHECK: {{^}}@[[GLOB5:[0-9]+]] = private unnamed_addr constant [7 x i8] c"%#v %v\0A", align 1{{$}}

func main() {
	var m sync.Map
	m.Store(1, "hello")
	m.Store("1", 100)
	v, ok := m.Load("1")
	fmt.Println(v, ok)
	m.Range(func(k, v interface{}) bool {
		fmt.Printf("%#v %v\n", k, v)
		return true
	})
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 96)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 1, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP1]], 1
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB1]], i64 5 }, ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP3]], 1
// CHECK-NEXT:   call void @"sync.(*Map).Store"(ptr %[[TMP0]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP2]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP4]])
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB3]], i64 1 }, ptr %[[TMP5]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP5]], 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 100, ptr %[[TMP7]], align 8
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP7]], 1
// CHECK-NEXT:   call void @"sync.(*Map).Store"(ptr %[[TMP0]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP6]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP8]])
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB3]], i64 1 }, ptr %[[TMP9]], align 8
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP9]], 1
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = call { %"{{.*}}/runtime/internal/runtime.eface", i1 } @"sync.(*Map).Load"(ptr %[[TMP0]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP10]])
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.eface", i1 } %[[TMP11]], 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.eface", i1 } %[[TMP11]], 1
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP14]], i64 0
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP12]], ptr %[[TMP15]], align 8
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP14]], i64 1
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 1)
// CHECK-NEXT:   store i1 %[[TMP13]], ptr %[[TMP17]], align 1
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_bool, ptr undef }, ptr %[[TMP17]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP18]], ptr %[[TMP16]], align 8
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP14]], 0
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP19]], i64 2, 1
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP20]], i64 2, 2
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = call { i64, %"{{.*}}/runtime/internal/runtime.iface" } @fmt.Println(%"{{.*}}/runtime/internal/runtime.Slice" %[[TMP21]])
// CHECK-NEXT:   call void @"sync.(*Map).Range"(ptr %[[TMP0]], { ptr, ptr } { ptr @"main.main$1", ptr null })
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define i1 @"main.main$1"(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0:[0-9]+]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP2]], i64 0
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP2]], i64 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP1]], ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP2]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP5]], i64 2, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP6]], i64 2, 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call { i64, %"{{.*}}/runtime/internal/runtime.iface" } @fmt.Printf(%"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB5]], i64 7 }, %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]])
// CHECK-NEXT:   ret i1 true
// CHECK-NEXT: }
