// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.lookup[main.LargeKey]\E) --check-globals=smart
package main

// LargeKey is larger than the runtime's inline map key limit. Maps store
// these keys indirectly, so this also exercises the generic map ABI path.
type LargeKey [256]byte

func lookup[K comparable](m map[K]int, key K) (int, bool) {
	value, ok := m[key]
	return value, ok
}

func main() {
	m := make(map[LargeKey]int)
	for i := 0; i < 32; i++ {
		var key LargeKey
		key[0] = byte(i)
		m[key] = i
	}

	var target LargeKey
	target[0] = 17
	value, ok := lookup(m, target)

	sum := 0
	for key, value := range m {
		sum += int(key[0]) + value
	}
	println(value, ok, len(m), sum)
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MakeMap"(ptr @"map[_llgo_main.LargeKey]_llgo_int", i64 0)
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = phi i64 [ 0, %_llgo_[[BB0]] ], [ %[[TMP9:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 32
// CHECK-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = alloca [256 x i8], align 1
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP3]], i8 0, i64 256, i1 false)
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = trunc i64 %[[TMP1]] to i8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds i8, ptr %[[TMP3]], i64 0
// CHECK-NEXT:   store i8 %[[TMP4]], ptr %[[TMP5]], align 1
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load [256 x i8], ptr %[[TMP3]], align 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 256)
// CHECK-NEXT:   store [256 x i8] %[[TMP6]], ptr %[[TMP7]], align 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MapAssign"(ptr @"map[_llgo_main.LargeKey]_llgo_int", ptr %[[TMP0]], ptr %[[TMP7]])
// CHECK-NEXT:   store i64 %[[TMP1]], ptr %[[TMP8]], align 8
// CHECK-NEXT:   %[[TMP9]] = add i64 %[[TMP1]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = alloca [256 x i8], align 1
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP10]], i8 0, i64 256, i1 false)
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds i8, ptr %[[TMP10]], i64 0
// CHECK-NEXT:   store i8 17, ptr %[[TMP11]], align 1
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = load [256 x i8], ptr %[[TMP10]], align 1
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = call { i64, i1 } @"main.lookup[main.LargeKey]"(ptr %[[TMP0]], [256 x i8] %[[TMP12]])
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = extractvalue { i64, i1 } %[[TMP13]], 0
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = extractvalue { i64, i1 } %[[TMP13]], 1
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewMapIter"(ptr @"map[_llgo_main.LargeKey]_llgo_int", ptr %[[TMP0]])
// CHECK-NEXT:   br label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = phi i64 [ 0, %_llgo_[[BB3]] ], [ %[[TMP27:[0-9]+]], %_llgo_[[BB5:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = call { i1, ptr, ptr } @"{{.*}}/runtime/internal/runtime.MapIterNext"(ptr %[[TMP16]])
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = extractvalue { i1, ptr, ptr } %[[TMP18]], 0
// CHECK-NEXT:   br i1 %[[TMP19]], label %_llgo_[[BB7:[0-9]+]], label %_llgo_[[BB8:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = extractvalue { i1, [256 x i8], i64 } %[[TMP35:[0-9]+]], 1
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = extractvalue { i1, [256 x i8], i64 } %[[TMP35]], 2
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = alloca [256 x i8], align 1
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP22]], i8 0, i64 256, i1 false)
// CHECK-NEXT:   store [256 x i8] %[[TMP20]], ptr %[[TMP22]], align 1
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = getelementptr inbounds i8, ptr %[[TMP22]], i64 0
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = load i8, ptr %[[TMP23]], align 1
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = zext i8 %[[TMP24]] to i64
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = add i64 %[[TMP25]], %[[TMP21]]
// CHECK-NEXT:   %[[TMP27]] = add i64 %[[TMP17]], %[[TMP26]]
// CHECK-NEXT:   br label %_llgo_[[BB4]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB6:[0-9]+]]:
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = call i64 @"{{.*}}/runtime/internal/runtime.MapLen"(ptr %[[TMP0]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP14]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP15]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP28]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP17]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB7]]:
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = extractvalue { i1, ptr, ptr } %[[TMP18]], 1
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = extractvalue { i1, ptr, ptr } %[[TMP18]], 2
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = load [256 x i8], ptr %[[TMP29]], align 1
// CHECK-NEXT:   %[[TMP32:[0-9]+]] = load i64, ptr %[[TMP30]], align 8
// CHECK-NEXT:   %[[TMP33:[0-9]+]] = insertvalue { i1, [256 x i8], i64 } { i1 true, [256 x i8] undef, i64 undef }, [256 x i8] %[[TMP31]], 1
// CHECK-NEXT:   %[[TMP34:[0-9]+]] = insertvalue { i1, [256 x i8], i64 } %[[TMP33]], i64 %[[TMP32]], 2
// CHECK-NEXT:   br label %_llgo_[[BB9:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB8]]:
// CHECK-NEXT:   br label %_llgo_[[BB9]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB9]]:
// CHECK-NEXT:   %[[TMP35]] = phi { i1, [256 x i8], i64 } [ %[[TMP34]], %_llgo_[[BB7]] ], [ zeroinitializer, %_llgo_[[BB8]] ]
// CHECK-NEXT:   %[[TMP36:[0-9]+]] = extractvalue { i1, [256 x i8], i64 } %[[TMP35]], 0
// CHECK-NEXT:   br i1 %[[TMP36]], label %_llgo_[[BB5]], label %_llgo_[[BB6]]
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce { i64, i1 } @"main.lookup[main.LargeKey]"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]], [256 x i8] %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 256)
// CHECK-NEXT:   store [256 x i8] %[[TMP1]], ptr %[[TMP2]], align 1
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call { ptr, i1 } @"{{.*}}/runtime/internal/runtime.MapAccess2"(ptr @"map[_llgo_main.LargeKey]_llgo_int", ptr %[[TMP0]], ptr %[[TMP2]])
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load i64, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP3]], 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i1 } undef, i64 %[[TMP5]], 0
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = insertvalue { i64, i1 } %[[TMP7]], i1 %[[TMP6]], 1
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i1 } %[[TMP8]], 0
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i1 } %[[TMP8]], 1
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = insertvalue { i64, i1 } undef, i64 %[[TMP9]], 0
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = insertvalue { i64, i1 } %[[TMP11]], i1 %[[TMP10]], 1
// CHECK-NEXT:   ret { i64, i1 } %[[TMP12]]
// CHECK-NEXT: }
