//go:build ignore

// Generate small, real native-format parser fixtures on the host. Generation
// requires clang and lld-link; running the tests needs neither tool nor a shell.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	dir, err := os.MkdirTemp("", "llgo-binary-fixtures-")
	check(err)
	defer os.RemoveAll(dir)
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by go run generate.go; DO NOT EDIT.\n\npackage binaryfixture")
	for _, target := range []struct{ name, triple string }{
		{"ELF", "x86_64-unknown-linux-gnu"},
		{"MachO", "x86_64-apple-darwin"},
		{"PE", "x86_64-w64-windows-gnu"},
	} {
		object := filepath.Join(dir, target.name+".o")
		run("clang", "--target="+target.triple, "-gdwarf-4", "-g", "-O0", "-fno-stack-protector", "-fno-addrsig", "-fdebug-compilation-dir=.", "-c", "testdata/fixture.c", "-o", object)
		if target.name == "PE" {
			exe := filepath.Join(dir, "fixture.exe")
			run("lld-link", "/entry:llgo_fixture", "/nodefaultlib", "/subsystem:console", "/debug:dwarf", "/timestamp:0", "/out:"+exe, object)
			object = exe
		}
		data, err := os.ReadFile(object)
		check(err)
		var compressed bytes.Buffer
		w := gzip.NewWriter(&compressed)
		_, err = w.Write(data)
		check(err)
		check(w.Close())
		fmt.Fprintf(&source, "\nconst data%s = %q\n", target.name, base64.StdEncoding.EncodeToString(compressed.Bytes()))
	}
	data, err := format.Source(source.Bytes())
	check(err)
	check(os.WriteFile("data_generated.go", data, 0o644))
}

func run(name string, args ...string) {
	if output, err := exec.Command(name, args...).CombinedOutput(); err != nil {
		panic(fmt.Sprintf("%s %v: %v\n%s", name, args, err, output))
	}
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
