[workspace]
name = "llgo-dev"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
go = ">=1.27,<1.28"
llvmdev = ">=22,<23"
clang = ">=22,<23"
clangxx = ">=22,<23"
lld = ">=22,<23"
pkg-config = ">=0.29"
bdw-gc = ">=8"
libffi = "*"
openssl = ">=3,<4"
zlib = "*"
sqlite = "*"
libuv = "*"

[activation]
scripts = ["activate_pixi.sh"]

[target.win-64.activation]
scripts = ["activate_pixi.bat"]
