// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\QUse\E|\QUse5F64\E|\QUse6\E|\QUse6X\E|\QUsePtr\E|\QUseRaw\E|\QUseRaw6\E) --check-globals=smart
package llgosyscall

import _ "unsafe"

// llgo.syscall lowers to a typed indirect call and translates -1 through
// errno. Cover the ordinary, six-argument, floating-point, and raw forms.

//go:linkname syscall llgo.syscall
func syscall(fn, a1, a2, a3 uintptr) (r1, r2, err uintptr)

//go:linkname syscall6 llgo.syscall
func syscall6(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2, err uintptr)

//go:linkname syscall6X llgo.syscall
func syscall6X(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2, err uintptr)

//go:linkname syscall5f64 llgo.syscall
func syscall5f64(fn, a1, a2, a3, a4, a5 uintptr, f1 float64) (r1, r2, err uintptr)

//go:linkname syscallPtr llgo.syscall
func syscallPtr(fn, a1, a2, a3 uintptr) (r1, r2, err uintptr)

//go:linkname rawSyscall llgo.syscall
func rawSyscall(fn, a1, a2, a3 uintptr) (r1, r2, err uintptr)

//go:linkname rawSyscall6 llgo.syscall
func rawSyscall6(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2, err uintptr)

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.Use"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call i64 null(i64 1, i64 2, i64 3)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], -1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = sext i32 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], i64 %[[TMP3]], i64 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP5]], i64 0, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP6]], i64 %[[TMP4]], 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 2
// CHECK-NEXT:   ret i64 %[[TMP8]]
// CHECK-NEXT: }

func Use() uintptr {
	r1, _, _ := syscall(0, 1, 2, 3)
	return r1
}

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.Use5F64"(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]], double %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = inttoptr i64 %[[TMP0]] to ptr
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call i64 %[[TMP2]](i64 1, i64 2, i64 3, i64 4, i64 5, double %[[TMP1]])
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp eq i64 %[[TMP3]], -1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = sext i32 %[[TMP5]] to i64
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = select i1 %[[TMP4]], i64 %[[TMP6]], i64 0
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP8]], i64 0, 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP9]], i64 %[[TMP7]], 2
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP10]], 0
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP10]], 1
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP10]], 2
// CHECK-NEXT:   ret i64 %[[TMP11]]
// CHECK-NEXT: }

func Use5F64(fn uintptr, f float64) uintptr {
	r1, _, _ := syscall5f64(fn, 1, 2, 3, 4, 5, f)
	return r1
}

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.Use6"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call i64 null(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], -1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = sext i32 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], i64 %[[TMP3]], i64 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP5]], i64 0, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP6]], i64 %[[TMP4]], 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 2
// CHECK-NEXT:   ret i64 %[[TMP8]]
// CHECK-NEXT: }

func Use6() uintptr {
	r1, _, _ := syscall6(0, 1, 2, 3, 4, 5, 6)
	return r1
}

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.Use6X"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call i64 null(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], -1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = sext i32 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], i64 %[[TMP3]], i64 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP5]], i64 0, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP6]], i64 %[[TMP4]], 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 2
// CHECK-NEXT:   ret i64 %[[TMP8]]
// CHECK-NEXT: }

func Use6X() uintptr {
	r1, _, _ := syscall6X(0, 1, 2, 3, 4, 5, 6)
	return r1
}

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.UsePtr"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call i64 null(i64 1, i64 2, i64 3)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], -1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = sext i32 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], i64 %[[TMP3]], i64 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP5]], i64 0, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP6]], i64 %[[TMP4]], 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 2
// CHECK-NEXT:   ret i64 %[[TMP8]]
// CHECK-NEXT: }

func UsePtr() uintptr {
	r1, _, _ := syscallPtr(0, 1, 2, 3)
	return r1
}

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.UseRaw"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call i64 null(i64 1, i64 2, i64 3)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], -1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = sext i32 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], i64 %[[TMP3]], i64 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP5]], i64 0, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP6]], i64 %[[TMP4]], 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 2
// CHECK-NEXT:   ret i64 %[[TMP8]]
// CHECK-NEXT: }

func UseRaw() uintptr {
	r1, _, _ := rawSyscall(0, 1, 2, 3)
	return r1
}

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/llgosyscall.UseRaw6"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call i64 null(i64 1, i64 2, i64 3, i64 4, i64 5, i64 6)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], -1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @cliteErrno()
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = sext i32 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP1]], i64 %[[TMP3]], i64 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue { i64, i64, i64 } undef, i64 %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP5]], i64 0, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { i64, i64, i64 } %[[TMP6]], i64 %[[TMP4]], 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { i64, i64, i64 } %[[TMP7]], 2
// CHECK-NEXT:   ret i64 %[[TMP8]]
// CHECK-NEXT: }

func UseRaw6() uintptr {
	r1, _, _ := rawSyscall6(0, 1, 2, 3, 4, 5, 6)
	return r1
}
