// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.concat\E|\Qmain.info\E|\Qmain.main\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [3 x i8] c"...", align 1{{$}}
// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [5 x i8] c"Hello", align 1{{$}}
// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [1 x i8] c" ", align 1{{$}}
// CHECK: {{^}}@[[GLOB3:[0-9]+]] = private unnamed_addr constant [5 x i8] c"World", align 1{{$}}

// The loop carries both the accumulated string and the current index. The
// element selected by that index must be concatenated into the carried value.
func concat(args ...string) (ret string) {
	for _, v := range args {
		ret += v
	}
	return
}

func info(s string) string {
	return "" + s + "..."
}

func main() {
	result := concat("Hello", " ", "World")
	println(result)
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 48)
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], i64 0
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB1]], i64 5 }, ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], i64 1
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB2]], i64 1 }, ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], i64 2
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB3]], i64 5 }, ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP1]], 0
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP5]], i64 3, 1
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP6]], i64 3, 2
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]], ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.String" @main.concat(ptr %[[TMP0]])
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP8]])
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 48)
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], i64 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB1]], i64 5 }, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], i64 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB2]], i64 1 }, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], i64 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB3]], i64 5 }, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP3]], 0
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]], i64 3, 1
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP8]], i64 3, 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP9]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = call { ptr, i64 } @main.concat(ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP1]])
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP10]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP11]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = load i64, ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP13]], i64 %[[TMP15]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// DARWIN-ARM64-LABEL: define %"{{.*}}/runtime/internal/runtime.String" @main.concat(
// DARWIN-ARM64-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-LABEL: define { ptr, i64 } @main.concat(
// LINUX-AMD64-SAME: ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 1
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = phi %"{{.*}}/runtime/internal/runtime.String" [ zeroinitializer, %_llgo_[[BB0]] ], [ %[[TMP14:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP5:[0-9]+]], %_llgo_[[BB2]] ]
// DARWIN-ARM64-NEXT:   %[[TMP5]] = add i64 %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = icmp slt i64 %[[TMP5]], %[[TMP2]]
// DARWIN-ARM64-NEXT:   br i1 %[[TMP6]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = phi %"{{.*}}/runtime/internal/runtime.String" [ zeroinitializer, %_llgo_[[BB0]] ], [ %[[TMP26:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP8:[0-9]+]], %_llgo_[[BB2]] ]
// LINUX-AMD64-NEXT:   %[[TMP8]] = add i64 %[[TMP7]], 1
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = icmp slt i64 %[[TMP8]], %[[TMP5]]
// LINUX-AMD64-NEXT:   br i1 %[[TMP9]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 0
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 1
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = icmp slt i64 %[[TMP5]], 0
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = icmp uge i64 %[[TMP5]], %[[TMP8]]
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = or i1 %[[TMP10]], %[[TMP9]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP11]], i64 %[[TMP5]], i1 true, i64 %[[TMP8]])
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP7]], i64 %[[TMP5]]
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP12]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP14]] = call %"{{.*}}/runtime/internal/runtime.String" @"{{.*}}/runtime/internal/runtime.StringCat"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP3]], %"{{.*}}/runtime/internal/runtime.String" %[[TMP13]])
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 0
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 1
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = icmp slt i64 %[[TMP8]], 0
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = icmp uge i64 %[[TMP8]], %[[TMP11]]
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = or i1 %[[TMP13]], %[[TMP12]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP14]], i64 %[[TMP8]], i1 true, i64 %[[TMP11]])
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP10]], i64 %[[TMP8]]
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP15]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP6]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = load ptr, ptr %[[TMP17]], align 8
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = load i64, ptr %[[TMP19]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP16]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = load ptr, ptr %[[TMP21]], align 8
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = load i64, ptr %[[TMP23]], align 8
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = call { ptr, i64 } @"{{.*}}/runtime/internal/runtime.StringCat"(ptr %[[TMP18]], i64 %[[TMP20]], ptr %[[TMP22]], i64 %[[TMP24]])
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP25]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP26]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP4]], align 8
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// DARWIN-ARM64-NEXT:   ret %"{{.*}}/runtime/internal/runtime.String" %[[TMP3]]
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP6]], ptr %[[TMP27]], align 8
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = load { ptr, i64 }, ptr %[[TMP27]], align 8
// LINUX-AMD64-NEXT:   ret { ptr, i64 } %[[TMP28]]
// CHECK-NEXT: }

// DARWIN-ARM64-LABEL: define %"{{.*}}/runtime/internal/runtime.String" @main.info(
// DARWIN-ARM64-SAME: %"{{.*}}/runtime/internal/runtime.String" %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-LABEL: define { ptr, i64 } @main.info(
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.String" @"{{.*}}/runtime/internal/runtime.StringCat"(%"{{.*}}/runtime/internal/runtime.String" zeroinitializer, %"{{.*}}/runtime/internal/runtime.String" %[[TMP0]])
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.String" @"{{.*}}/runtime/internal/runtime.StringCat"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP1]], %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 3 })
// DARWIN-ARM64-NEXT:   ret %"{{.*}}/runtime/internal/runtime.String" %[[TMP2]]
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store i64 %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" zeroinitializer, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP9]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = load ptr, ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP9]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load i64, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP5]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = load ptr, ptr %[[TMP15]], align 8
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = load i64, ptr %[[TMP17]], align 8
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = call { ptr, i64 } @"{{.*}}/runtime/internal/runtime.StringCat"(ptr %[[TMP11]], i64 %[[TMP13]], ptr %[[TMP16]], i64 %[[TMP18]])
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP19]], ptr %[[TMP20]], align 8
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP20]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP21]], ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP6]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = load ptr, ptr %[[TMP22]], align 8
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP6]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = load i64, ptr %[[TMP24]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 3 }, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP7]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = load ptr, ptr %[[TMP26]], align 8
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP7]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = load i64, ptr %[[TMP28]], align 8
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = call { ptr, i64 } @"{{.*}}/runtime/internal/runtime.StringCat"(ptr %[[TMP23]], i64 %[[TMP25]], ptr %[[TMP27]], i64 %[[TMP29]])
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP30]], ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP31]], ptr %[[TMP32]], align 8
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = load { ptr, i64 }, ptr %[[TMP32]], align 8
// LINUX-AMD64-NEXT:   ret { ptr, i64 } %[[TMP33]]
// CHECK-NEXT: }
