// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=run --check-globals=smart
// NOTE: Autogenerated snapshot targets: WASIP1-WASM
package main

// WASIP1-WASM: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [5 x i8] c"first", align 1{{$}}
// WASIP1-WASM: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [6 x i8] c"second", align 1{{$}}

func run() {
	defer println("first")
	defer println("second")
}

func main() {
	run()
}

// WASIP1-WASM-LABEL: define void @main.run(){{.*}} {
// WASIP1-WASM-NEXT: _llgo_[[BB0:[0-9]+]]:
// WASIP1-WASM-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// WASIP1-WASM-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// WASIP1-WASM-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.GetThreadDefer"()
// WASIP1-WASM-NEXT:   %[[TMP3:[0-9]+]] = alloca i8, i32 200, align 1
// WASIP1-WASM-NEXT:   %[[TMP4:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i32 24)
// WASIP1-WASM-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 0
// WASIP1-WASM-NEXT:   store ptr %[[TMP3]], ptr %[[TMP5]], align 4
// WASIP1-WASM-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 1
// WASIP1-WASM-NEXT:   store i32 0, ptr %[[TMP6]], align 4
// WASIP1-WASM-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 2
// WASIP1-WASM-NEXT:   store ptr %[[TMP2]], ptr %[[TMP7]], align 4
// WASIP1-WASM-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 3
// WASIP1-WASM-NEXT:   store ptr null, ptr %[[TMP8]], align 4
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SetThreadDefer"(ptr %[[TMP4]])
// WASIP1-WASM-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 1
// WASIP1-WASM-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 3
// WASIP1-WASM-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 4
// WASIP1-WASM-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 5
// WASIP1-WASM-NEXT:   store ptr null, ptr %[[TMP11]], align 4
// WASIP1-WASM-NEXT:   store ptr null, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP13:[0-9]+]] = call i32 @setjmp(ptr %[[TMP3]])
// WASIP1-WASM-NEXT:   %[[TMP14:[0-9]+]] = icmp eq i32 %[[TMP13]], 0
// WASIP1-WASM-NEXT:   br i1 %[[TMP14]], label %_llgo_[[BB4:[0-9]+]], label %_llgo_[[BB5:[0-9]+]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB1:[0-9]+]]:
// WASIP1-WASM-NEXT:   ret void
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB2:[0-9]+]]:
// WASIP1-WASM-NEXT:   store ptr inttoptr (i32 2 to ptr), ptr %[[TMP10]], align 4
// WASIP1-WASM-NEXT:   %[[TMP15:[0-9]+]] = load i32, ptr %[[TMP9]], align 4
// WASIP1-WASM-NEXT:   %[[TMP16:[0-9]+]] = load ptr, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP17:[0-9]+]] = icmp ne ptr %[[TMP16]], null
// WASIP1-WASM-NEXT:   br i1 %[[TMP17]], label %_llgo_[[BB8:[0-9]+]], label %_llgo_[[BB9:[0-9]+]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB3:[0-9]+]]:
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Rethrow"(ptr %[[TMP2]])
// WASIP1-WASM-NEXT:   br label %_llgo_[[BB1]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB4]]:
// WASIP1-WASM-NEXT:   %[[TMP18:[0-9]+]] = load ptr, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP19:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i32 16)
// WASIP1-WASM-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP19]], i32 0, i32 0
// WASIP1-WASM-NEXT:   store ptr %[[TMP18]], ptr %[[TMP20]], align 4
// WASIP1-WASM-NEXT:   %[[TMP21:[0-9]+]] = getelementptr inbounds { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP19]], i32 0, i32 1
// WASIP1-WASM-NEXT:   store i32 0, ptr %[[TMP21]], align 4
// WASIP1-WASM-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP19]], i32 0, i32 2
// WASIP1-WASM-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i32 5 }, ptr %[[TMP22]], align 4
// WASIP1-WASM-NEXT:   store ptr %[[TMP19]], ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP23:[0-9]+]] = load ptr, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP24:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i32 16)
// WASIP1-WASM-NEXT:   %[[TMP25:[0-9]+]] = getelementptr inbounds { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP24]], i32 0, i32 0
// WASIP1-WASM-NEXT:   store ptr %[[TMP23]], ptr %[[TMP25]], align 4
// WASIP1-WASM-NEXT:   %[[TMP26:[0-9]+]] = getelementptr inbounds { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP24]], i32 0, i32 1
// WASIP1-WASM-NEXT:   store i32 1, ptr %[[TMP26]], align 4
// WASIP1-WASM-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP24]], i32 0, i32 2
// WASIP1-WASM-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB1]], i32 6 }, ptr %[[TMP27]], align 4
// WASIP1-WASM-NEXT:   store ptr %[[TMP24]], ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   store ptr inttoptr (i32 1 to ptr), ptr %[[TMP11]], align 4
// WASIP1-WASM-NEXT:   br label %_llgo_[[BB2]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB5]]:
// WASIP1-WASM-NEXT:   store ptr null, ptr %[[TMP11]], align 4
// WASIP1-WASM-NEXT:   %[[TMP28:[0-9]+]] = load ptr, ptr %[[TMP10]], align 4
// WASIP1-WASM-NEXT:   %[[TMP29:[0-9]+]] = ptrtoint ptr %[[TMP28]] to i32
// WASIP1-WASM-NEXT:   switch i32 %[[TMP29]], label %_llgo_[[BB13:[0-9]+]] [
// WASIP1-WASM-NEXT:     i32 1, label %_llgo_[[BB3]]
// WASIP1-WASM-NEXT:     i32 2, label %_llgo_[[BB7:[0-9]+]]
// WASIP1-WASM-NEXT:     i32 0, label %_llgo_[[BB2]]
// WASIP1-WASM-NEXT:   ]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB6:[0-9]+]]:
// WASIP1-WASM-NEXT:   ret void
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB7]]:
// WASIP1-WASM-NEXT:   store ptr inttoptr (i32 1 to ptr), ptr %[[TMP10]], align 4
// WASIP1-WASM-NEXT:   %[[TMP30:[0-9]+]] = load i32, ptr %[[TMP9]], align 4
// WASIP1-WASM-NEXT:   %[[TMP31:[0-9]+]] = load ptr, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP32:[0-9]+]] = icmp ne ptr %[[TMP31]], null
// WASIP1-WASM-NEXT:   br i1 %[[TMP32]], label %_llgo_[[BB10:[0-9]+]], label %_llgo_[[BB11:[0-9]+]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB8]]:
// WASIP1-WASM-NEXT:   %[[TMP33:[0-9]+]] = load ptr, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP34:[0-9]+]] = load { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP33]], align 4
// WASIP1-WASM-NEXT:   %[[TMP35:[0-9]+]] = extractvalue { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP34]], 0
// WASIP1-WASM-NEXT:   store ptr %[[TMP35]], ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP36:[0-9]+]] = extractvalue { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP34]], 2
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.FreeDeferNode"(ptr %[[TMP33]])
// WASIP1-WASM-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP36]], ptr %[[TMP1]], align 4
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr byval(%"{{.*}}/runtime/internal/runtime.String") %[[TMP1]])
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// WASIP1-WASM-NEXT:   br label %_llgo_[[BB9]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB9]]:
// WASIP1-WASM-NEXT:   br label %_llgo_[[BB7]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB10]]:
// WASIP1-WASM-NEXT:   %[[TMP37:[0-9]+]] = load ptr, ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP38:[0-9]+]] = load { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP37]], align 4
// WASIP1-WASM-NEXT:   %[[TMP39:[0-9]+]] = extractvalue { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP38]], 0
// WASIP1-WASM-NEXT:   store ptr %[[TMP39]], ptr %[[TMP12]], align 4
// WASIP1-WASM-NEXT:   %[[TMP40:[0-9]+]] = extractvalue { ptr, i32, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP38]], 2
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.FreeDeferNode"(ptr %[[TMP37]])
// WASIP1-WASM-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP40]], ptr %[[TMP0]], align 4
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr byval(%"{{.*}}/runtime/internal/runtime.String") %[[TMP0]])
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// WASIP1-WASM-NEXT:   br label %_llgo_[[BB11]]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB11]]:
// WASIP1-WASM-NEXT:   %[[TMP41:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], align 4
// WASIP1-WASM-NEXT:   %[[TMP42:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Defer" %[[TMP41]], 2
// WASIP1-WASM-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SetThreadDefer"(ptr %[[TMP42]])
// WASIP1-WASM-NEXT:   %[[TMP43:[0-9]+]] = load ptr, ptr %[[TMP11]], align 4
// WASIP1-WASM-NEXT:   %[[TMP44:[0-9]+]] = ptrtoint ptr %[[TMP43]] to i32
// WASIP1-WASM-NEXT:   switch i32 %[[TMP44]], label %_llgo_[[BB12:[0-9]+]] [
// WASIP1-WASM-NEXT:     i32 0, label %_llgo_[[BB3]]
// WASIP1-WASM-NEXT:     i32 1, label %_llgo_[[BB6]]
// WASIP1-WASM-NEXT:   ]
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB12]]:
// WASIP1-WASM-NEXT:   unreachable
// WASIP1-WASM-EMPTY:
// WASIP1-WASM-NEXT: _llgo_[[BB13]]:
// WASIP1-WASM-NEXT:   unreachable
// WASIP1-WASM-NEXT: }
