// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.init\E|\Qmain.main\E) --check-globals=smart
package main

import (
	"unsafe"

	"github.com/goplus/lib/c"
	"github.com/goplus/lib/py"
	"github.com/goplus/lib/py/math"
	"github.com/goplus/lib/py/std"
)

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [5 x i8] c"world", align 1{{$}}
// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [5 x i8] c"hello", align 1{{$}}
// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [3 x i8] c"pi\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB3:[0-9]+]] = private unnamed_addr constant [14 x i8] c"lens = %d %d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB4:[0-9]+]] = private unnamed_addr constant [14 x i8] c"ptrs = %d %d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB5:[0-9]+]] = private unnamed_addr constant [12 x i8] c"pi = %.15g\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB6:[0-9]+]] = private unnamed_addr constant [4 x i8] c"abs\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB7:[0-9]+]] = private unnamed_addr constant [6 x i8] c"print\00", align 1{{$}}

func main() {
	v := 100
	x := py.List(true, false, 1, float32(2.1), 3.1, uint(4), 1+2i, complex64(3+4i),
		"hello", []byte("world"), [...]byte{1, 2, 3}, [...]byte{}, &v, unsafe.Pointer(&v))
	y := py.List(std.Abs, std.Print, math.Pi)
	c.Printf(c.Str("lens = %d %d\n"), x.ListLen(), y.ListLen())
	c.Printf(c.Str("ptrs = %d %d\n"), x.ListItem(12).IsTrue(), x.ListItem(13).IsTrue())
	c.Printf(c.Str("pi = %.15g\n"), y.ListItem(2).Float64())
}

// Python module symbol binding belongs to package initialization, not main's
// list construction.

// Each Go value must be converted to the corresponding Python object and
// inserted into the same 14-element list at its source position.
// The second list contains the two loaded builtins and math.Pi, and all later
// observations must read back from the correct list and index.

// CHECK-LABEL: define void @main.init(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = load i1, ptr @"main.init$guard", align 1
// CHECK-NEXT:   br i1 %[[TMP0]], label %_llgo_[[BB2:[0-9]+]], label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   store i1 true, ptr @"main.init$guard", align 1
// CHECK-NEXT:   call void @"github.com/goplus/lib/py/math.init"()
// CHECK-NEXT:   call void @"github.com/goplus/lib/py/std.init"()
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load ptr, ptr @__llgo_py.builtins, align 8
// CHECK-NEXT:   call void (ptr, ...) @llgoLoadPyModSyms(ptr %[[TMP1]], ptr @[[GLOB6]], ptr @__llgo_py.builtins.abs, ptr @[[GLOB7]], ptr @__llgo_py.builtins.print, ptr null)
// CHECK-NEXT:   br label %_llgo_[[BB2]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// CHECK-NEXT:   store i64 100, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.Slice" @"{{.*}}/runtime/internal/runtime.StringToBytes"(%"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 })
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = alloca [3 x i8], align 1
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP2]], i8 0, i64 3, i1 false)
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds i8, ptr %[[TMP2]], i64 0
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds i8, ptr %[[TMP2]], i64 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds i8, ptr %[[TMP2]], i64 2
// CHECK-NEXT:   store i8 1, ptr %[[TMP3]], align 1
// CHECK-NEXT:   store i8 2, ptr %[[TMP4]], align 1
// CHECK-NEXT:   store i8 3, ptr %[[TMP5]], align 1
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load [3 x i8], ptr %[[TMP2]], align 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = call ptr @PyList_New(i64 14)
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call ptr @PyBool_FromLong(i32 -1)
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 0, ptr %[[TMP8]])
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = call ptr @PyBool_FromLong(i32 0)
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 1, ptr %[[TMP10]])
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = call ptr @PyLong_FromLongLong(i64 1)
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 2, ptr %[[TMP12]])
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call ptr @PyFloat_FromDouble(double 0x4000CCCCC0000000)
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 3, ptr %[[TMP14]])
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = call ptr @PyFloat_FromDouble(double 3.100000e+00)
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 4, ptr %[[TMP16]])
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = call ptr @PyLong_FromUnsignedLongLong(i64 4)
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 5, ptr %[[TMP18]])
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = call ptr @PyComplex_FromDoubles(double 1.000000e+00, double 2.000000e+00)
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 6, ptr %[[TMP20]])
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = call ptr @PyComplex_FromDoubles(double 3.000000e+00, double 4.000000e+00)
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 7, ptr %[[TMP22]])
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = call ptr @PyUnicode_FromStringAndSize(ptr @[[GLOB1]], i64 5)
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 8, ptr %[[TMP24]])
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP1]], 1
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = call ptr @PyByteArray_FromStringAndSize(ptr %[[TMP26]], i64 %[[TMP27]])
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 9, ptr %[[TMP28]])
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = alloca [3 x i8], align 1
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP30]], i8 0, i64 3, i1 false)
// CHECK-NEXT:   store [3 x i8] %[[TMP6]], ptr %[[TMP30]], align 1
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = getelementptr inbounds ptr, ptr %[[TMP30]], i64 0
// CHECK-NEXT:   %[[TMP32:[0-9]+]] = call ptr @PyBytes_FromStringAndSize(ptr %[[TMP31]], i64 3)
// CHECK-NEXT:   %[[TMP33:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 10, ptr %[[TMP32]])
// CHECK-NEXT:   %[[TMP34:[0-9]+]] = call ptr @PyBytes_FromStringAndSize(ptr null, i64 0)
// CHECK-NEXT:   %[[TMP35:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 11, ptr %[[TMP34]])
// CHECK-NEXT:   %[[TMP36:[0-9]+]] = ptrtoint ptr %[[TMP0]] to i64
// CHECK-NEXT:   %[[TMP37:[0-9]+]] = call ptr @PyLong_FromUnsignedLongLong(i64 %[[TMP36]])
// CHECK-NEXT:   %[[TMP38:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 12, ptr %[[TMP37]])
// CHECK-NEXT:   %[[TMP39:[0-9]+]] = ptrtoint ptr %[[TMP0]] to i64
// CHECK-NEXT:   %[[TMP40:[0-9]+]] = call ptr @PyLong_FromUnsignedLongLong(i64 %[[TMP39]])
// CHECK-NEXT:   %[[TMP41:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 13, ptr %[[TMP40]])
// CHECK-NEXT:   %[[TMP42:[0-9]+]] = load ptr, ptr @__llgo_py.math, align 8
// CHECK-NEXT:   %[[TMP43:[0-9]+]] = call ptr @PyObject_GetAttrString(ptr %[[TMP42]], ptr @[[GLOB2]])
// CHECK-NEXT:   %[[TMP44:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP45:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.abs, align 8
// CHECK-NEXT:   %[[TMP46:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP44]], i64 0, ptr %[[TMP45]])
// CHECK-NEXT:   %[[TMP47:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.print, align 8
// CHECK-NEXT:   %[[TMP48:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP44]], i64 1, ptr %[[TMP47]])
// CHECK-NEXT:   %[[TMP49:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP44]], i64 2, ptr %[[TMP43]])
// CHECK-NEXT:   %[[TMP50:[0-9]+]] = call i64 @PyList_Size(ptr %[[TMP7]])
// CHECK-NEXT:   %[[TMP51:[0-9]+]] = call i64 @PyList_Size(ptr %[[TMP44]])
// CHECK-NEXT:   %[[TMP52:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB3]], i64 %[[TMP50]], i64 %[[TMP51]])
// CHECK-NEXT:   %[[TMP53:[0-9]+]] = call ptr @PyList_GetItem(ptr %[[TMP7]], i64 12)
// CHECK-NEXT:   %[[TMP54:[0-9]+]] = call i32 @PyObject_IsTrue(ptr %[[TMP53]])
// CHECK-NEXT:   %[[TMP55:[0-9]+]] = call ptr @PyList_GetItem(ptr %[[TMP7]], i64 13)
// CHECK-NEXT:   %[[TMP56:[0-9]+]] = call i32 @PyObject_IsTrue(ptr %[[TMP55]])
// CHECK-NEXT:   %[[TMP57:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB4]], i32 %[[TMP54]], i32 %[[TMP56]])
// CHECK-NEXT:   %[[TMP58:[0-9]+]] = call ptr @PyList_GetItem(ptr %[[TMP44]], i64 2)
// CHECK-NEXT:   %[[TMP59:[0-9]+]] = call double @PyFloat_AsDouble(ptr %[[TMP58]])
// CHECK-NEXT:   %[[TMP60:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB5]], double %[[TMP59]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
