// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.genInts\E|\Qmain.(*generator).next\E|\Qmain.main\E|\Qmain.main$1\E|\Qmain.(*generator).next$bound\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

import (
	"github.com/goplus/lib/c"
)

// genInts invokes the supplied code/environment pair once per output slot and
// stores that result into the slice at the checked loop index.

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}

func genInts(n int, gen func() c.Int) []c.Int {
	a := make([]c.Int, n)
	for i := range a {
		a[i] = gen()
	}
	return a
}

func (g *generator) next() c.Int {
	g.val++
	return g.val
}

type generator struct {
	val c.Int
}

func main() {
	for _, v := range genInts(5, c.Rand) {

		c.Printf(c.Str("%d\n"), v)
	}

	initVal := c.Int(1)
	ints := genInts(5, func() c.Int {
		initVal *= 2
		return initVal
	})
	for _, v := range ints {
		c.Printf(c.Str("%d\n"), v)
	}

	g := &generator{val: 1}
	for _, v := range genInts(5, g.next) {
		c.Printf(c.Str("%d\n"), v)
	}
}

// CHECK-LABEL: define i32 @"main.(*generator).next"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load i32, ptr %[[TMP1]], align 4
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = add i32 %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   store i32 %[[TMP3]], ptr %[[TMP4]], align 4
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load i32, ptr %[[TMP5]], align 4
// CHECK-NEXT:   ret i32 %[[TMP6]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca { ptr, ptr }, align 8
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// DARWIN-ARM64-NEXT:   call void @main.genInts(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP2]], i64 5, { ptr, ptr } { ptr @rand, ptr null })
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 1
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   store { ptr, ptr } { ptr @rand, ptr null }, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP4]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP4]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load ptr, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   call void @main.genInts(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP9]], i64 5, ptr %[[TMP6]], ptr %[[TMP8]])
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP6:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// DARWIN-ARM64-NEXT:   %[[TMP6]] = add i64 %[[TMP5]], 1
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = icmp slt i64 %[[TMP6]], %[[TMP4]]
// DARWIN-ARM64-NEXT:   br i1 %[[TMP7]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP13:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// LINUX-AMD64-NEXT:   %[[TMP13]] = add i64 %[[TMP12]], 1
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = icmp slt i64 %[[TMP13]], %[[TMP11]]
// LINUX-AMD64-NEXT:   br i1 %[[TMP14]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 0
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 1
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = icmp slt i64 %[[TMP6]], 0
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = icmp uge i64 %[[TMP6]], %[[TMP9]]
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = or i1 %[[TMP11]], %[[TMP10]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP12]], i64 %[[TMP6]], i1 true, i64 %[[TMP9]])
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP8]], i64 %[[TMP6]]
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = load i32, ptr %[[TMP13]], align 4
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB0]], i32 %[[TMP14]])
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], 0
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], 1
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = icmp slt i64 %[[TMP13]], 0
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = icmp uge i64 %[[TMP13]], %[[TMP16]]
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = or i1 %[[TMP18]], %[[TMP17]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP19]], i64 %[[TMP13]], i1 true, i64 %[[TMP16]])
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP15]], i64 %[[TMP13]]
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = load i32, ptr %[[TMP20]], align 4
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB0]], i32 %[[TMP21]])
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// DARWIN-ARM64-NEXT:   store i32 1, ptr %[[TMP16]], align 4
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// DARWIN-ARM64-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP17]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store ptr %[[TMP16]], ptr %[[TMP18]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1", ptr undef }, ptr %[[TMP17]], 1
// DARWIN-ARM64-NEXT:   call void @main.genInts(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP1]], i64 5, { ptr, ptr } %[[TMP19]])
// DARWIN-ARM64-NEXT:   %[[TMP20:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP21:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP20]], 1
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// LINUX-AMD64-NEXT:   store i32 1, ptr %[[TMP23]], align 4
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP24]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP23]], ptr %[[TMP25]], align 8
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1", ptr undef }, ptr %[[TMP24]], 1
// LINUX-AMD64-NEXT:   store { ptr, ptr } %[[TMP26]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = load ptr, ptr %[[TMP27]], align 8
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = load ptr, ptr %[[TMP29]], align 8
// LINUX-AMD64-NEXT:   call void @main.genInts(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP3]], i64 5, ptr %[[TMP28]], ptr %[[TMP30]])
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP31]], 1
// CHECK-NEXT:   br label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// DARWIN-ARM64-NEXT:   %[[TMP22:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB3]] ], [ %[[TMP23:[0-9]+]], %_llgo_[[BB5:[0-9]+]] ]
// DARWIN-ARM64-NEXT:   %[[TMP23]] = add i64 %[[TMP22]], 1
// DARWIN-ARM64-NEXT:   %[[TMP24:[0-9]+]] = icmp slt i64 %[[TMP23]], %[[TMP21]]
// DARWIN-ARM64-NEXT:   br i1 %[[TMP24]], label %_llgo_[[BB5]], label %_llgo_[[BB6:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB3]] ], [ %[[TMP34:[0-9]+]], %_llgo_[[BB5:[0-9]+]] ]
// LINUX-AMD64-NEXT:   %[[TMP34]] = add i64 %[[TMP33]], 1
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = icmp slt i64 %[[TMP34]], %[[TMP32]]
// LINUX-AMD64-NEXT:   br i1 %[[TMP35]], label %_llgo_[[BB5]], label %_llgo_[[BB6:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// DARWIN-ARM64-NEXT:   %[[TMP25:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP20]], 0
// DARWIN-ARM64-NEXT:   %[[TMP26:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP20]], 1
// DARWIN-ARM64-NEXT:   %[[TMP27:[0-9]+]] = icmp slt i64 %[[TMP23]], 0
// DARWIN-ARM64-NEXT:   %[[TMP28:[0-9]+]] = icmp uge i64 %[[TMP23]], %[[TMP26]]
// DARWIN-ARM64-NEXT:   %[[TMP29:[0-9]+]] = or i1 %[[TMP28]], %[[TMP27]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP29]], i64 %[[TMP23]], i1 true, i64 %[[TMP26]])
// DARWIN-ARM64-NEXT:   %[[TMP30:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP25]], i64 %[[TMP23]]
// DARWIN-ARM64-NEXT:   %[[TMP31:[0-9]+]] = load i32, ptr %[[TMP30]], align 4
// DARWIN-ARM64-NEXT:   %[[TMP32:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB1]], i32 %[[TMP31]])
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP31]], 0
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP31]], 1
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = icmp slt i64 %[[TMP34]], 0
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = icmp uge i64 %[[TMP34]], %[[TMP37]]
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = or i1 %[[TMP39]], %[[TMP38]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP40]], i64 %[[TMP34]], i1 true, i64 %[[TMP37]])
// LINUX-AMD64-NEXT:   %[[TMP41:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP36]], i64 %[[TMP34]]
// LINUX-AMD64-NEXT:   %[[TMP42:[0-9]+]] = load i32, ptr %[[TMP41]], align 4
// LINUX-AMD64-NEXT:   %[[TMP43:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB1]], i32 %[[TMP42]])
// CHECK-NEXT:   br label %_llgo_[[BB4]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB6]]:
// DARWIN-ARM64-NEXT:   %[[TMP33:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// DARWIN-ARM64-NEXT:   %[[TMP34:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP33]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store i32 1, ptr %[[TMP34]], align 4
// DARWIN-ARM64-NEXT:   %[[TMP35:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// DARWIN-ARM64-NEXT:   %[[TMP36:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP35]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store ptr %[[TMP33]], ptr %[[TMP36]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP37:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.(*generator).next$bound", ptr undef }, ptr %[[TMP35]], 1
// DARWIN-ARM64-NEXT:   call void @main.genInts(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0]], i64 5, { ptr, ptr } %[[TMP37]])
// DARWIN-ARM64-NEXT:   %[[TMP38:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP39:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP38]], 1
// LINUX-AMD64-NEXT:   %[[TMP44:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 4)
// LINUX-AMD64-NEXT:   %[[TMP45:[0-9]+]] = getelementptr inbounds %main.generator, ptr %[[TMP44]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store i32 1, ptr %[[TMP45]], align 4
// LINUX-AMD64-NEXT:   %[[TMP46:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP47:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP46]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP44]], ptr %[[TMP47]], align 8
// LINUX-AMD64-NEXT:   %[[TMP48:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.(*generator).next$bound", ptr undef }, ptr %[[TMP46]], 1
// LINUX-AMD64-NEXT:   store { ptr, ptr } %[[TMP48]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP49:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP50:[0-9]+]] = load ptr, ptr %[[TMP49]], align 8
// LINUX-AMD64-NEXT:   %[[TMP51:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP52:[0-9]+]] = load ptr, ptr %[[TMP51]], align 8
// LINUX-AMD64-NEXT:   call void @main.genInts(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP1]], i64 5, ptr %[[TMP50]], ptr %[[TMP52]])
// LINUX-AMD64-NEXT:   %[[TMP53:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP54:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP53]], 1
// CHECK-NEXT:   br label %_llgo_[[BB7:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB7]]:
// DARWIN-ARM64-NEXT:   %[[TMP40:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB6]] ], [ %[[TMP41:[0-9]+]], %_llgo_[[BB8:[0-9]+]] ]
// DARWIN-ARM64-NEXT:   %[[TMP41]] = add i64 %[[TMP40]], 1
// DARWIN-ARM64-NEXT:   %[[TMP42:[0-9]+]] = icmp slt i64 %[[TMP41]], %[[TMP39]]
// DARWIN-ARM64-NEXT:   br i1 %[[TMP42]], label %_llgo_[[BB8]], label %_llgo_[[BB9:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP55:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB6]] ], [ %[[TMP56:[0-9]+]], %_llgo_[[BB8:[0-9]+]] ]
// LINUX-AMD64-NEXT:   %[[TMP56]] = add i64 %[[TMP55]], 1
// LINUX-AMD64-NEXT:   %[[TMP57:[0-9]+]] = icmp slt i64 %[[TMP56]], %[[TMP54]]
// LINUX-AMD64-NEXT:   br i1 %[[TMP57]], label %_llgo_[[BB8]], label %_llgo_[[BB9:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB8]]:
// DARWIN-ARM64-NEXT:   %[[TMP43:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP38]], 0
// DARWIN-ARM64-NEXT:   %[[TMP44:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP38]], 1
// DARWIN-ARM64-NEXT:   %[[TMP45:[0-9]+]] = icmp slt i64 %[[TMP41]], 0
// DARWIN-ARM64-NEXT:   %[[TMP46:[0-9]+]] = icmp uge i64 %[[TMP41]], %[[TMP44]]
// DARWIN-ARM64-NEXT:   %[[TMP47:[0-9]+]] = or i1 %[[TMP46]], %[[TMP45]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP47]], i64 %[[TMP41]], i1 true, i64 %[[TMP44]])
// DARWIN-ARM64-NEXT:   %[[TMP48:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP43]], i64 %[[TMP41]]
// DARWIN-ARM64-NEXT:   %[[TMP49:[0-9]+]] = load i32, ptr %[[TMP48]], align 4
// DARWIN-ARM64-NEXT:   %[[TMP50:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], i32 %[[TMP49]])
// LINUX-AMD64-NEXT:   %[[TMP58:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP53]], 0
// LINUX-AMD64-NEXT:   %[[TMP59:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP53]], 1
// LINUX-AMD64-NEXT:   %[[TMP60:[0-9]+]] = icmp slt i64 %[[TMP56]], 0
// LINUX-AMD64-NEXT:   %[[TMP61:[0-9]+]] = icmp uge i64 %[[TMP56]], %[[TMP59]]
// LINUX-AMD64-NEXT:   %[[TMP62:[0-9]+]] = or i1 %[[TMP61]], %[[TMP60]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP62]], i64 %[[TMP56]], i1 true, i64 %[[TMP59]])
// LINUX-AMD64-NEXT:   %[[TMP63:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP58]], i64 %[[TMP56]]
// LINUX-AMD64-NEXT:   %[[TMP64:[0-9]+]] = load i32, ptr %[[TMP63]], align 4
// LINUX-AMD64-NEXT:   %[[TMP65:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], i32 %[[TMP64]])
// CHECK-NEXT:   br label %_llgo_[[BB7]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB9]]:
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @"main.main$1"(
// CHECK-SAME: ptr {{(nest|swiftself)}} %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load i32, ptr %[[TMP2]], align 4
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = mul i32 %[[TMP3]], 2
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   store i32 %[[TMP4]], ptr %[[TMP5]], align 4
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = load i32, ptr %[[TMP6]], align 4
// CHECK-NEXT:   ret i32 %[[TMP7]]
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @"main.(*generator).next$bound"(
// CHECK-SAME: ptr {{(nest|swiftself)}} %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = extractvalue { ptr } %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call i32 @"main.(*generator).next"(ptr %[[TMP2]])
// CHECK-NEXT:   ret i32 %[[TMP3]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.genInts(
// DARWIN-ARM64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]], { ptr, ptr } %[[TMP2:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]], ptr %[[TMP2:[0-9]+]], ptr %[[TMP3:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.MakeSlice"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP3]], i64 %[[TMP1]], i64 %[[TMP1]], i64 4)
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP4]], 1
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP4]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP2]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP4]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store ptr %[[TMP3]], ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.MakeSlice"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP8]], i64 %[[TMP1]], i64 %[[TMP1]], i64 4)
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP9]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP7:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// DARWIN-ARM64-NEXT:   %[[TMP7]] = add i64 %[[TMP6]], 1
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = icmp slt i64 %[[TMP7]], %[[TMP5]]
// DARWIN-ARM64-NEXT:   br i1 %[[TMP8]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP12:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// LINUX-AMD64-NEXT:   %[[TMP12]] = add i64 %[[TMP11]], 1
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = icmp slt i64 %[[TMP12]], %[[TMP10]]
// LINUX-AMD64-NEXT:   br i1 %[[TMP13]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP2]], 1
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP2]], 0
// DARWIN-ARM64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP10]])
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = call i32 %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP9]])
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP4]], 0
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = icmp slt i64 %[[TMP7]], 0
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = icmp uge i64 %[[TMP7]], %[[TMP13]]
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = or i1 %[[TMP15]], %[[TMP14]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP16]], i64 %[[TMP7]], i1 true, i64 %[[TMP13]])
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP12]], i64 %[[TMP7]]
// DARWIN-ARM64-NEXT:   store i32 %[[TMP11]], ptr %[[TMP17]], align 4
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP7]], 1
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP7]], 0
// LINUX-AMD64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP15]])
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = call i32 %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP14]])
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP9]], 0
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP9]], 1
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = icmp slt i64 %[[TMP12]], 0
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = icmp uge i64 %[[TMP12]], %[[TMP18]]
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = or i1 %[[TMP20]], %[[TMP19]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP21]], i64 %[[TMP12]], i1 true, i64 %[[TMP18]])
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds i32, ptr %[[TMP17]], i64 %[[TMP12]]
// LINUX-AMD64-NEXT:   store i32 %[[TMP16]], ptr %[[TMP22]], align 4
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP4]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP9]], ptr %[[TMP0]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
