// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.CFmt.Printf\E|\Qmain.(*CFmt).Printf\E|\Qmain.(*CFmt).SetFormat\E|\Qmain.main\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

import (
	"unsafe"

	"github.com/goplus/lib/c"
)

// Variadic C-linked methods must forward their receiver-derived format pointer
// and preserve the variadic arguments for direct and interface calls.

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [9 x i8] c"%s (%d)\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [6 x i8] c"hello\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [9 x i8] c"(%d) %s\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB3:[0-9]+]] = private unnamed_addr constant [6 x i8] c"world\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB18:[0-9]+]] = private unnamed_addr constant [12 x i8] c"%s (%d,%d)\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB19:[0-9]+]] = private unnamed_addr constant [5 x i8] c"ifmt\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB20:[0-9]+]] = private unnamed_addr constant [5 x i8] c"error", align 1{{$}}

//llgo:link (*T).Printf C.printf
func (*T) Printf(__llgo_va_list ...any) c.Int { return 0 }

type T c.Char

//go:linkname Printf C.printf
func Printf(format *c.Char, __llgo_va_list ...any) c.Int

type CFmt struct {
	*T
}

func (f *CFmt) SetFormat(fmt *c.Char) {
	f.T = (*T)(unsafe.Pointer(fmt))
}

type IFmt interface {
	SetFormat(fmt *c.Char)
	Printf(__llgo_va_list ...any) c.Int
}

func main() {
	cfmt := &CFmt{}
	cfmt.SetFormat(c.Str("%s (%d)\n"))
	cfmt.Printf(c.Str("hello"), 100)
	cfmt.SetFormat(c.Str("(%d) %s\n"))
	cfmt.Printf(200, c.Str("world"))

	var i any = &CFmt{}
	ifmt, ok := i.(IFmt)
	if !ok {
		panic("error")
	}
	ifmt.SetFormat(c.Str("%s (%d,%d)\n"))
	ifmt.Printf(c.Str("ifmt"), 100, 200)
}

// CHECK-LABEL: define i32 @main.CFmt.Printf(
// DARWIN-ARM64-SAME: i64 %[[TMP0:[0-9]+]], ...){{.*}} {
// LINUX-AMD64-SAME: %main.CFmt %[[TMP0:[0-9]+]], ...){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = alloca i64, align 8
// DARWIN-ARM64-NEXT:   store i64 %[[TMP0]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load %main.CFmt, ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = alloca %main.CFmt, align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP3]], i8 0, i64 8, i1 false)
// DARWIN-ARM64-NEXT:   store %main.CFmt %[[TMP2]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP1]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = load ptr, ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP5]])
// DARWIN-ARM64-NEXT:   ret i32 %[[TMP6]]
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %main.CFmt, align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP1]], i8 0, i64 8, i1 false)
// LINUX-AMD64-NEXT:   store %main.CFmt %[[TMP0]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = load ptr, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP3]])
// LINUX-AMD64-NEXT:   ret i32 %[[TMP4]]
// CHECK-NEXT: }

// CHECK-LABEL: define i32 @"main.(*CFmt).Printf"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]], ...){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load ptr, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP2]])
// CHECK-NEXT:   ret i32 %[[TMP3]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.(*CFmt).SetFormat"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   store ptr %[[TMP1]], ptr %[[TMP2]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// DARWIN-ARM64-NEXT:   call void @"main.(*CFmt).SetFormat"(ptr %[[TMP0]], ptr @[[GLOB0]])
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP0]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load ptr, ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP2]], ptr @[[GLOB1]], i64 100)
// DARWIN-ARM64-NEXT:   call void @"main.(*CFmt).SetFormat"(ptr %[[TMP0]], ptr @[[GLOB2]])
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// LINUX-AMD64-NEXT:   call void @"main.(*CFmt).SetFormat"(ptr %[[TMP3]], ptr @[[GLOB0]])
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP3]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load ptr, ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP5]], i64 200, ptr @[[GLOB3]])
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"*_llgo_main.CFmt", ptr undef }, ptr %[[TMP7]], 1
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP8]], 0
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.Implements"(ptr @_llgo_main.IFmt, ptr %[[TMP9]])
// DARWIN-ARM64-NEXT:   br i1 %[[TMP10]], label %_llgo_[[BB3:[0-9]+]], label %_llgo_[[BB4:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP5]], ptr @[[GLOB1]], i64 100)
// LINUX-AMD64-NEXT:   call void @"main.(*CFmt).SetFormat"(ptr %[[TMP3]], ptr @[[GLOB2]])
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %main.CFmt, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load ptr, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = call i32 (ptr, ...) @printf(ptr %[[TMP8]], i64 200, ptr @[[GLOB3]])
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"*_llgo_main.CFmt", ptr undef }, ptr %[[TMP10]], 1
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP11]], 0
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.Implements"(ptr @_llgo_main.IFmt, ptr %[[TMP12]])
// LINUX-AMD64-NEXT:   br i1 %[[TMP13]], label %_llgo_[[BB3:[0-9]+]], label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB20]], i64 5 }, ptr %[[TMP11]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP11]], 1
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP12]])
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB20]], i64 5 }, ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP14]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP15]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = load ptr, ptr %[[TMP16]], align 8
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = load ptr, ptr %[[TMP18]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(ptr %[[TMP17]], ptr %[[TMP19]])
// CHECK-NEXT:   unreachable
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP37:[0-9]+]])
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP37]], 0
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = getelementptr ptr, ptr %[[TMP14]], i64 4
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = load ptr, ptr %[[TMP15]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP16]], 0
// DARWIN-ARM64-NEXT:   %[[TMP18:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP17]], ptr %[[TMP13]], 1
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP18]], 1
// DARWIN-ARM64-NEXT:   %[[TMP20:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP18]], 0
// DARWIN-ARM64-NEXT:   call void %[[TMP20]](ptr %[[TMP19]], ptr @[[GLOB18]])
// DARWIN-ARM64-NEXT:   %[[TMP21:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP37]])
// DARWIN-ARM64-NEXT:   %[[TMP22:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP37]], 0
// DARWIN-ARM64-NEXT:   %[[TMP23:[0-9]+]] = getelementptr ptr, ptr %[[TMP22]], i64 3
// DARWIN-ARM64-NEXT:   %[[TMP24:[0-9]+]] = load ptr, ptr %[[TMP23]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP25:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP24]], 0
// DARWIN-ARM64-NEXT:   %[[TMP26:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP25]], ptr %[[TMP21]], 1
// DARWIN-ARM64-NEXT:   %[[TMP27:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP26]], 1
// DARWIN-ARM64-NEXT:   %[[TMP28:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP26]], 0
// DARWIN-ARM64-NEXT:   %[[TMP29:[0-9]+]] = call i32 (ptr, ...) %[[TMP28]](ptr %[[TMP27]], ptr @[[GLOB19]], i64 100, i64 200)
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" %[[TMP52:[0-9]+]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = load ptr, ptr %[[TMP20]], align 8
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = load ptr, ptr %[[TMP22]], align 8
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(ptr %[[TMP21]], ptr %[[TMP23]])
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP52]], 0
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = getelementptr ptr, ptr %[[TMP25]], i64 4
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = load ptr, ptr %[[TMP26]], align 8
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP27]], 0
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP28]], ptr %[[TMP24]], 1
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP29]], 1
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP29]], 0
// LINUX-AMD64-NEXT:   call void %[[TMP31]](ptr %[[TMP30]], ptr @[[GLOB18]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" %[[TMP52]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = load ptr, ptr %[[TMP32]], align 8
// LINUX-AMD64-NEXT:   %[[TMP34:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = load ptr, ptr %[[TMP34]], align 8
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(ptr %[[TMP33]], ptr %[[TMP35]])
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP52]], 0
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = getelementptr ptr, ptr %[[TMP37]], i64 3
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = load ptr, ptr %[[TMP38]], align 8
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP39]], 0
// LINUX-AMD64-NEXT:   %[[TMP41:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP40]], ptr %[[TMP36]], 1
// LINUX-AMD64-NEXT:   %[[TMP42:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP41]], 1
// LINUX-AMD64-NEXT:   %[[TMP43:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP41]], 0
// LINUX-AMD64-NEXT:   %[[TMP44:[0-9]+]] = call i32 (ptr, ...) %[[TMP43]](ptr %[[TMP42]], ptr @[[GLOB19]], i64 100, i64 200)
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// DARWIN-ARM64-NEXT:   %[[TMP30:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP8]], 1
// DARWIN-ARM64-NEXT:   %[[TMP31:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewItab"(ptr @"_llgo_iface$a85zs5wWQQoPIERm_en8plssh4spdIeeXZPC-E0TDh0", ptr %[[TMP9]])
// DARWIN-ARM64-NEXT:   %[[TMP32:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" undef, ptr %[[TMP31]], 0
// DARWIN-ARM64-NEXT:   %[[TMP33:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP32]], ptr %[[TMP30]], 1
// DARWIN-ARM64-NEXT:   %[[TMP34:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } undef, %"{{.*}}/runtime/internal/runtime.iface" %[[TMP33]], 0
// DARWIN-ARM64-NEXT:   %[[TMP35:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } %[[TMP34]], i1 true, 1
// LINUX-AMD64-NEXT:   %[[TMP45:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP11]], 1
// LINUX-AMD64-NEXT:   %[[TMP46:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewItab"(ptr @"_llgo_iface$a85zs5wWQQoPIERm_en8plssh4spdIeeXZPC-E0TDh0", ptr %[[TMP12]])
// LINUX-AMD64-NEXT:   %[[TMP47:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" undef, ptr %[[TMP46]], 0
// LINUX-AMD64-NEXT:   %[[TMP48:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP47]], ptr %[[TMP45]], 1
// LINUX-AMD64-NEXT:   %[[TMP49:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } undef, %"{{.*}}/runtime/internal/runtime.iface" %[[TMP48]], 0
// LINUX-AMD64-NEXT:   %[[TMP50:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } %[[TMP49]], i1 true, 1
// CHECK-NEXT:   br label %_llgo_[[BB5:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   br label %_llgo_[[BB5]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// DARWIN-ARM64-NEXT:   %[[TMP36:[0-9]+]] = phi { %"{{.*}}/runtime/internal/runtime.iface", i1 } [ %[[TMP35]], %_llgo_[[BB3]] ], [ zeroinitializer, %_llgo_[[BB4]] ]
// DARWIN-ARM64-NEXT:   %[[TMP37]] = extractvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } %[[TMP36]], 0
// DARWIN-ARM64-NEXT:   %[[TMP38:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } %[[TMP36]], 1
// DARWIN-ARM64-NEXT:   br i1 %[[TMP38]], label %_llgo_[[BB2]], label %_llgo_[[BB1]]
// LINUX-AMD64-NEXT:   %[[TMP51:[0-9]+]] = phi { %"{{.*}}/runtime/internal/runtime.iface", i1 } [ %[[TMP50]], %_llgo_[[BB3]] ], [ zeroinitializer, %_llgo_[[BB4]] ]
// LINUX-AMD64-NEXT:   %[[TMP52]] = extractvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } %[[TMP51]], 0
// LINUX-AMD64-NEXT:   %[[TMP53:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.iface", i1 } %[[TMP51]], 1
// LINUX-AMD64-NEXT:   br i1 %[[TMP53]], label %_llgo_[[BB2]], label %_llgo_[[BB1]]
// CHECK-NEXT: }
