// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.recursive\E|\Qmain.recur1[main.T.1.0]\E|\Qmain.recur2[main.T.1.0]\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [5 x i8] c"error", align 1{{$}}

func main() {
	recursive()
}

func recursive() {
	type T int
	if got, want := recur1[T](5), T(110); got != want {
		panic("error")
	}
}

type Integer interface {
	~int | ~int32 | ~int64
}

func recur1[T Integer](n T) T {
	if n == 0 || n == 1 {
		return T(1)
	} else {
		return n * recur2(n-1)
	}
}

func recur2[T Integer](n T) T {
	list := make([]T, n)
	for i, _ := range list {
		list[i] = T(i + 1)
	}
	var sum T
	for _, elt := range list {
		sum += elt
	}
	return sum + recur1(n-1)
}

// recur1 preserves both base cases and passes n-1 to recur2 before multiplying.

// recur2 builds [1..n], sums it, and adds recur1(n-1).

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   call void @main.recursive()
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.recursive(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = call i64 @"main.recur1[main.T.1.0]"(i64 5)
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = icmp ne i64 %[[TMP0]], 110
// DARWIN-ARM64-NEXT:   br i1 %[[TMP1]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = call i64 @"main.recur1[main.T.1.0]"(i64 5)
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = icmp ne i64 %[[TMP1]], 110
// LINUX-AMD64-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP2]], 1
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP3]])
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP3]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP4]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load ptr, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(ptr %[[TMP6]], ptr %[[TMP8]])
// CHECK-NEXT:   unreachable
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce i64 @"main.recur1[main.T.1.0]"(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq i64 %[[TMP0]], 0
// CHECK-NEXT:   br i1 %[[TMP1]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   ret i64 1
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = sub i64 %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call i64 @"main.recur2[main.T.1.0]"(i64 %[[TMP2]])
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = mul i64 %[[TMP0]], %[[TMP3]]
// CHECK-NEXT:   ret i64 %[[TMP4]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = icmp eq i64 %[[TMP0]], 1
// CHECK-NEXT:   br i1 %[[TMP5]], label %_llgo_[[BB1]], label %_llgo_[[BB2]]
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce i64 @"main.recur2[main.T.1.0]"(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.MakeSlice"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP1]], i64 %[[TMP0]], i64 %[[TMP0]], i64 8)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP5:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP5]] = add i64 %[[TMP4]], 1
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = icmp slt i64 %[[TMP5]], %[[TMP3]]
// CHECK-NEXT:   br i1 %[[TMP6]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = add i64 %[[TMP5]], 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = icmp slt i64 %[[TMP5]], 0
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = icmp uge i64 %[[TMP5]], %[[TMP9]]
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = or i1 %[[TMP11]], %[[TMP10]]
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP12]], i64 %[[TMP5]], i1 true, i64 %[[TMP9]])
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP8]], i64 %[[TMP5]]
// CHECK-NEXT:   store i64 %[[TMP7]], ptr %[[TMP13]], align 8
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 1
// CHECK-NEXT:   br label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = phi i64 [ 0, %_llgo_[[BB3]] ], [ %[[TMP26:[0-9]+]], %_llgo_[[BB5:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB3]] ], [ %[[TMP17:[0-9]+]], %_llgo_[[BB5]] ]
// CHECK-NEXT:   %[[TMP17]] = add i64 %[[TMP16]], 1
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = icmp slt i64 %[[TMP17]], %[[TMP14]]
// CHECK-NEXT:   br i1 %[[TMP18]], label %_llgo_[[BB5]], label %_llgo_[[BB6:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 0
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = icmp slt i64 %[[TMP17]], 0
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = icmp uge i64 %[[TMP17]], %[[TMP20]]
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = or i1 %[[TMP22]], %[[TMP21]]
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP23]], i64 %[[TMP17]], i1 true, i64 %[[TMP20]])
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP19]], i64 %[[TMP17]]
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = load i64, ptr %[[TMP24]], align 8
// CHECK-NEXT:   %[[TMP26]] = add i64 %[[TMP15]], %[[TMP25]]
// CHECK-NEXT:   br label %_llgo_[[BB4]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB6]]:
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = sub i64 %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = call i64 @"main.recur1[main.T.1.0]"(i64 %[[TMP27]])
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = add i64 %[[TMP15]], %[[TMP28]]
// CHECK-NEXT:   ret i64 %[[TMP29]]
// CHECK-NEXT: }
