// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.hi\E|\Qmain.incVal\E|\Qmain.main\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

import (
	"github.com/goplus/lib/c"
)

// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [7 x i8] c"%s %d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB3:[0-9]+]] = private unnamed_addr constant [6 x i8] c"Hello\00", align 1{{$}}

func hi(a any) *c.Char {
	return a.(*c.Char)
}

func incVal(a any) int {
	return a.(int) + 1
}

func main() {
	c.Printf(c.Str("%s %d\n"), hi(c.Str("Hello")), incVal(100))
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = call ptr @main.hi(%"{{.*}}/runtime/internal/runtime.eface" { ptr @"*_llgo_int8", ptr @[[GLOB3]] })
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// DARWIN-ARM64-NEXT:   store i64 100, ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP1]], 1
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = call i64 @main.incVal(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP2]])
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], ptr %[[TMP0]], i64 %[[TMP3]])
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" { ptr @"*_llgo_int8", ptr @[[GLOB3]] }, ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = load ptr, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load ptr, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = call ptr @main.hi(ptr %[[TMP3]], ptr %[[TMP5]])
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   store i64 100, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP7]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP8]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = load ptr, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = load ptr, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = call i64 @main.incVal(ptr %[[TMP10]], ptr %[[TMP12]])
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], ptr %[[TMP6]], i64 %[[TMP13]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define ptr @main.hi(
// DARWIN-ARM64-SAME: %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 0
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = icmp eq ptr %[[TMP1]], @"*_llgo_int8"
// DARWIN-ARM64-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 0
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = icmp eq ptr %[[TMP6]], @"*_llgo_int8"
// LINUX-AMD64-NEXT:   br i1 %[[TMP7]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 1
// DARWIN-ARM64-NEXT:   ret ptr %[[TMP3]]
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 1
// LINUX-AMD64-NEXT:   ret ptr %[[TMP8]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP1]], ptr @"*_llgo_int8")
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP6]], ptr @"*_llgo_int8")
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @main.incVal(
// DARWIN-ARM64-SAME: %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 0
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = icmp eq ptr %[[TMP1]], @_llgo_int
// DARWIN-ARM64-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 0
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = icmp eq ptr %[[TMP6]], @_llgo_int
// LINUX-AMD64-NEXT:   br i1 %[[TMP7]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 1
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = load i64, ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = add i64 %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   ret i64 %[[TMP5]]
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 1
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = load i64, ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = add i64 %[[TMP9]], 1
// LINUX-AMD64-NEXT:   ret i64 %[[TMP10]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP1]], ptr @_llgo_int)
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP6]], ptr @_llgo_int)
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }
