// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.hi\E|\Qmain.incVal\E|\Qmain.main\E) --check-globals=smart
package main

import (
	"github.com/goplus/lib/c"
)

// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [7 x i8] c"%s %d\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB3:[0-9]+]] = private unnamed_addr constant [6 x i8] c"Hello\00", align 1{{$}}

func hi(a any) *c.Char {
	return a.(*c.Char)
}

func incVal(a any) int {
	return a.(int) + 1
}

func main() {
	c.Printf(c.Str("%s %d\n"), hi(c.Str("Hello")), incVal(100))
}

// CHECK-LABEL: define ptr @main.hi(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp eq ptr %[[TMP1]], @"*_llgo_int8"
// CHECK-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 1
// CHECK-NEXT:   ret ptr %[[TMP3]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP1]], ptr @"*_llgo_int8")
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @main.incVal(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp eq ptr %[[TMP1]], @_llgo_int
// CHECK-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = load i64, ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = add i64 %[[TMP4]], 1
// CHECK-NEXT:   ret i64 %[[TMP5]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP1]], ptr @_llgo_int)
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @main.hi(%"{{.*}}/runtime/internal/runtime.eface" { ptr @"*_llgo_int8", ptr @[[GLOB3]] })
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 100, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP1]], 1
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call i64 @main.incVal(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP2]])
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], ptr %[[TMP0]], i64 %[[TMP3]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
