// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.test\E) --check-globals=smart
package main

import "github.com/goplus/lib/c"

// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1{{$}}

func main() {
	test(1, 2, 3)
}

func test(a ...any) {
	for _, v := range a {
		c.Printf(c.Str("%d\n"), v.(int))
	}
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 48)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP0]], i64 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 1, ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP2]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP3]], ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP0]], i64 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 2, ptr %[[TMP5]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP5]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP6]], ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP0]], i64 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 3, ptr %[[TMP8]], align 8
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP8]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP9]], ptr %[[TMP7]], align 8
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], i64 3, 1
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP11]], i64 3, 2
// CHECK-NEXT:   call void @main.test(%"{{.*}}/runtime/internal/runtime.Slice" %[[TMP12]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.test(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP3:[0-9]+]], %_llgo_[[BB4:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP3]] = add i64 %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp slt i64 %[[TMP3]], %[[TMP1]]
// CHECK-NEXT:   br i1 %[[TMP4]], label %_llgo_[[BB2:[0-9]+]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = icmp slt i64 %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = icmp uge i64 %[[TMP3]], %[[TMP6]]
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = or i1 %[[TMP8]], %[[TMP7]]
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP9]], i64 %[[TMP3]], i1 true, i64 %[[TMP6]])
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP5]], i64 %[[TMP3]]
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.eface", ptr %[[TMP10]], align 8
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP11]], 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = icmp eq ptr %[[TMP12]], @_llgo_int
// CHECK-NEXT:   br i1 %[[TMP13]], label %_llgo_[[BB4]], label %_llgo_[[BB5:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP11]], 1
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = load i64, ptr %[[TMP14]], align 8
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB1]], i64 %[[TMP15]])
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP12]], ptr @_llgo_int)
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }
