// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.main$1\E|\Qmain.main$1$1\E|\Qmain.main$2\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

func main() {
	func(resolve func(error)) {

		func(err error) {
			if err != nil {
				resolve(err)
				return
			}
			resolve(nil)
		}(nil)
	}(func(err error) {
	})
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   call void @"main.main$1"({ ptr, ptr } { ptr @"main.main$2", ptr null })
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   store { ptr, ptr } { ptr @"main.main$2", ptr null }, ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = load ptr, ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = load ptr, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   call void @"main.main$1"(ptr %[[TMP2]], ptr %[[TMP4]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.main$1"(
// DARWIN-ARM64-SAME: { ptr, ptr } %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// DARWIN-ARM64-NEXT:   store { ptr, ptr } %[[TMP0]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP2]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1$1", ptr undef }, ptr %[[TMP2]], 1
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP4]], 0
// DARWIN-ARM64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP6]])
// DARWIN-ARM64-NEXT:   call void %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP5]], %"{{.*}}/runtime/internal/runtime.iface" zeroinitializer)
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// LINUX-AMD64-NEXT:   store { ptr, ptr } %[[TMP5]], ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP8]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP7]], ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1$1", ptr undef }, ptr %[[TMP8]], 1
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP10]], 1
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP10]], 0
// LINUX-AMD64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP12]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" zeroinitializer, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP6]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = load ptr, ptr %[[TMP13]], align 8
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP6]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = load ptr, ptr %[[TMP15]], align 8
// LINUX-AMD64-NEXT:   call void %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP11]], ptr %[[TMP14]], ptr %[[TMP16]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.main$1$1"(
// DARWIN-ARM64-SAME: ptr {{(nest|swiftself)}} %[[TMP0:[0-9]+]], %"{{.*}}/runtime/internal/runtime.iface" %[[TMP1:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr {{(nest|swiftself)}} %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr %[[TMP2:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfaceType"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP1]])
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP1]], 1
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" undef, ptr %[[TMP3]], 0
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], ptr %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfaceType"(%"{{.*}}/runtime/internal/runtime.iface" zeroinitializer)
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" undef, ptr %[[TMP7]], 0
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP8]], ptr null, 1
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.EfaceEqual"(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP6]], %"{{.*}}/runtime/internal/runtime.eface" %[[TMP9]])
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = xor i1 %[[TMP10]], true
// DARWIN-ARM64-NEXT:   br i1 %[[TMP11]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store ptr %[[TMP2]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.iface", ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" %[[TMP6]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = load ptr, ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = load ptr, ptr %[[TMP16]], align 8
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfaceType"(ptr %[[TMP15]], ptr %[[TMP17]])
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP6]], 1
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" undef, ptr %[[TMP18]], 0
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP20]], ptr %[[TMP19]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" zeroinitializer, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP11]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = load ptr, ptr %[[TMP22]], align 8
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP11]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = load ptr, ptr %[[TMP24]], align 8
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfaceType"(ptr %[[TMP23]], ptr %[[TMP25]])
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" undef, ptr %[[TMP26]], 0
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP27]], ptr null, 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP21]], ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP9]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = load ptr, ptr %[[TMP29]], align 8
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP9]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = load ptr, ptr %[[TMP31]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP28]], ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP10]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP34:[0-9]+]] = load ptr, ptr %[[TMP33]], align 8
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP10]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = load ptr, ptr %[[TMP35]], align 8
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.EfaceEqual"(ptr %[[TMP30]], ptr %[[TMP32]], ptr %[[TMP34]], ptr %[[TMP36]])
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = xor i1 %[[TMP37]], true
// LINUX-AMD64-NEXT:   br i1 %[[TMP38]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = extractvalue { ptr } %[[TMP2]], 0
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP12]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP13]], 1
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP13]], 0
// DARWIN-ARM64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP15]])
// DARWIN-ARM64-NEXT:   call void %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP14]], %"{{.*}}/runtime/internal/runtime.iface" %[[TMP1]])
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = extractvalue { ptr } %[[TMP13]], 0
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP39]], align 8
// LINUX-AMD64-NEXT:   %[[TMP41:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP40]], 1
// LINUX-AMD64-NEXT:   %[[TMP42:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP40]], 0
// LINUX-AMD64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP42]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" %[[TMP6]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP43:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP44:[0-9]+]] = load ptr, ptr %[[TMP43]], align 8
// LINUX-AMD64-NEXT:   %[[TMP45:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP46:[0-9]+]] = load ptr, ptr %[[TMP45]], align 8
// LINUX-AMD64-NEXT:   call void %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP41]], ptr %[[TMP44]], ptr %[[TMP46]])
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = extractvalue { ptr } %[[TMP2]], 0
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP16]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP18:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP17]], 1
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP17]], 0
// DARWIN-ARM64-NEXT:   %__llgo_funcval_code1 = call ptr asm "", "=r,0"(ptr %[[TMP19]])
// DARWIN-ARM64-NEXT:   call void %__llgo_funcval_code1(ptr {{(nest|swiftself)}} %[[TMP18]], %"{{.*}}/runtime/internal/runtime.iface" zeroinitializer)
// LINUX-AMD64-NEXT:   %[[TMP47:[0-9]+]] = extractvalue { ptr } %[[TMP13]], 0
// LINUX-AMD64-NEXT:   %[[TMP48:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP47]], align 8
// LINUX-AMD64-NEXT:   %[[TMP49:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP48]], 1
// LINUX-AMD64-NEXT:   %[[TMP50:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP48]], 0
// LINUX-AMD64-NEXT:   %__llgo_funcval_code1 = call ptr asm "", "=r,0"(ptr %[[TMP50]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" zeroinitializer, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP51:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP7]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP52:[0-9]+]] = load ptr, ptr %[[TMP51]], align 8
// LINUX-AMD64-NEXT:   %[[TMP53:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP7]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP54:[0-9]+]] = load ptr, ptr %[[TMP53]], align 8
// LINUX-AMD64-NEXT:   call void %__llgo_funcval_code1(ptr {{(nest|swiftself)}} %[[TMP49]], ptr %[[TMP52]], ptr %[[TMP54]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.main$2"(
// DARWIN-ARM64-SAME: %"{{.*}}/runtime/internal/runtime.iface" %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, ptr }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.iface", ptr %[[TMP2]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
