// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\QNewRectangle\E|\Q(*Rectangle).Area\E|\Q(*Rectangle).GetID\E|\Q(*Rectangle).setID\E|\Q(*Rectangle).validate\E|\QRegisterShape\E) --check-globals=smart
package geometry1370

type Shape interface {
	Area() float64
	validate() bool
	setID(int)
}

type Rectangle struct {
	Width, Height float64
	id            int
}

// CHECK-LABEL: define ptr @"{{.*}}/cl/_testdata/geometry1370.NewRectangle"(
// CHECK-SAME: double %[[TMP0:[0-9]+]], double %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP2]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP2]], i32 0, i32 1
// CHECK-NEXT:   store double %[[TMP0]], ptr %[[TMP3]], align 8
// CHECK-NEXT:   store double %[[TMP1]], ptr %[[TMP4]], align 8
// CHECK-NEXT:   ret ptr %[[TMP2]]
// CHECK-NEXT: }

func NewRectangle(width, height float64) *Rectangle {
	return &Rectangle{Width: width, Height: height}
}

// CHECK-LABEL: define double @"{{.*}}/cl/_testdata/geometry1370.(*Rectangle).Area"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load double, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP0]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = load double, ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = fmul double %[[TMP2]], %[[TMP4]]
// CHECK-NEXT:   ret double %[[TMP5]]
// CHECK-NEXT: }

func (r *Rectangle) Area() float64 { return r.Width * r.Height }

// CHECK-LABEL: define i64 @"{{.*}}/cl/_testdata/geometry1370.(*Rectangle).GetID"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP0]], i32 0, i32 2
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load i64, ptr %[[TMP1]], align 8
// CHECK-NEXT:   ret i64 %[[TMP2]]
// CHECK-NEXT: }

func (r *Rectangle) GetID() int { return r.id }

// CHECK-LABEL: define void @"{{.*}}/cl/_testdata/geometry1370.(*Rectangle).setID"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP0]], i32 0, i32 2
// CHECK-NEXT:   store i64 %[[TMP1]], ptr %[[TMP2]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

func (r *Rectangle) setID(id int) { r.id = id }

// CHECK-LABEL: define i1 @"{{.*}}/cl/_testdata/geometry1370.(*Rectangle).validate"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load double, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = fcmp ogt double %[[TMP2]], 0.000000e+00
// CHECK-NEXT:   br i1 %[[TMP3]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/geometry1370.Rectangle", ptr %[[TMP0]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load double, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = fcmp ogt double %[[TMP5]], 0.000000e+00
// CHECK-NEXT:   br label %_llgo_[[BB2]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = phi i1 [ false, %_llgo_[[BB0]] ], [ %[[TMP6]], %_llgo_[[BB1]] ]
// CHECK-NEXT:   ret i1 %[[TMP7]]
// CHECK-NEXT: }

func (r *Rectangle) validate() bool { return r.Width > 0 && r.Height > 0 }

// CHECK-LABEL: define void @"{{.*}}/cl/_testdata/geometry1370.RegisterShape"(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.iface" %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP0]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr ptr, ptr %[[TMP3]], i64 4
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load ptr, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP5]], 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP6]], ptr %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP7]], 1
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP7]], 0
// CHECK-NEXT:   call void %[[TMP9]](ptr %[[TMP8]], i64 %[[TMP1]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

func RegisterShape(s Shape, id int) {
	s.setID(id)
}
