// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=run --check-globals=smart
// NOTE: Autogenerated snapshot targets: LINUX-AMD64
package main

// LINUX-AMD64: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [5 x i8] c"first", align 1{{$}}
// LINUX-AMD64: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [6 x i8] c"second", align 1{{$}}

func run() {
	defer println("first")
	defer println("second")
}

func main() {
	run()
}

// LINUX-AMD64-LABEL: define void @main.run(){{.*}} {
// LINUX-AMD64-NEXT: _llgo_[[BB0:[0-9]+]]:
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.GetThreadDefer"()
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca i8, i64 200, align 1
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP3]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 2
// LINUX-AMD64-NEXT:   store ptr %[[TMP2]], ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 3
// LINUX-AMD64-NEXT:   store ptr blockaddress(@main.run, %_llgo_[[BB2:[0-9]+]]), ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SetThreadDefer"(ptr %[[TMP4]])
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 3
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 4
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], i32 0, i32 5
// LINUX-AMD64-NEXT:   store ptr null, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = call i32 @__sigsetjmp(ptr %[[TMP3]], i32 0)
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = icmp eq i32 %[[TMP13]], 0
// LINUX-AMD64-NEXT:   br i1 %[[TMP14]], label %_llgo_[[BB4:[0-9]+]], label %_llgo_[[BB5:[0-9]+]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB1:[0-9]+]]:
// LINUX-AMD64-NEXT:   ret void
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB2]]:
// LINUX-AMD64-NEXT:   store ptr blockaddress(@main.run, %_llgo_[[BB7:[0-9]+]]), ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = load i64, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = icmp ne ptr %[[TMP16]], null
// LINUX-AMD64-NEXT:   br i1 %[[TMP17]], label %_llgo_[[BB8:[0-9]+]], label %_llgo_[[BB9:[0-9]+]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB3:[0-9]+]]:
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Rethrow"(ptr %[[TMP2]])
// LINUX-AMD64-NEXT:   br label %_llgo_[[BB1]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB4]]:
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 32)
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP19]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP18]], ptr %[[TMP20]], align 8
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = getelementptr inbounds { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP19]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP21]], align 8
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP19]], i32 0, i32 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP22]], align 8
// LINUX-AMD64-NEXT:   store ptr %[[TMP19]], ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 32)
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = getelementptr inbounds { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP24]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP23]], ptr %[[TMP25]], align 8
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = getelementptr inbounds { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP24]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store i64 1, ptr %[[TMP26]], align 8
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP24]], i32 0, i32 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB1]], i64 6 }, ptr %[[TMP27]], align 8
// LINUX-AMD64-NEXT:   store ptr %[[TMP24]], ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   store ptr blockaddress(@main.run, %_llgo_[[BB6:[0-9]+]]), ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   br label %_llgo_[[BB2]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB5]]:
// LINUX-AMD64-NEXT:   store ptr blockaddress(@main.run, %_llgo_[[BB3]]), ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = load ptr, ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   indirectbr ptr %[[TMP28]], [label %_llgo_[[BB3]], label %_llgo_[[BB7]], label %_llgo_[[BB2]]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB6]]:
// LINUX-AMD64-NEXT:   ret void
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB7]]:
// LINUX-AMD64-NEXT:   store ptr blockaddress(@main.run, %_llgo_[[BB3]]), ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = load i64, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = icmp ne ptr %[[TMP30]], null
// LINUX-AMD64-NEXT:   br i1 %[[TMP31]], label %_llgo_[[BB10:[0-9]+]], label %_llgo_[[BB11:[0-9]+]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB8]]:
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = load { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP32]], align 8
// LINUX-AMD64-NEXT:   %[[TMP34:[0-9]+]] = extractvalue { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP33]], 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP34]], ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = extractvalue { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP33]], 2
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.FreeDeferNode"(ptr %[[TMP32]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP35]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = load ptr, ptr %[[TMP36]], align 8
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = load i64, ptr %[[TMP38]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP37]], i64 %[[TMP39]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// LINUX-AMD64-NEXT:   br label %_llgo_[[BB9]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB9]]:
// LINUX-AMD64-NEXT:   br label %_llgo_[[BB7]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB10]]:
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP41:[0-9]+]] = load { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" }, ptr %[[TMP40]], align 8
// LINUX-AMD64-NEXT:   %[[TMP42:[0-9]+]] = extractvalue { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP41]], 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP42]], ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP43:[0-9]+]] = extractvalue { ptr, i64, %"{{.*}}/runtime/internal/runtime.String" } %[[TMP41]], 2
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.FreeDeferNode"(ptr %[[TMP40]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP43]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP44:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP45:[0-9]+]] = load ptr, ptr %[[TMP44]], align 8
// LINUX-AMD64-NEXT:   %[[TMP46:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP47:[0-9]+]] = load i64, ptr %[[TMP46]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP45]], i64 %[[TMP47]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// LINUX-AMD64-NEXT:   br label %_llgo_[[BB11]]
// LINUX-AMD64-EMPTY:
// LINUX-AMD64-NEXT: _llgo_[[BB11]]:
// LINUX-AMD64-NEXT:   %[[TMP48:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Defer", ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP49:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Defer" %[[TMP48]], 2
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SetThreadDefer"(ptr %[[TMP49]])
// LINUX-AMD64-NEXT:   %[[TMP50:[0-9]+]] = load ptr, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   indirectbr ptr %[[TMP50]], [label %_llgo_[[BB3]], label %_llgo_[[BB6]]]
// LINUX-AMD64-NEXT: }
