// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.main$1\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

// CHECK: {{^}}@[[GLOB5:[0-9]+]] = private unnamed_addr constant [5 x i8] c"error", align 1{{$}}

func main() {
	var m int = 200
	fn := func(n int) int {
		return m + n
	}
	var i any = fn
	f, ok := i.(func(int) int)
	if !ok {
		panic("error")
	}
	println(f(100))
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// DARWIN-ARM64-NEXT:   store i64 200, ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP1]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1", ptr undef }, ptr %[[TMP1]], 1
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// DARWIN-ARM64-NEXT:   store { ptr, ptr } %[[TMP3]], ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_closure$QIHBTaw1IFobr8yvWpq-2AJFm3xBNhdW_aNBicqUBGk", ptr undef }, ptr %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 0
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.MatchesClosure"(ptr @"_llgo_closure$QIHBTaw1IFobr8yvWpq-2AJFm3xBNhdW_aNBicqUBGk", ptr %[[TMP6]])
// DARWIN-ARM64-NEXT:   br i1 %[[TMP7]], label %_llgo_[[BB3:[0-9]+]], label %_llgo_[[BB4:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// LINUX-AMD64-NEXT:   store i64 200, ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = insertvalue { ptr, ptr } { ptr @"main.main$1", ptr undef }, ptr %[[TMP2]], 1
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// LINUX-AMD64-NEXT:   store { ptr, ptr } %[[TMP4]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_closure$QIHBTaw1IFobr8yvWpq-2AJFm3xBNhdW_aNBicqUBGk", ptr undef }, ptr %[[TMP5]], 1
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP6]], 0
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.MatchesClosure"(ptr @"_llgo_closure$QIHBTaw1IFobr8yvWpq-2AJFm3xBNhdW_aNBicqUBGk", ptr %[[TMP7]])
// LINUX-AMD64-NEXT:   br i1 %[[TMP8]], label %_llgo_[[BB3:[0-9]+]], label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB5]], i64 5 }, ptr %[[TMP8]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP8]], 1
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP9]])
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB5]], i64 5 }, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP9]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP10]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = load ptr, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = load ptr, ptr %[[TMP13]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(ptr %[[TMP12]], ptr %[[TMP14]])
// CHECK-NEXT:   unreachable
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP18:[0-9]+]], 1
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP18]], 0
// DARWIN-ARM64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP11]])
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = call i64 %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP10]], i64 100)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP12]])
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP23:[0-9]+]], 1
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP23]], 0
// LINUX-AMD64-NEXT:   %__llgo_funcval_code = call ptr asm "", "=r,0"(ptr %[[TMP16]])
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = call i64 %__llgo_funcval_code(ptr {{(nest|swiftself)}} %[[TMP15]], i64 100)
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP17]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 1
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP13]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } undef, { ptr, ptr } %[[TMP14]], 0
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } %[[TMP15]], i1 true, 1
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP6]], 1
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP18]], align 8
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } undef, { ptr, ptr } %[[TMP19]], 0
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } %[[TMP20]], i1 true, 1
// CHECK-NEXT:   br label %_llgo_[[BB5:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   br label %_llgo_[[BB5]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = phi { { ptr, ptr }, i1 } [ %[[TMP16]], %_llgo_[[BB3]] ], [ zeroinitializer, %_llgo_[[BB4]] ]
// DARWIN-ARM64-NEXT:   %[[TMP18]] = extractvalue { { ptr, ptr }, i1 } %[[TMP17]], 0
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = extractvalue { { ptr, ptr }, i1 } %[[TMP17]], 1
// DARWIN-ARM64-NEXT:   br i1 %[[TMP19]], label %_llgo_[[BB2]], label %_llgo_[[BB1]]
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = phi { { ptr, ptr }, i1 } [ %[[TMP21]], %_llgo_[[BB3]] ], [ zeroinitializer, %_llgo_[[BB4]] ]
// LINUX-AMD64-NEXT:   %[[TMP23]] = extractvalue { { ptr, ptr }, i1 } %[[TMP22]], 0
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = extractvalue { { ptr, ptr }, i1 } %[[TMP22]], 1
// LINUX-AMD64-NEXT:   br i1 %[[TMP24]], label %_llgo_[[BB2]], label %_llgo_[[BB1]]
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @"main.main$1"(
// CHECK-SAME: ptr {{(nest|swiftself)}} %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load { ptr }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = extractvalue { ptr } %[[TMP2]], 0
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = load i64, ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = add i64 %[[TMP4]], %[[TMP1]]
// CHECK-NEXT:   ret i64 %[[TMP5]]
// CHECK-NEXT: }
