// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.mask\E|\Qmain.mask_shl\E|\Qmain.mask_shl8\E|\Qmain.mask_shl8u\E|\Qmain.mask_shr\E|\Qmain.mask_shr8\E|\Qmain.mask_shr8u\E) --check-globals=smart
package main

func main() {
	println(mask(1))
	println(mask_shl(127, 5))
	println(mask_shl8(127, 5))
	println(mask_shl8u(127, 5))
	println(mask_shl8(127, 16))
	println(mask_shl8u(127, 16))
	println(mask_shr(127, 5))
	println(mask_shr8(127, 5))
	println(mask_shr8u(127, 5))
	println(mask_shr8(127, 16))
}

// The sign bit must survive the two constant shifts, including the explicit
// overshift select inserted by the lowering.
func mask(x int8) int32 {
	return int32(x) << 31 >> 31
}

func mask_shl(x int, y int) int {
	return x << y
}

func mask_shl8(x int8, y int) int8 {
	return x << y
}

func mask_shl8u(x uint8, y int) uint8 {
	return x << y
}

// Signed right shifts clamp an oversized count to width-1, preserving sign.
func mask_shr(x int, y int) int {
	return x >> y
}

func mask_shr8(x int8, y int) int8 {
	return x >> y
}

// Unsigned right shifts instead select zero for an oversized count.
func mask_shr8u(x uint8, y int) uint8 {
	return x >> y
}

// CHECK-LABEL: define i32 @main.mask(
// CHECK-SAME: i8 %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = sext i8 %[[TMP0]] to i32
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = shl i32 %[[TMP1]], 31
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = select i1 false, i32 0, i32 %[[TMP2]]
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = ashr i32 %[[TMP3]], 31
// CHECK-NEXT:   ret i32 %[[TMP4]]
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @main.mask_shl(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.AssertNegativeShift"(i1 %[[TMP2]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = icmp uge i64 %[[TMP1]], 64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = shl i64 %[[TMP0]], %[[TMP1]]
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = select i1 %[[TMP3]], i64 0, i64 %[[TMP4]]
// CHECK-NEXT:   ret i64 %[[TMP5]]
// CHECK-NEXT: }

// CHECK-LABEL: define i8 @main.mask_shl8(
// CHECK-SAME: i8 %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.AssertNegativeShift"(i1 %[[TMP2]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = trunc i64 %[[TMP1]] to i8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp uge i8 %[[TMP3]], 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = shl i8 %[[TMP0]], %[[TMP3]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = select i1 %[[TMP4]], i8 0, i8 %[[TMP5]]
// CHECK-NEXT:   ret i8 %[[TMP6]]
// CHECK-NEXT: }

// CHECK-LABEL: define i8 @main.mask_shl8u(
// CHECK-SAME: i8 %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.AssertNegativeShift"(i1 %[[TMP2]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = trunc i64 %[[TMP1]] to i8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp uge i8 %[[TMP3]], 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = shl i8 %[[TMP0]], %[[TMP3]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = select i1 %[[TMP4]], i8 0, i8 %[[TMP5]]
// CHECK-NEXT:   ret i8 %[[TMP6]]
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @main.mask_shr(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.AssertNegativeShift"(i1 %[[TMP2]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = icmp uge i64 %[[TMP1]], 64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = select i1 %[[TMP3]], i64 63, i64 %[[TMP1]]
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = ashr i64 %[[TMP0]], %[[TMP4]]
// CHECK-NEXT:   ret i64 %[[TMP5]]
// CHECK-NEXT: }

// CHECK-LABEL: define i8 @main.mask_shr8(
// CHECK-SAME: i8 %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.AssertNegativeShift"(i1 %[[TMP2]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = trunc i64 %[[TMP1]] to i8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp uge i8 %[[TMP3]], 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = select i1 %[[TMP4]], i8 7, i8 %[[TMP3]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = ashr i8 %[[TMP0]], %[[TMP5]]
// CHECK-NEXT:   ret i8 %[[TMP6]]
// CHECK-NEXT: }

// CHECK-LABEL: define i8 @main.mask_shr8u(
// CHECK-SAME: i8 %[[TMP0:[0-9]+]], i64 %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.AssertNegativeShift"(i1 %[[TMP2]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = trunc i64 %[[TMP1]] to i8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = icmp uge i8 %[[TMP3]], 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = lshr i8 %[[TMP0]], %[[TMP3]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = select i1 %[[TMP4]], i8 0, i8 %[[TMP5]]
// CHECK-NEXT:   ret i8 %[[TMP6]]
// CHECK-NEXT: }
