// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E) --check-globals=smart
package main

import (
	"github.com/goplus/lib/py"
	"github.com/goplus/lib/py/std"
)

// Direct variadic Max passes the four converted objects to the loaded builtin,
// and Print consumes the returned object.
func main() {
	x := std.Max(py.Float(3.0), py.Float(9.0), py.Float(23.0), py.Float(100.0))
	std.Print(x)

	list := py.List(3.0, 9.0, 23.0, 100.0)
	y := std.Max(std.Iter(list))
	std.Print(y)

	tuple := py.Tuple(1.0, 2.0, 3.0)
	z := std.Max(std.Iter(tuple))
	std.Print(z)
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @PyFloat_FromDouble(double 3.000000e+00)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @PyFloat_FromDouble(double 9.000000e+00)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @PyFloat_FromDouble(double 2.300000e+01)
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call ptr @PyFloat_FromDouble(double 1.000000e+02)
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.max, align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP4]], ptr %[[TMP0]], ptr %[[TMP1]], ptr %[[TMP2]], ptr %[[TMP3]], ptr null)
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.print, align 8
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP6]], ptr %[[TMP5]], ptr null)
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call ptr @PyList_New(i64 4)
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call ptr @PyFloat_FromDouble(double 3.000000e+00)
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP8]], i64 0, ptr %[[TMP9]])
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = call ptr @PyFloat_FromDouble(double 9.000000e+00)
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP8]], i64 1, ptr %[[TMP11]])
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = call ptr @PyFloat_FromDouble(double 2.300000e+01)
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP8]], i64 2, ptr %[[TMP13]])
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = call ptr @PyFloat_FromDouble(double 1.000000e+02)
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP8]], i64 3, ptr %[[TMP15]])
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.iter, align 8
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = call ptr @PyObject_CallOneArg(ptr %[[TMP17]], ptr %[[TMP8]])
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.max, align 8
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP19]], ptr %[[TMP18]], ptr null)
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.print, align 8
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP21]], ptr %[[TMP20]], ptr null)
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = call ptr @PyTuple_New(i64 3)
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = call ptr @PyFloat_FromDouble(double 1.000000e+00)
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = call i32 @PyTuple_SetItem(ptr %[[TMP23]], i64 0, ptr %[[TMP24]])
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = call ptr @PyFloat_FromDouble(double 2.000000e+00)
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = call i32 @PyTuple_SetItem(ptr %[[TMP23]], i64 1, ptr %[[TMP26]])
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = call ptr @PyFloat_FromDouble(double 3.000000e+00)
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = call i32 @PyTuple_SetItem(ptr %[[TMP23]], i64 2, ptr %[[TMP28]])
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.iter, align 8
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = call ptr @PyObject_CallOneArg(ptr %[[TMP30]], ptr %[[TMP23]])
// CHECK-NEXT:   %[[TMP32:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.max, align 8
// CHECK-NEXT:   %[[TMP33:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP32]], ptr %[[TMP31]], ptr null)
// CHECK-NEXT:   %[[TMP34:[0-9]+]] = load ptr, ptr @__llgo_py.builtins.print, align 8
// CHECK-NEXT:   %[[TMP35:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP34]], ptr %[[TMP33]], ptr null)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
