package sizereport

import (
	"bytes"
	"fmt"
	"math"
	"unicode/utf8"
)

// These are measurements of the final encoding, not LLVM instructions or a
// prediction of native code generated by a WebAssembly engine.
type wasmSizeDetails struct {
	Sections       []wasmSizeSection `json:"sections"`
	Memories       []wasmSizeMemory  `json:"memories"`
	StructureBytes uint64            `json:"structure_bytes"`
	CustomBytes    uint64            `json:"custom_bytes"`
}

type wasmSizeSection struct {
	ID           byte   `json:"id"`
	Name         string `json:"name"`
	Offset       uint64 `json:"offset"`
	Size         uint64 `json:"size"`
	PayloadBytes uint64 `json:"payload_bytes"`
}

// Linear-memory limits include reservations and are not static BSS or peak
// RAM usage. Imported shared memory must be reported too.
type wasmSizeMemory struct {
	Imported     bool    `json:"imported"`
	Shared       bool    `json:"shared"`
	Memory64     bool    `json:"memory64"`
	InitialBytes uint64  `json:"initial_bytes"`
	MaximumBytes *uint64 `json:"maximum_bytes,omitempty"`
}

type wasmSizeReader struct {
	data []byte
	off  int
	err  error
}

func (r *wasmSizeReader) take(n uint64) []byte {
	if r.err != nil {
		return nil
	}
	if n > uint64(len(r.data)-r.off) {
		r.err = fmt.Errorf("truncated WebAssembly encoding at byte %d", r.off)
		return nil
	}
	p := r.data[r.off : r.off+int(n)]
	r.off += int(n)
	return p
}

func (r *wasmSizeReader) byte() byte {
	p := r.take(1)
	if len(p) == 0 {
		return 0
	}
	return p[0]
}

func (r *wasmSizeReader) uint(bits uint) uint64 {
	var v uint64
	for shift := uint(0); shift < bits && r.err == nil; shift += 7 {
		b := r.byte()
		if bits-shift < 7 && uint64(b) >= uint64(1)<<(bits-shift) {
			r.err = fmt.Errorf("WebAssembly varuint%d overflow", bits)
			return 0
		}
		v |= uint64(b&127) << shift
		if b&128 == 0 {
			return v
		}
	}
	return 0
}

func (r *wasmSizeReader) signed(bits uint) {
	for shift := uint(0); shift < bits && r.err == nil; shift += 7 {
		b := r.byte()
		if bits-shift < 7 {
			unused := byte((0x7f << (bits - shift - 1)) & 0x7f)
			if b&128 != 0 || (b&unused != 0 && b&unused != unused) {
				r.err = fmt.Errorf("WebAssembly varint%d overflow", bits)
			}
		}
		if b&128 == 0 {
			return
		}
	}
}

func (r *wasmSizeReader) name() string {
	p := r.take(r.uint(32))
	if !utf8.Valid(p) && r.err == nil {
		r.err = fmt.Errorf("invalid UTF-8 WebAssembly name")
	}
	return string(p)
}

func (r *wasmSizeReader) done() error {
	if r.err != nil {
		return r.err
	}
	if r.off != len(r.data) {
		return fmt.Errorf("unexpected trailing WebAssembly bytes at %d", r.off)
	}
	return nil
}

func (r *wasmSizeReader) valueType() {
	switch b := r.byte(); b {
	case 0x63, 0x64: // ref null / ref, followed by a signed heap type.
		r.signed(33)
	default:
		if b < 0x65 || b > 0x7f {
			r.err = fmt.Errorf("unsupported WebAssembly value type %#x", b)
		}
	}
}

func (r *wasmSizeReader) limits(imported, memory bool) wasmSizeMemory {
	flags := r.uint(32)
	m := wasmSizeMemory{Imported: imported, Shared: flags&2 != 0, Memory64: flags&4 != 0}
	if flags & ^uint64(7) != 0 {
		r.err = fmt.Errorf("unsupported WebAssembly limits flags %#x", flags)
		return m
	}
	bits := uint(32)
	if m.Memory64 {
		bits = 64
	}
	minimum := r.uint(bits)
	maximum := uint64(0)
	if flags&1 != 0 {
		maximum = r.uint(bits)
		m.MaximumBytes = new(uint64)
	}
	if !memory {
		return m // Table limits count elements, not memory pages.
	}
	if minimum > math.MaxUint64/65536 || maximum > math.MaxUint64/65536 {
		r.err = fmt.Errorf("WebAssembly memory byte size overflow")
		return m
	}
	m.InitialBytes = minimum * 65536
	if m.MaximumBytes != nil {
		*m.MaximumBytes = maximum * 65536
	}
	return m
}

func (r *wasmSizeReader) offsetExpression() {
	for r.err == nil {
		switch b := r.byte(); b {
		case 0x0b:
			return
		case 0x41:
			r.signed(32)
		case 0x42:
			r.signed(64)
		case 0x23: // global.get
			r.uint(32)
		case 0x6a, 0x6b, 0x6c, 0x7c, 0x7d, 0x7e: // extended-const integer arithmetic
		default:
			r.err = fmt.Errorf("unsupported WebAssembly data offset opcode %#x", b)
		}
	}
}

func wasmFunctionNames(payload []byte) (map[uint64]string, error) {
	names := make(map[uint64]string)
	r := wasmSizeReader{data: payload}
	for r.off < len(r.data) && r.err == nil {
		id := r.byte()
		sub := wasmSizeReader{data: r.take(r.uint(32))}
		if id != 1 {
			continue
		}
		count := sub.uint(32)
		for i := uint64(0); i < count && sub.err == nil; i++ {
			index := sub.uint(32)
			name := sub.name()
			if _, exists := names[index]; exists {
				return nil, fmt.Errorf("duplicate WebAssembly function name index %d", index)
			}
			names[index] = name
		}
		if err := sub.done(); err != nil {
			return nil, err
		}
	}
	return names, r.done()
}

func collectWasmSize(path string, raw []byte, pkgs []Package, level string) (*Report, error) {
	if len(raw) < 8 || !bytes.Equal(raw[:8], []byte{0, 'a', 's', 'm', 1, 0, 0, 0}) {
		return nil, fmt.Errorf("invalid WebAssembly header")
	}
	report := &Report{Binary: path, Modules: make(map[string]*Module), Wasm: &wasmSizeDetails{}}
	w := report.Wasm
	r := wasmSizeReader{data: raw, off: 8}
	sections := make(map[byte][]byte)
	names := make(map[uint64]string)
	sectionNames := []string{"custom", "type", "import", "function", "table", "memory", "global", "export", "start", "element", "code", "data", "data_count", "tag"}
	for r.off < len(raw) && r.err == nil {
		start := r.off
		id := r.byte()
		size := r.uint(32)
		payload := r.take(size)
		if r.err != nil {
			break
		}
		name := fmt.Sprintf("section_%d", id)
		if int(id) < len(sectionNames) {
			name = sectionNames[id]
		}
		if id == 0 {
			sub := wasmSizeReader{data: payload}
			name = sub.name()
			if sub.err != nil {
				return nil, sub.err
			}
			if name == "name" {
				parsed, err := wasmFunctionNames(payload[sub.off:])
				if err != nil {
					report.Warnings = append(report.Warnings, "ignored invalid function names: "+err.Error())
				} else {
					for index, n := range parsed {
						names[index] = n
					}
				}
			}
			w.CustomBytes += uint64(r.off - start)
		} else {
			if _, exists := sections[id]; exists {
				return nil, fmt.Errorf("duplicate WebAssembly section %d", id)
			}
			sections[id] = payload
		}
		w.Sections = append(w.Sections, wasmSizeSection{ID: id, Name: name, Offset: uint64(start), Size: uint64(r.off - start), PayloadBytes: size})
	}
	if err := r.done(); err != nil {
		return nil, err
	}

	var importedFunctions uint64
	if payload, ok := sections[2]; ok {
		sub := wasmSizeReader{data: payload}
		count := sub.uint(32)
		for i := uint64(0); i < count && sub.err == nil; i++ {
			sub.name()
			sub.name()
			switch kind := sub.byte(); kind {
			case 0:
				sub.uint(32)
				importedFunctions++
			case 1:
				sub.valueType()
				sub.limits(true, false)
			case 2:
				w.Memories = append(w.Memories, sub.limits(true, true))
			case 3:
				sub.valueType()
				sub.byte()
			case 4:
				sub.byte()
				sub.uint(32)
			default:
				sub.err = fmt.Errorf("unsupported WebAssembly import kind %d", kind)
			}
		}
		if err := sub.done(); err != nil {
			return nil, err
		}
	}
	if payload, ok := sections[5]; ok {
		sub := wasmSizeReader{data: payload}
		count := sub.uint(32)
		for i := uint64(0); i < count && sub.err == nil; i++ {
			w.Memories = append(w.Memories, sub.limits(false, true))
		}
		if err := sub.done(); err != nil {
			return nil, err
		}
	}
	if payload, ok := sections[10]; ok {
		sub := wasmSizeReader{data: payload}
		count := sub.uint(32)
		res := newNameResolver(level, pkgs)
		for i := uint64(0); i < count && sub.err == nil; i++ {
			size := sub.uint(32)
			sub.take(size)
			name := "(unknown code)"
			if n := names[importedFunctions+i]; n != "" {
				name = res.resolve(n)
			} else if level == "full" {
				name = fmt.Sprintf("(unknown function %d)", importedFunctions+i)
			}
			report.add(name, sectionText, size)
		}
		if err := sub.done(); err != nil {
			return nil, err
		}
	}
	if payload, ok := sections[11]; ok {
		sub := wasmSizeReader{data: payload}
		count := sub.uint(32)
		for i := uint64(0); i < count && sub.err == nil; i++ {
			switch mode := sub.uint(32); mode {
			case 0:
				sub.offsetExpression()
			case 1: // passive
			case 2:
				sub.uint(32)
				sub.offsetExpression()
			default:
				sub.err = fmt.Errorf("unsupported WebAssembly data segment mode %d", mode)
			}
			size := sub.uint(32)
			sub.take(size)
			report.add("(unknown data)", sectionData, size)
		}
		if err := sub.done(); err != nil {
			return nil, err
		}
	}
	// Every other byte (header, section/vector/body lengths, imports, types,
	// globals, etc.) remains visible instead of disappearing into Flash totals.
	w.StructureBytes = uint64(len(raw)) - w.CustomBytes - report.Total.Code - report.Total.Data
	return report, nil
}
