// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.Basic\E|\Qmain.basicType\E|\Qmain.init\E|\Qmain.main\E) --check-globals=smart
package main

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/llgo/runtime/abi"
)

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [20 x i8] c"Kind: %d, Size: %d\0A\00", align 1{{$}}

func Basic(kind abi.Kind) *abi.Type {
	return basicTypes[kind]
}

func basicType(kind abi.Kind) *abi.Type {
	return &abi.Type{
		Size_: sizeBasicTypes[kind],
		Hash:  uint32(kind),
		Kind_: uint8(kind),
	}
}

var (
	basicTypes = [...]*abi.Type{
		abi.String: basicType(abi.String),
	}
	sizeBasicTypes = [...]uintptr{
		abi.String: 16,
	}
)

func main() {
	t := Basic(abi.String)
	c.Printf(c.Str("Kind: %d, Size: %d\n"), int(t.Kind_), t.Size_)
}

// CHECK-LABEL: define ptr @main.Basic(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp uge i64 %[[TMP0]], 25
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP1]], i64 %[[TMP0]], i1 false, i64 25)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds ptr, ptr @main.basicTypes, i64 %[[TMP0]]
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load ptr, ptr %[[TMP2]], align 8
// CHECK-NEXT:   ret ptr %[[TMP3]]
// CHECK-NEXT: }

// CHECK-LABEL: define ptr @main.basicType(
// CHECK-SAME: i64 %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 72)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/abi.Type", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = icmp uge i64 %[[TMP0]], 25
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP3]], i64 %[[TMP0]], i1 false, i64 25)
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds i64, ptr @main.sizeBasicTypes, i64 %[[TMP0]]
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load i64, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/abi.Type", ptr %[[TMP1]], i32 0, i32 2
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = trunc i64 %[[TMP0]] to i32
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/abi.Type", ptr %[[TMP1]], i32 0, i32 6
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = trunc i64 %[[TMP0]] to i8
// CHECK-NEXT:   store i64 %[[TMP5]], ptr %[[TMP2]], align 8
// CHECK-NEXT:   store i32 %[[TMP7]], ptr %[[TMP6]], align 4
// CHECK-NEXT:   store i8 %[[TMP9]], ptr %[[TMP8]], align 1
// CHECK-NEXT:   ret ptr %[[TMP1]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.init(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = load i1, ptr @"main.init$guard", align 1
// CHECK-NEXT:   br i1 %[[TMP0]], label %_llgo_[[BB2:[0-9]+]], label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   store i1 true, ptr @"main.init$guard", align 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/abi.init"()
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @main.basicType(i64 24)
// CHECK-NEXT:   store ptr %[[TMP1]], ptr getelementptr inbounds (ptr, ptr @main.basicTypes, i64 24), align 8
// CHECK-NEXT:   br label %_llgo_[[BB2]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @main.Basic(i64 24)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/abi.Type", ptr %[[TMP0]], i32 0, i32 6
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load i8, ptr %[[TMP1]], align 1
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = zext i8 %[[TMP2]] to i64
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/abi.Type", ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load i64, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB0]], i64 %[[TMP3]], i64 %[[TMP5]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
