// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.sum\E) --check-globals=smart
package main

import (
	"github.com/goplus/lib/c"
)

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [10 x i8] c"Hello %d\0A\00", align 1{{$}}

func main() {
	c.Printf(c.Str("Hello %d\n"), sum(1, 2, 3, 4))
}

func sum(args ...int) (ret int) {
	for _, v := range args {
		ret += v
	}
	return
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP0]], i64 0
// CHECK-NEXT:   store i64 1, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP0]], i64 1
// CHECK-NEXT:   store i64 2, ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP0]], i64 2
// CHECK-NEXT:   store i64 3, ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP0]], i64 3
// CHECK-NEXT:   store i64 4, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP5]], i64 4, 1
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP6]], i64 4, 2
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call i64 @main.sum(%"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]])
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB0]], i64 %[[TMP8]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @main.sum(
// CHECK-SAME: %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 1
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = phi i64 [ 0, %_llgo_[[BB0]] ], [ %[[TMP13:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = phi i64 [ -1, %_llgo_[[BB0]] ], [ %[[TMP4:[0-9]+]], %_llgo_[[BB2]] ]
// CHECK-NEXT:   %[[TMP4]] = add i64 %[[TMP3]], 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = icmp slt i64 %[[TMP4]], %[[TMP1]]
// CHECK-NEXT:   br i1 %[[TMP5]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = icmp slt i64 %[[TMP4]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = icmp uge i64 %[[TMP4]], %[[TMP7]]
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = or i1 %[[TMP9]], %[[TMP8]]
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP10]], i64 %[[TMP4]], i1 true, i64 %[[TMP7]])
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP6]], i64 %[[TMP4]]
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = load i64, ptr %[[TMP11]], align 8
// CHECK-NEXT:   %[[TMP13]] = add i64 %[[TMP2]], %[[TMP12]]
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   ret i64 %[[TMP2]]
// CHECK-NEXT: }
