// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E) --check-globals=smart
package main

// Constant arithmetic remains folded, while division is delegated to the
// runtime and its two components are reassembled for printing.
type T complex64

func main() {
	a := 1 + 2i
	b := 3 + 4i
	c := 0 + 0i
	println(real(a), imag(a))
	println(-a)
	println(a + b)
	println(a - b)
	println(a * b)
	println(a / b)
	println(a / c)
	println(c / c)
	println(a == a, a != a)
	println(a == b, a != b)
	println(complex128(T(a)) == a)
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintFloat"(double 1.000000e+00)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintFloat"(double 2.000000e+00)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } { double -1.000000e+00, double -2.000000e+00 })
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } { double 4.000000e+00, double 6.000000e+00 })
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } { double -2.000000e+00, double -2.000000e+00 })
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } { double -5.000000e+00, double 1.000000e+01 })
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call { double, double } @"{{.*}}/runtime/internal/runtime.Complex128Div"({ double, double } { double 1.000000e+00, double 2.000000e+00 }, { double, double } { double 3.000000e+00, double 4.000000e+00 })
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = extractvalue { double, double } %[[TMP0]], 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = extractvalue { double, double } %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = insertvalue { double, double } undef, double %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = insertvalue { double, double } %[[TMP3]], double %[[TMP2]], 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } %[[TMP4]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call { double, double } @"{{.*}}/runtime/internal/runtime.Complex128Div"({ double, double } { double 1.000000e+00, double 2.000000e+00 }, { double, double } zeroinitializer)
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue { double, double } %[[TMP5]], 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = extractvalue { double, double } %[[TMP5]], 1
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = insertvalue { double, double } undef, double %[[TMP6]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = insertvalue { double, double } %[[TMP8]], double %[[TMP7]], 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } %[[TMP9]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = call { double, double } @"{{.*}}/runtime/internal/runtime.Complex128Div"({ double, double } zeroinitializer, { double, double } zeroinitializer)
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = extractvalue { double, double } %[[TMP10]], 0
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = extractvalue { double, double } %[[TMP10]], 1
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = insertvalue { double, double } undef, double %[[TMP11]], 0
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = insertvalue { double, double } %[[TMP13]], double %[[TMP12]], 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintComplex"({ double, double } %[[TMP14]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 true)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 false)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 false)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 true)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 true)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
