// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.index\E|\Qmain.main\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

import (
	"unicode/utf8"
)

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [7 x i8] c"\E4\B8\ADabcd", align 1{{$}}

func index(n int8) uint8 {
	return array[n]
}

var array = [...]uint8{
	1, 2, 3, 4, 5, 6, 7, 8,
}

func main() {
	var str = "中abcd"
	for i := 0; i < len(str); {
		r, n := utf8.DecodeRuneInString(str[i:])
		i += n
		println(r)
	}
	println(index(2) == 3)
}

// CHECK-LABEL: define i8 @main.index(
// CHECK-SAME: i8 %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = sext i8 %[[TMP0]] to i64
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = icmp uge i64 %[[TMP1]], 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = or i1 %[[TMP3]], %[[TMP2]]
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP4]], i64 %[[TMP1]], i1 true, i64 8)
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds i8, ptr @main.array, i64 %[[TMP1]]
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = load i8, ptr %[[TMP5]], align 1
// CHECK-NEXT:   ret i8 %[[TMP6]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = alloca [2 x i64], align 8
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca { i32, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca { ptr, i64 }, align 8
// CHECK-NEXT:   br label %_llgo_[[BB1:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = phi i64 [ 0, %_llgo_[[BB0]] ], [ %[[TMP8:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = icmp slt i64 %[[TMP1]], 7
// DARWIN-ARM64-NEXT:   br i1 %[[TMP2]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = phi i64 [ 0, %_llgo_[[BB0]] ], [ %[[TMP20:[0-9]+]], %_llgo_[[BB2:[0-9]+]] ]
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = icmp slt i64 %[[TMP4]], 7
// LINUX-AMD64-NEXT:   br i1 %[[TMP5]], label %_llgo_[[BB2]], label %_llgo_[[BB3:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.String" @"{{.*}}/runtime/internal/runtime.StringSlice2"(%"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 7 }, i64 %[[TMP1]], i64 7, i1 true, i1 true)
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = call [2 x i64] @"unicode/utf8.DecodeRuneInString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP3]])
// DARWIN-ARM64-NEXT:   store [2 x i64] %[[TMP4]], ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = load { i32, i64 }, ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = extractvalue { i32, i64 } %[[TMP5]], 0
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = extractvalue { i32, i64 } %[[TMP5]], 1
// DARWIN-ARM64-NEXT:   %[[TMP8]] = add i64 %[[TMP1]], %[[TMP7]]
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = sext i32 %[[TMP6]] to i64
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP9]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 7 }, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = load ptr, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = load i64, ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = call { ptr, i64 } @"{{.*}}/runtime/internal/runtime.StringSlice2"(ptr %[[TMP7]], i64 %[[TMP9]], i64 %[[TMP4]], i64 7, i1 true, i1 true)
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP10]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP11]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load ptr, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = load i64, ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = call { i32, i64 } @"unicode/utf8.DecodeRuneInString"(ptr %[[TMP13]], i64 %[[TMP15]])
// LINUX-AMD64-NEXT:   store { i32, i64 } %[[TMP16]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = load { i32, i64 }, ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = extractvalue { i32, i64 } %[[TMP17]], 0
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = extractvalue { i32, i64 } %[[TMP17]], 1
// LINUX-AMD64-NEXT:   %[[TMP20]] = add i64 %[[TMP4]], %[[TMP19]]
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = sext i32 %[[TMP18]] to i64
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP21]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   br label %_llgo_[[BB1]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = call i8 @main.index(i8 2)
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = icmp eq i8 %[[TMP10]], 3
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP11]])
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = call i8 @main.index(i8 2)
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = icmp eq i8 %[[TMP22]], 3
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP23]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
