// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain\E|\Q(*Slice[[]int,int]).Append\E|\Q(*Slice[[]string,string]).Append\E|\Q(*Slice[[]int,int]).Append2\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [5 x i8] c"hello", align 1{{$}}

type Data[T any] struct {
	v T
}

func (p *Data[T]) Set(v T) {
	p.v = v
}

func (p *(Data[T1])) Set2(v T1) {
	p.v = v
}

type sliceOf[E any] interface {
	~[]E
}

type Slice[S sliceOf[T], T any] struct {
	Data S
}

func (p *Slice[S, T]) Append(t ...T) S {
	p.Data = append(p.Data, t...)
	return p.Data
}

func (p *Slice[S1, T1]) Append2(t ...T1) S1 {
	p.Data = append(p.Data, t...)
	return p.Data
}

type (
	DataInt     = Data[int]
	SliceInt    = Slice[[]int, int]
	DataString  = Data[string]
	SliceString = Slice[[]string, string]
)

// Type aliases and direct instantiations retain their concrete field types.
// SliceInt.Append receives a one-element []int containing 100.
// SliceString.Append receives one string element with the 16-byte stride.
// The direct v3 instantiation is updated twice through Append and Append2.

func main() {
	println(DataInt{1}.v)
	println(DataString{"hello"}.v)
	println(Data[int]{100}.v)
	println(Data[string]{"hello"}.v)

	// TODO
	println(Data[struct {
		X int
		Y int
	}]{}.v.X)

	v1 := SliceInt{}
	v1.Append(100)
	v2 := SliceString{}
	v2.Append("hello")
	v3 := Slice[[]int, int]{}
	v3.Append([]int{1, 2, 3, 4}...)
	v3.Append2([]int{1, 2, 3, 4}...)

	println(v1.Data, v1.Data[0])
	println(v2.Data, v2.Data[0])
	println(v3.Data, v3.Data[0])
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = alloca %"main.Data[int]", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP11]], i8 0, i64 8, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"main.Data[int]", ptr %[[TMP11]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store i64 1, ptr %[[TMP12]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = load %"main.Data[int]", ptr %[[TMP11]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = extractvalue %"main.Data[int]" %[[TMP13]], 0
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP14]])
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = alloca %"main.Data[int]", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP14]], i8 0, i64 8, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds %"main.Data[int]", ptr %[[TMP14]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store i64 1, ptr %[[TMP15]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = load %"main.Data[int]", ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = extractvalue %"main.Data[int]" %[[TMP16]], 0
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP17]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = alloca %"main.Data[string]", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP15]], i8 0, i64 16, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds %"main.Data[string]", ptr %[[TMP15]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP16]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = load %"main.Data[string]", ptr %[[TMP15]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP18:[0-9]+]] = extractvalue %"main.Data[string]" %[[TMP17]], 0
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP18]])
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = alloca %"main.Data[string]", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP18]], i8 0, i64 16, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds %"main.Data[string]", ptr %[[TMP18]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP19]], align 8
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = load %"main.Data[string]", ptr %[[TMP18]], align 8
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = extractvalue %"main.Data[string]" %[[TMP20]], 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP21]], ptr %[[TMP13]], align 8
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP13]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = load ptr, ptr %[[TMP22]], align 8
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP13]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = load i64, ptr %[[TMP24]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP23]], i64 %[[TMP25]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = alloca %"main.Data[int]", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP19]], i8 0, i64 8, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds %"main.Data[int]", ptr %[[TMP19]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store i64 100, ptr %[[TMP20]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP21:[0-9]+]] = load %"main.Data[int]", ptr %[[TMP19]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP22:[0-9]+]] = extractvalue %"main.Data[int]" %[[TMP21]], 0
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP22]])
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = alloca %"main.Data[int]", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP26]], i8 0, i64 8, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds %"main.Data[int]", ptr %[[TMP26]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store i64 100, ptr %[[TMP27]], align 8
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = load %"main.Data[int]", ptr %[[TMP26]], align 8
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = extractvalue %"main.Data[int]" %[[TMP28]], 0
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP29]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP23:[0-9]+]] = alloca %"main.Data[string]", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP23]], i8 0, i64 16, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP24:[0-9]+]] = getelementptr inbounds %"main.Data[string]", ptr %[[TMP23]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP24]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP25:[0-9]+]] = load %"main.Data[string]", ptr %[[TMP23]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP26:[0-9]+]] = extractvalue %"main.Data[string]" %[[TMP25]], 0
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP26]])
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = alloca %"main.Data[string]", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP30]], i8 0, i64 16, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = getelementptr inbounds %"main.Data[string]", ptr %[[TMP30]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP31]], align 8
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = load %"main.Data[string]", ptr %[[TMP30]], align 8
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = extractvalue %"main.Data[string]" %[[TMP32]], 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP33]], ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   %[[TMP34:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP12]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = load ptr, ptr %[[TMP34]], align 8
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP12]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = load i64, ptr %[[TMP36]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP35]], i64 %[[TMP37]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 0)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP27:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// DARWIN-ARM64-NEXT:   %[[TMP28:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// DARWIN-ARM64-NEXT:   %[[TMP29:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP28]], i64 0
// DARWIN-ARM64-NEXT:   store i64 100, ptr %[[TMP29]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP30:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP28]], 0
// DARWIN-ARM64-NEXT:   %[[TMP31:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP30]], i64 1, 1
// DARWIN-ARM64-NEXT:   %[[TMP32:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP31]], i64 1, 2
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP32]], ptr %[[TMP9]], align 8
// DARWIN-ARM64-NEXT:   call void @"main.(*Slice{{\[\[}}]int,int]).Append"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP10]], ptr %[[TMP27]], ptr %[[TMP9]])
// DARWIN-ARM64-NEXT:   %[[TMP33:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP10]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP34:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// DARWIN-ARM64-NEXT:   %[[TMP35:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// DARWIN-ARM64-NEXT:   %[[TMP36:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP35]], i64 0
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP36]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP37:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP35]], 0
// DARWIN-ARM64-NEXT:   %[[TMP38:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP37]], i64 1, 1
// DARWIN-ARM64-NEXT:   %[[TMP39:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP38]], i64 1, 2
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP39]], ptr %[[TMP7]], align 8
// DARWIN-ARM64-NEXT:   call void @"main.(*Slice{{\[\[}}]string,string]).Append"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP8]], ptr %[[TMP34]], ptr %[[TMP7]])
// DARWIN-ARM64-NEXT:   %[[TMP40:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP8]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP41:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// DARWIN-ARM64-NEXT:   %[[TMP42:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// DARWIN-ARM64-NEXT:   %[[TMP43:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP42]], i64 0
// DARWIN-ARM64-NEXT:   store i64 1, ptr %[[TMP43]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP44:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP42]], i64 1
// DARWIN-ARM64-NEXT:   store i64 2, ptr %[[TMP44]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP45:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP42]], i64 2
// DARWIN-ARM64-NEXT:   store i64 3, ptr %[[TMP45]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP46:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP42]], i64 3
// DARWIN-ARM64-NEXT:   store i64 4, ptr %[[TMP46]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP47:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP42]], 0
// DARWIN-ARM64-NEXT:   %[[TMP48:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP47]], i64 4, 1
// DARWIN-ARM64-NEXT:   %[[TMP49:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP48]], i64 4, 2
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP49]], ptr %[[TMP5]], align 8
// DARWIN-ARM64-NEXT:   call void @"main.(*Slice{{\[\[}}]int,int]).Append"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP6]], ptr %[[TMP41]], ptr %[[TMP5]])
// DARWIN-ARM64-NEXT:   %[[TMP50:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP6]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP51:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// DARWIN-ARM64-NEXT:   %[[TMP52:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP51]], i64 0
// DARWIN-ARM64-NEXT:   store i64 1, ptr %[[TMP52]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP53:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP51]], i64 1
// DARWIN-ARM64-NEXT:   store i64 2, ptr %[[TMP53]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP54:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP51]], i64 2
// DARWIN-ARM64-NEXT:   store i64 3, ptr %[[TMP54]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP55:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP51]], i64 3
// DARWIN-ARM64-NEXT:   store i64 4, ptr %[[TMP55]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP56:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP51]], 0
// DARWIN-ARM64-NEXT:   %[[TMP57:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP56]], i64 4, 1
// DARWIN-ARM64-NEXT:   %[[TMP58:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP57]], i64 4, 2
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP58]], ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   call void @"main.(*Slice{{\[\[}}]int,int]).Append2"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP4]], ptr %[[TMP41]], ptr %[[TMP3]])
// DARWIN-ARM64-NEXT:   %[[TMP59:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP60:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP27]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP61:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP60]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP62:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP27]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP63:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP62]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP64:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP63]], 0
// DARWIN-ARM64-NEXT:   %[[TMP65:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP63]], 1
// DARWIN-ARM64-NEXT:   %[[TMP66:[0-9]+]] = icmp uge i64 0, %[[TMP65]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP66]], i64 0, i1 true, i64 %[[TMP65]])
// DARWIN-ARM64-NEXT:   %[[TMP67:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP64]], i64 0
// DARWIN-ARM64-NEXT:   %[[TMP68:[0-9]+]] = load i64, ptr %[[TMP67]], align 8
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP61]], ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintSlice"(ptr %[[TMP2]])
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP68]])
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP69:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP34]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP70:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP69]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP71:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP34]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP39]], i64 0
// LINUX-AMD64-NEXT:   store i64 100, ptr %[[TMP40]], align 8
// LINUX-AMD64-NEXT:   %[[TMP41:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP39]], 0
// LINUX-AMD64-NEXT:   %[[TMP42:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP41]], i64 1, 1
// LINUX-AMD64-NEXT:   %[[TMP43:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP42]], i64 1, 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP43]], ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   call void @"main.(*Slice{{\[\[}}]int,int]).Append"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP11]], ptr %[[TMP38]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP10]])
// LINUX-AMD64-NEXT:   %[[TMP44:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP45:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// LINUX-AMD64-NEXT:   %[[TMP46:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 16)
// LINUX-AMD64-NEXT:   %[[TMP47:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP46]], i64 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 5 }, ptr %[[TMP47]], align 8
// LINUX-AMD64-NEXT:   %[[TMP48:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP46]], 0
// LINUX-AMD64-NEXT:   %[[TMP49:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP48]], i64 1, 1
// LINUX-AMD64-NEXT:   %[[TMP50:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP49]], i64 1, 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP50]], ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   call void @"main.(*Slice{{\[\[}}]string,string]).Append"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP9]], ptr %[[TMP45]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP8]])
// LINUX-AMD64-NEXT:   %[[TMP51:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP52:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// LINUX-AMD64-NEXT:   %[[TMP53:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// LINUX-AMD64-NEXT:   %[[TMP54:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP53]], i64 0
// LINUX-AMD64-NEXT:   store i64 1, ptr %[[TMP54]], align 8
// LINUX-AMD64-NEXT:   %[[TMP55:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP53]], i64 1
// LINUX-AMD64-NEXT:   store i64 2, ptr %[[TMP55]], align 8
// LINUX-AMD64-NEXT:   %[[TMP56:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP53]], i64 2
// LINUX-AMD64-NEXT:   store i64 3, ptr %[[TMP56]], align 8
// LINUX-AMD64-NEXT:   %[[TMP57:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP53]], i64 3
// LINUX-AMD64-NEXT:   store i64 4, ptr %[[TMP57]], align 8
// LINUX-AMD64-NEXT:   %[[TMP58:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP53]], 0
// LINUX-AMD64-NEXT:   %[[TMP59:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP58]], i64 4, 1
// LINUX-AMD64-NEXT:   %[[TMP60:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP59]], i64 4, 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP60]], ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   call void @"main.(*Slice{{\[\[}}]int,int]).Append"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP7]], ptr %[[TMP52]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP6]])
// LINUX-AMD64-NEXT:   %[[TMP61:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP62:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// LINUX-AMD64-NEXT:   %[[TMP63:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP62]], i64 0
// LINUX-AMD64-NEXT:   store i64 1, ptr %[[TMP63]], align 8
// LINUX-AMD64-NEXT:   %[[TMP64:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP62]], i64 1
// LINUX-AMD64-NEXT:   store i64 2, ptr %[[TMP64]], align 8
// LINUX-AMD64-NEXT:   %[[TMP65:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP62]], i64 2
// LINUX-AMD64-NEXT:   store i64 3, ptr %[[TMP65]], align 8
// LINUX-AMD64-NEXT:   %[[TMP66:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP62]], i64 3
// LINUX-AMD64-NEXT:   store i64 4, ptr %[[TMP66]], align 8
// LINUX-AMD64-NEXT:   %[[TMP67:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" undef, ptr %[[TMP62]], 0
// LINUX-AMD64-NEXT:   %[[TMP68:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP67]], i64 4, 1
// LINUX-AMD64-NEXT:   %[[TMP69:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP68]], i64 4, 2
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP69]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   call void @"main.(*Slice{{\[\[}}]int,int]).Append2"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr %[[TMP52]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP4]])
// LINUX-AMD64-NEXT:   %[[TMP70:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP71:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP38]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP72:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP71]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP73:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP72]], 0
// DARWIN-ARM64-NEXT:   %[[TMP74:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP72]], 1
// DARWIN-ARM64-NEXT:   %[[TMP75:[0-9]+]] = icmp uge i64 0, %[[TMP74]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP75]], i64 0, i1 true, i64 %[[TMP74]])
// DARWIN-ARM64-NEXT:   %[[TMP76:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP73]], i64 0
// DARWIN-ARM64-NEXT:   %[[TMP77:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP76]], align 8
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP70]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintSlice"(ptr %[[TMP1]])
// LINUX-AMD64-NEXT:   %[[TMP73:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP38]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP74:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP73]], align 8
// LINUX-AMD64-NEXT:   %[[TMP75:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP74]], 0
// LINUX-AMD64-NEXT:   %[[TMP76:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP74]], 1
// LINUX-AMD64-NEXT:   %[[TMP77:[0-9]+]] = icmp uge i64 0, %[[TMP76]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP77]], i64 0, i1 true, i64 %[[TMP76]])
// LINUX-AMD64-NEXT:   %[[TMP78:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP75]], i64 0
// LINUX-AMD64-NEXT:   %[[TMP79:[0-9]+]] = load i64, ptr %[[TMP78]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP72]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintSlice"(ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP3]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP77]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP79]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP78:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP41]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP79:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP78]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP80:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP41]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP80:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP45]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP81:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP80]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP82:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP81]], 0
// DARWIN-ARM64-NEXT:   %[[TMP83:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP81]], 1
// DARWIN-ARM64-NEXT:   %[[TMP84:[0-9]+]] = icmp uge i64 0, %[[TMP83]]
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP84]], i64 0, i1 true, i64 %[[TMP83]])
// DARWIN-ARM64-NEXT:   %[[TMP85:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP82]], i64 0
// DARWIN-ARM64-NEXT:   %[[TMP86:[0-9]+]] = load i64, ptr %[[TMP85]], align 8
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP79]], ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintSlice"(ptr %[[TMP0]])
// LINUX-AMD64-NEXT:   %[[TMP82:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP45]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP83:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP82]], align 8
// LINUX-AMD64-NEXT:   %[[TMP84:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP83]], 0
// LINUX-AMD64-NEXT:   %[[TMP85:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP83]], 1
// LINUX-AMD64-NEXT:   %[[TMP86:[0-9]+]] = icmp uge i64 0, %[[TMP85]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP86]], i64 0, i1 true, i64 %[[TMP85]])
// LINUX-AMD64-NEXT:   %[[TMP87:[0-9]+]] = getelementptr inbounds %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP84]], i64 0
// LINUX-AMD64-NEXT:   %[[TMP88:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP87]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP81]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintSlice"(ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP2]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP86]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP88]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP89:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP90:[0-9]+]] = load ptr, ptr %[[TMP89]], align 8
// LINUX-AMD64-NEXT:   %[[TMP91:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP92:[0-9]+]] = load i64, ptr %[[TMP91]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP90]], i64 %[[TMP92]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// LINUX-AMD64-NEXT:   %[[TMP93:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP52]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP94:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP93]], align 8
// LINUX-AMD64-NEXT:   %[[TMP95:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP52]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP96:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP95]], align 8
// LINUX-AMD64-NEXT:   %[[TMP97:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP96]], 0
// LINUX-AMD64-NEXT:   %[[TMP98:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP96]], 1
// LINUX-AMD64-NEXT:   %[[TMP99:[0-9]+]] = icmp uge i64 0, %[[TMP98]]
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.CheckIndexRange"(i1 %[[TMP99]], i64 0, i1 true, i64 %[[TMP98]])
// LINUX-AMD64-NEXT:   %[[TMP100:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP97]], i64 0
// LINUX-AMD64-NEXT:   %[[TMP101:[0-9]+]] = load i64, ptr %[[TMP100]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP94]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintSlice"(ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP101]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*Slice{{\[\[}}]int,int]).Append"(
// DARWIN-ARM64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr %[[TMP2:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP2:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP6]], align 8
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]], ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SliceAppend"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr %[[TMP4]], ptr %[[TMP8]], i64 %[[TMP9]], i64 8)
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SliceAppend"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP4]], ptr %[[TMP8]], i64 %[[TMP9]], i64 8)
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP5]], align 8
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], ptr %[[TMP11]], align 8
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP12]], align 8
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP13]], ptr %[[TMP0]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*Slice{{\[\[}}]string,string]).Append"(
// DARWIN-ARM64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr %[[TMP2:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP2:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP6]], align 8
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]], ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SliceAppend"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr %[[TMP4]], ptr %[[TMP8]], i64 %[[TMP9]], i64 16)
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SliceAppend"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP4]], ptr %[[TMP8]], i64 %[[TMP9]], i64 16)
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP5]], align 8
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], ptr %[[TMP11]], align 8
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]string,string]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP12]], align 8
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP13]], ptr %[[TMP0]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*Slice{{\[\[}}]int,int]).Append2"(
// DARWIN-ARM64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr %[[TMP2:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP2:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.Slice", align 8
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP6]], align 8
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP3]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP7]], ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SliceAppend"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr %[[TMP4]], ptr %[[TMP8]], i64 %[[TMP9]], i64 8)
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.SliceAppend"(ptr sret(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP5]], ptr byval(%"{{.*}}/runtime/internal/runtime.Slice") %[[TMP4]], ptr %[[TMP8]], i64 %[[TMP9]], i64 8)
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP5]], align 8
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP10]], ptr %[[TMP11]], align 8
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"main.Slice{{\[\[}}]int,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.Slice", ptr %[[TMP12]], align 8
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.Slice" %[[TMP13]], ptr %[[TMP0]], align 8
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
