// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.Wrapped.Name\E|\Qmain.Wrapped.github.com/goplus/llgo/cl/_testdata/embedunexport.setName\E|\Qmain.(*Wrapped).Name\E|\Qmain.(*Wrapped).github.com/goplus/llgo/cl/_testdata/embedunexport.setName\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

import "github.com/goplus/llgo/cl/_testdata/embedunexport"

// Wrapped embeds *embedunexport.Base to implement embedunexport.Object
type Wrapped struct {
	*embedunexport.Base
}

func main() {
	base := embedunexport.NewBase("test")
	wrapped := &Wrapped{Base: base}

	// This should work: calling unexported method through interface
	var obj embedunexport.Object = wrapped
	embedunexport.Use(obj)

	println(obj.Name())
}

// DARWIN-ARM64-LABEL: define %"{{.*}}/runtime/internal/runtime.String" @main.Wrapped.Name(
// DARWIN-ARM64-SAME: i64 %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-LABEL: define { ptr, i64 } @main.Wrapped.Name(
// LINUX-AMD64-SAME: %main.Wrapped %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = alloca i64, align 8
// DARWIN-ARM64-NEXT:   store i64 %[[TMP0]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load %main.Wrapped, ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = alloca %main.Wrapped, align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP3]], i8 0, i64 8, i1 false)
// DARWIN-ARM64-NEXT:   store %main.Wrapped %[[TMP2]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP1]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = load ptr, ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.String" @"{{.*}}/cl/_testdata/embedunexport.(*Base).Name"(ptr %[[TMP5]])
// DARWIN-ARM64-NEXT:   ret %"{{.*}}/runtime/internal/runtime.String" %[[TMP6]]
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %main.Wrapped, align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP2]], i8 0, i64 8, i1 false)
// LINUX-AMD64-NEXT:   store %main.Wrapped %[[TMP0]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = load ptr, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = call { ptr, i64 } @"{{.*}}/cl/_testdata/embedunexport.(*Base).Name"(ptr %[[TMP4]])
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP5]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP6]], ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load { ptr, i64 }, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   ret { ptr, i64 } %[[TMP8]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.Wrapped.{{.*}}/cl/_testdata/embedunexport.setName"(
// DARWIN-ARM64-SAME: i64 %[[TMP0:[0-9]+]], %"{{.*}}/runtime/internal/runtime.String" %[[TMP1:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: %main.Wrapped %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], i64 %[[TMP2:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = alloca i64, align 8
// DARWIN-ARM64-NEXT:   store i64 %[[TMP0]], ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = load %main.Wrapped, ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = alloca %main.Wrapped, align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP4]], i8 0, i64 8, i1 false)
// DARWIN-ARM64-NEXT:   store %main.Wrapped %[[TMP3]], ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP2]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr %[[TMP5]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/cl/_testdata/embedunexport.(*Base).setName"(ptr %[[TMP6]], %"{{.*}}/runtime/internal/runtime.String" %[[TMP1]])
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store i64 %[[TMP2]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = alloca %main.Wrapped, align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP8]], i8 0, i64 8, i1 false)
// LINUX-AMD64-NEXT:   store %main.Wrapped %[[TMP0]], ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP8]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = load ptr, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP6]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = load ptr, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = load i64, ptr %[[TMP13]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/cl/_testdata/embedunexport.(*Base).setName"(ptr %[[TMP10]], ptr %[[TMP12]], i64 %[[TMP14]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// DARWIN-ARM64-LABEL: define %"{{.*}}/runtime/internal/runtime.String" @"main.(*Wrapped).Name"(
// LINUX-AMD64-LABEL: define { ptr, i64 } @"main.(*Wrapped).Name"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP0]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load ptr, ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = call %"{{.*}}/runtime/internal/runtime.String" @"{{.*}}/cl/_testdata/embedunexport.(*Base).Name"(ptr %[[TMP2]])
// DARWIN-ARM64-NEXT:   ret %"{{.*}}/runtime/internal/runtime.String" %[[TMP3]]
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = load ptr, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = call { ptr, i64 } @"{{.*}}/cl/_testdata/embedunexport.(*Base).Name"(ptr %[[TMP3]])
// LINUX-AMD64-NEXT:   store { ptr, i64 } %[[TMP4]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP5]], ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = load { ptr, i64 }, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   ret { ptr, i64 } %[[TMP7]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.(*Wrapped).{{.*}}/cl/_testdata/embedunexport.setName"(
// DARWIN-ARM64-SAME: ptr %[[TMP0:[0-9]+]], %"{{.*}}/runtime/internal/runtime.String" %[[TMP1:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], ptr %[[TMP1:[0-9]+]], i64 %[[TMP2:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP0]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = load ptr, ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/cl/_testdata/embedunexport.(*Base).setName"(ptr %[[TMP3]], %"{{.*}}/runtime/internal/runtime.String" %[[TMP1]])
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca { ptr, i64 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP1]], ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store i64 %[[TMP2]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %main.Wrapped, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = load ptr, ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP6]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = load ptr, ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load i64, ptr %[[TMP12]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/cl/_testdata/embedunexport.(*Base).setName"(ptr %[[TMP9]], ptr %[[TMP11]], i64 %[[TMP13]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
