// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.T[string,int].Info\E|\Qmain.(*T[string,int]).Demo\E|\Qmain.(*T[string,int]).Info\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

import "github.com/goplus/lib/c"

// Generic instantiation keeps the concrete type in interface metadata and
// preserves both value and pointer method ABIs. llgo.advance must lower to the
// same array GEP for its C helper and linked method spellings.

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [1 x i8] c"a", align 1{{$}}
// CHECK: {{^}}@[[GLOB5:[0-9]+]] = private unnamed_addr constant [4 x i8] c"Info", align 1{{$}}
// CHECK: {{^}}@[[GLOB10:[0-9]+]] = private unnamed_addr constant [5 x i8] c"hello", align 1{{$}}
// CHECK: {{^}}@[[GLOB12:[0-9]+]] = private unnamed_addr constant [54 x i8] c"{{.*}}/cl/_testrt/tpabi.T[string, int]", align 1{{$}}

type T[M, N any] struct {
	m M
	n N
}

func (t *T[M, N]) Demo() {
	println(t.m, t.n)
}

func (t T[M, N]) Info() {
	println(t.m, t.n)
}

type I interface {
	Demo()
}

type K[N any] [4]N

//llgo:link (*K).Advance llgo.advance
func (t *K[N]) Advance(n int) *K[N] {
	return nil
}

func main() {
	var a any = T[string, int]{"a", 1}
	println(a.(T[string, int]).m)
	var i I = &T[string, int]{"hello", 100}
	i.Demo()

	k := &K[int]{1, 2, 3, 4}
	println(c.Advance(k, 1))
	println(k.Advance(1))
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"main.T[string,int]", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP0]], i8 0, i64 24, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 1 }, ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   store i64 1, ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 24)
// DARWIN-ARM64-NEXT:   store %"main.T[string,int]" %[[TMP3]], ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_main.T[string,int]", ptr undef }, ptr %[[TMP4]], 1
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 0
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = icmp eq ptr %[[TMP6]], @"_llgo_main.T[string,int]"
// DARWIN-ARM64-NEXT:   br i1 %[[TMP7]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.iface", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"main.T[string,int]", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP2]], i8 0, i64 24, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 1 }, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   store i64 1, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 24)
// LINUX-AMD64-NEXT:   store %"main.T[string,int]" %[[TMP5]], ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_main.T[string,int]", ptr undef }, ptr %[[TMP6]], 1
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP7]], 0
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = icmp eq ptr %[[TMP8]], @"_llgo_main.T[string,int]"
// LINUX-AMD64-NEXT:   br i1 %[[TMP9]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 1
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP8]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = extractvalue %"main.T[string,int]" %[[TMP9]], 0
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP10]])
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP7]], 1
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = extractvalue %"main.T[string,int]" %[[TMP11]], 0
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP12]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = load ptr, ptr %[[TMP13]], align 8
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = load i64, ptr %[[TMP15]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP14]], i64 %[[TMP16]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP11]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP11]], i32 0, i32 1
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB10]], i64 5 }, ptr %[[TMP12]], align 8
// DARWIN-ARM64-NEXT:   store i64 100, ptr %[[TMP13]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewItab"(ptr @"_llgo_iface$BP0p_lUsEd-IbbtJVukGmgrdQkqzcoYzSiwgUvgFvUs", ptr @"*_llgo_main.T[string,int]")
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" undef, ptr %[[TMP14]], 0
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP15]], ptr %[[TMP11]], 1
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP16]])
// DARWIN-ARM64-NEXT:   %[[TMP18:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP16]], 0
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = getelementptr ptr, ptr %[[TMP18]], i64 3
// DARWIN-ARM64-NEXT:   %[[TMP20:[0-9]+]] = load ptr, ptr %[[TMP19]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP21:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP20]], 0
// DARWIN-ARM64-NEXT:   %[[TMP22:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP21]], ptr %[[TMP17]], 1
// DARWIN-ARM64-NEXT:   %[[TMP23:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP22]], 1
// DARWIN-ARM64-NEXT:   %[[TMP24:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP22]], 0
// DARWIN-ARM64-NEXT:   call void %[[TMP24]](ptr %[[TMP23]])
// DARWIN-ARM64-NEXT:   %[[TMP25:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// DARWIN-ARM64-NEXT:   %[[TMP26:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 0
// DARWIN-ARM64-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 1
// DARWIN-ARM64-NEXT:   %[[TMP28:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 2
// DARWIN-ARM64-NEXT:   %[[TMP29:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 3
// DARWIN-ARM64-NEXT:   store i64 1, ptr %[[TMP26]], align 8
// DARWIN-ARM64-NEXT:   store i64 2, ptr %[[TMP27]], align 8
// DARWIN-ARM64-NEXT:   store i64 3, ptr %[[TMP28]], align 8
// DARWIN-ARM64-NEXT:   store i64 4, ptr %[[TMP29]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP30:[0-9]+]] = getelementptr [4 x i64], ptr %[[TMP25]], i64 1
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP30]])
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP17]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP17]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB10]], i64 5 }, ptr %[[TMP18]], align 8
// LINUX-AMD64-NEXT:   store i64 100, ptr %[[TMP19]], align 8
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewItab"(ptr @"_llgo_iface$BP0p_lUsEd-IbbtJVukGmgrdQkqzcoYzSiwgUvgFvUs", ptr @"*_llgo_main.T[string,int]")
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" undef, ptr %[[TMP20]], 0
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP21]], ptr %[[TMP17]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.iface" %[[TMP22]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = load ptr, ptr %[[TMP23]], align 8
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = getelementptr inbounds { ptr, ptr }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = load ptr, ptr %[[TMP25]], align 8
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(ptr %[[TMP24]], ptr %[[TMP26]])
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP22]], 0
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = getelementptr ptr, ptr %[[TMP28]], i64 3
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = load ptr, ptr %[[TMP29]], align 8
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP30]], 0
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP31]], ptr %[[TMP27]], 1
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP32]], 1
// LINUX-AMD64-NEXT:   %[[TMP34:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP32]], 0
// LINUX-AMD64-NEXT:   call void %[[TMP34]](ptr %[[TMP33]])
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP35]], i64 0
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP35]], i64 1
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP35]], i64 2
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP35]], i64 3
// LINUX-AMD64-NEXT:   store i64 1, ptr %[[TMP36]], align 8
// LINUX-AMD64-NEXT:   store i64 2, ptr %[[TMP37]], align 8
// LINUX-AMD64-NEXT:   store i64 3, ptr %[[TMP38]], align 8
// LINUX-AMD64-NEXT:   store i64 4, ptr %[[TMP39]], align 8
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = getelementptr [4 x i64], ptr %[[TMP35]], i64 1
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP40]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// DARWIN-ARM64-NEXT:   %[[TMP31:[0-9]+]] = getelementptr [4 x i64], ptr %[[TMP25]], i64 1
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP31]])
// LINUX-AMD64-NEXT:   %[[TMP41:[0-9]+]] = getelementptr [4 x i64], ptr %[[TMP35]], i64 1
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP41]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP6]], ptr @"_llgo_main.T[string,int]")
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP8]], ptr @"_llgo_main.T[string,int]")
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*T[string,int]).Demo"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = load i64, ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP2]])
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load i64, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP3]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = load ptr, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = load i64, ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP7]], i64 %[[TMP9]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP4]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP5]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*T[string,int]).Info"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"main.T[string,int]", align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = icmp eq ptr %[[TMP0]], null
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicWrapNilPointer"(i1 %[[TMP2]], %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB12]], i64 54 }, %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB5]], i64 4 })
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   store %"main.T[string,int]" %[[TMP3]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   call void @"main.T[string,int].Info"(ptr %[[TMP1]])
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = icmp eq ptr %[[TMP0]], null
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB12]], i64 54 }, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load i64, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB5]], i64 4 }, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = load ptr, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = load i64, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicWrapNilPointer"(i1 %[[TMP4]], ptr %[[TMP6]], i64 %[[TMP8]], ptr %[[TMP10]], i64 %[[TMP12]])
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   store %"main.T[string,int]" %[[TMP13]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   call void @"main.T[string,int].Info"(ptr byval(%"main.T[string,int]") %[[TMP1]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.T[string,int].Info"(
// DARWIN-ARM64-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr byval(%"main.T[string,int]") %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"main.T[string,int]", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP2]], i8 0, i64 24, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"main.T[string,int]", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP3]], i8 0, i64 24, i1 false)
// CHECK-NEXT:   store %"main.T[string,int]" %[[TMP1]], ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = load i64, ptr %[[TMP5]], align 8
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP4]])
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = load i64, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP5]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = load ptr, ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = load i64, ptr %[[TMP10]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP9]], i64 %[[TMP11]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP6]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP7]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
