// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.T[string,int].Info\E|\Qmain.(*T[string,int]).Demo\E|\Qmain.(*T[string,int]).Info\E) --check-globals=smart
package main

import "github.com/goplus/lib/c"

// Generic instantiation keeps the concrete type in interface metadata and
// preserves both value and pointer method ABIs. llgo.advance must lower to the
// same array GEP for its C helper and linked method spellings.

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [1 x i8] c"a", align 1{{$}}
// CHECK: {{^}}@[[GLOB5:[0-9]+]] = private unnamed_addr constant [4 x i8] c"Info", align 1{{$}}
// CHECK: {{^}}@[[GLOB10:[0-9]+]] = private unnamed_addr constant [5 x i8] c"hello", align 1{{$}}
// CHECK: {{^}}@[[GLOB12:[0-9]+]] = private unnamed_addr constant [55 x i8] c"{{.*}}/cl/_testrt/tpabi.T[string, int]", align 1{{$}}

type T[M, N any] struct {
	m M
	n N
}

func (t *T[M, N]) Demo() {
	println(t.m, t.n)
}

func (t T[M, N]) Info() {
	println(t.m, t.n)
}

type I interface {
	Demo()
}

type K[N any] [4]N

//llgo:link (*K).Advance llgo.advance
func (t *K[N]) Advance(n int) *K[N] {
	return nil
}

func main() {
	var a any = T[string, int]{"a", 1}
	println(a.(T[string, int]).m)
	var i I = &T[string, int]{"hello", 100}
	i.Demo()

	k := &K[int]{1, 2, 3, 4}
	println(c.Advance(k, 1))
	println(k.Advance(1))
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = alloca %"main.T[string,int]", align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP0]], i8 0, i64 24, i1 false)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB0]], i64 1 }, ptr %[[TMP1]], align 8
// CHECK-NEXT:   store i64 1, ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 24)
// CHECK-NEXT:   store %"main.T[string,int]" %[[TMP3]], ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_main.T[string,int]", ptr undef }, ptr %[[TMP4]], 1
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = icmp eq ptr %[[TMP6]], @"_llgo_main.T[string,int]"
// CHECK-NEXT:   br i1 %[[TMP7]], label %_llgo_[[BB1:[0-9]+]], label %_llgo_[[BB2:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1]]:
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP5]], 1
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP8]], align 8
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = extractvalue %"main.T[string,int]" %[[TMP9]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP10]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 24)
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP11]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP11]], i32 0, i32 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB10]], i64 5 }, ptr %[[TMP12]], align 8
// CHECK-NEXT:   store i64 100, ptr %[[TMP13]], align 8
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.NewItab"(ptr @"_llgo_iface$BP0p_lUsEd-IbbtJVukGmgrdQkqzcoYzSiwgUvgFvUs", ptr @"*_llgo_main.T[string,int]")
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" undef, ptr %[[TMP14]], 0
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP15]], ptr %[[TMP11]], 1
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.IfacePtrData"(%"{{.*}}/runtime/internal/runtime.iface" %[[TMP16]])
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.iface" %[[TMP16]], 0
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = getelementptr ptr, ptr %[[TMP18]], i64 3
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = load ptr, ptr %[[TMP19]], align 8
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = insertvalue { ptr, ptr } undef, ptr %[[TMP20]], 0
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = insertvalue { ptr, ptr } %[[TMP21]], ptr %[[TMP17]], 1
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP22]], 1
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP22]], 0
// CHECK-NEXT:   call void %[[TMP24]](ptr %[[TMP23]])
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocZ"(i64 32)
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 0
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 1
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 2
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = getelementptr inbounds i64, ptr %[[TMP25]], i64 3
// CHECK-NEXT:   store i64 1, ptr %[[TMP26]], align 8
// CHECK-NEXT:   store i64 2, ptr %[[TMP27]], align 8
// CHECK-NEXT:   store i64 3, ptr %[[TMP28]], align 8
// CHECK-NEXT:   store i64 4, ptr %[[TMP29]], align 8
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = getelementptr [4 x i64], ptr %[[TMP25]], i64 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP30]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = getelementptr [4 x i64], ptr %[[TMP25]], i64 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP31]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2]]:
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicTypeAssert"(ptr null, ptr %[[TMP6]], ptr @"_llgo_main.T[string,int]")
// CHECK-NEXT:   unreachable
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.T[string,int].Info"(
// CHECK-SAME: %"main.T[string,int]" %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"main.T[string,int]", align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP1]], i8 0, i64 24, i1 false)
// CHECK-NEXT:   store %"main.T[string,int]" %[[TMP0]], ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP1]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = load i64, ptr %[[TMP4]], align 8
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP3]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP5]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*T[string,int]).Demo"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %"main.T[string,int]", ptr %[[TMP0]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = load i64, ptr %[[TMP3]], align 8
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP2]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintInt"(i64 %[[TMP4]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define linkonce void @"main.(*T[string,int]).Info"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = icmp eq ptr %[[TMP0]], null
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicWrapNilPointer"(i1 %[[TMP1]], %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB12]], i64 55 }, %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB5]], i64 4 })
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load %"main.T[string,int]", ptr %[[TMP0]], align 8
// CHECK-NEXT:   call void @"main.T[string,int].Info"(%"main.T[string,int]" %[[TMP2]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
