// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E) --check-globals=smart
package main

// CHECK: {{^}}@[[GLOB29:[0-9]+]] = private unnamed_addr constant [5 x i8] c"world", align 1{{$}}

type T1 int

type T2 struct {
	v int
}

type T3[T any] struct {
	v T
}

type cacheKey struct {
	t1 T1
	t2 T2
	t3 T3[any]
	t4 *int
	t5 uintptr
}

func main() {
	m := map[cacheKey]string{}
	m[cacheKey{0, T2{0}, T3[any]{0}, nil, 0}] = "world"
	v, ok := m[cacheKey{0, T2{0}, T3[any]{0}, nil, 0}]
	println(v, ok)
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MakeMap"(ptr @"map[_llgo_main.cacheKey]_llgo_string", i64 0)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %main.cacheKey, align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP1]], i8 0, i64 48, i1 false)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP1]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP1]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.T2, ptr %[[TMP3]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP1]], i32 0, i32 2
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %"main.T3[any]", ptr %[[TMP5]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP1]], i32 0, i32 3
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP1]], i32 0, i32 4
// CHECK-NEXT:   store i64 0, ptr %[[TMP2]], align 8
// CHECK-NEXT:   store i64 0, ptr %[[TMP4]], align 8
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 0, ptr %[[TMP9]], align 8
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP9]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP10]], ptr %[[TMP6]], align 8
// CHECK-NEXT:   store ptr null, ptr %[[TMP7]], align 8
// CHECK-NEXT:   store i64 0, ptr %[[TMP8]], align 8
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = load %main.cacheKey, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// CHECK-NEXT:   store %main.cacheKey %[[TMP11]], ptr %[[TMP12]], align 8
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MapAssign"(ptr @"map[_llgo_main.cacheKey]_llgo_string", ptr %[[TMP0]], ptr %[[TMP12]])
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB29]], i64 5 }, ptr %[[TMP13]], align 8
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = alloca %main.cacheKey, align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP14]], i8 0, i64 48, i1 false)
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP14]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP14]], i32 0, i32 1
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds %main.T2, ptr %[[TMP16]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP14]], i32 0, i32 2
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds %"main.T3[any]", ptr %[[TMP18]], i32 0, i32 0
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP14]], i32 0, i32 3
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP14]], i32 0, i32 4
// CHECK-NEXT:   store i64 0, ptr %[[TMP15]], align 8
// CHECK-NEXT:   store i64 0, ptr %[[TMP17]], align 8
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store i64 0, ptr %[[TMP22]], align 8
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP22]], 1
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP23]], ptr %[[TMP19]], align 8
// CHECK-NEXT:   store ptr null, ptr %[[TMP20]], align 8
// CHECK-NEXT:   store i64 0, ptr %[[TMP21]], align 8
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = load %main.cacheKey, ptr %[[TMP14]], align 8
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// CHECK-NEXT:   store %main.cacheKey %[[TMP24]], ptr %[[TMP25]], align 8
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = call { ptr, i1 } @"{{.*}}/runtime/internal/runtime.MapAccess2"(ptr @"map[_llgo_main.cacheKey]_llgo_string", ptr %[[TMP0]], ptr %[[TMP25]])
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP26]], 0
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP27]], align 8
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP26]], 1
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } undef, %"{{.*}}/runtime/internal/runtime.String" %[[TMP28]], 0
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP30]], i1 %[[TMP29]], 1
// CHECK-NEXT:   %[[TMP32:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP31]], 0
// CHECK-NEXT:   %[[TMP33:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP31]], 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP32]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP33]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
