// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package main

// CHECK: {{^}}@[[GLOB29:[0-9]+]] = private unnamed_addr constant [5 x i8] c"world", align 1{{$}}

type T1 int

type T2 struct {
	v int
}

type T3[T any] struct {
	v T
}

type cacheKey struct {
	t1 T1
	t2 T2
	t3 T3[any]
	t4 *int
	t5 uintptr
}

func main() {
	m := map[cacheKey]string{}
	m[cacheKey{0, T2{0}, T3[any]{0}, nil, 0}] = "world"
	v, ok := m[cacheKey{0, T2{0}, T3[any]{0}, nil, 0}]
	println(v, ok)
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP0:[0-9]+]] = alloca [2 x i64], align 8
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MakeMap"(ptr @"map[_llgo_main.cacheKey]_llgo_string", i64 0)
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = alloca %main.cacheKey, align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP2]], i8 0, i64 48, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP2]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP2]], i32 0, i32 1
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %main.T2, ptr %[[TMP4]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP2]], i32 0, i32 2
// DARWIN-ARM64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %"main.T3[any]", ptr %[[TMP6]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP2]], i32 0, i32 3
// DARWIN-ARM64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP2]], i32 0, i32 4
// DARWIN-ARM64-NEXT:   store i64 0, ptr %[[TMP3]], align 8
// DARWIN-ARM64-NEXT:   store i64 0, ptr %[[TMP5]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP10:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP0:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP1:[0-9]+]] = alloca { ptr, i1 }, align 8
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MakeMap"(ptr @"map[_llgo_main.cacheKey]_llgo_string", i64 0)
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca %main.cacheKey, align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP3]], i8 0, i64 48, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = getelementptr inbounds %main.T2, ptr %[[TMP5]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP3]], i32 0, i32 2
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = getelementptr inbounds %"main.T3[any]", ptr %[[TMP7]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP3]], i32 0, i32 3
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP3]], i32 0, i32 4
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP4]], align 8
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP6]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP11]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP12]], ptr %[[TMP8]], align 8
// LINUX-AMD64-NEXT:   store ptr null, ptr %[[TMP9]], align 8
// CHECK-NEXT:   store i64 0, ptr %[[TMP10]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP11:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP10]], 1
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP11]], ptr %[[TMP7]], align 8
// DARWIN-ARM64-NEXT:   store ptr null, ptr %[[TMP8]], align 8
// DARWIN-ARM64-NEXT:   store i64 0, ptr %[[TMP9]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP12:[0-9]+]] = load %main.cacheKey, ptr %[[TMP2]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP13:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// DARWIN-ARM64-NEXT:   store %main.cacheKey %[[TMP12]], ptr %[[TMP13]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MapAssign"(ptr @"map[_llgo_main.cacheKey]_llgo_string", ptr %[[TMP1]], ptr %[[TMP13]])
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB29]], i64 5 }, ptr %[[TMP14]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP15:[0-9]+]] = alloca %main.cacheKey, align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP15]], i8 0, i64 48, i1 false)
// DARWIN-ARM64-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP15]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP15]], i32 0, i32 1
// DARWIN-ARM64-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds %main.T2, ptr %[[TMP17]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP15]], i32 0, i32 2
// DARWIN-ARM64-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds %"main.T3[any]", ptr %[[TMP19]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP21:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP15]], i32 0, i32 3
// DARWIN-ARM64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP15]], i32 0, i32 4
// DARWIN-ARM64-NEXT:   store i64 0, ptr %[[TMP16]], align 8
// DARWIN-ARM64-NEXT:   store i64 0, ptr %[[TMP18]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP23:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load %main.cacheKey, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// LINUX-AMD64-NEXT:   store %main.cacheKey %[[TMP13]], ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.MapAssign"(ptr @"map[_llgo_main.cacheKey]_llgo_string", ptr %[[TMP2]], ptr %[[TMP14]])
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB29]], i64 5 }, ptr %[[TMP15]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = alloca %main.cacheKey, align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP16]], i8 0, i64 48, i1 false)
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP16]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP16]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP19:[0-9]+]] = getelementptr inbounds %main.T2, ptr %[[TMP18]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP20:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP16]], i32 0, i32 2
// LINUX-AMD64-NEXT:   %[[TMP21:[0-9]+]] = getelementptr inbounds %"main.T3[any]", ptr %[[TMP20]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP22:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP16]], i32 0, i32 3
// LINUX-AMD64-NEXT:   %[[TMP23:[0-9]+]] = getelementptr inbounds %main.cacheKey, ptr %[[TMP16]], i32 0, i32 4
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP17]], align 8
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP19]], align 8
// LINUX-AMD64-NEXT:   %[[TMP24:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// LINUX-AMD64-NEXT:   store i64 0, ptr %[[TMP24]], align 8
// LINUX-AMD64-NEXT:   %[[TMP25:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP24]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP25]], ptr %[[TMP21]], align 8
// LINUX-AMD64-NEXT:   store ptr null, ptr %[[TMP22]], align 8
// CHECK-NEXT:   store i64 0, ptr %[[TMP23]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP24:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_int, ptr undef }, ptr %[[TMP23]], 1
// DARWIN-ARM64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP24]], ptr %[[TMP20]], align 8
// DARWIN-ARM64-NEXT:   store ptr null, ptr %[[TMP21]], align 8
// DARWIN-ARM64-NEXT:   store i64 0, ptr %[[TMP22]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP25:[0-9]+]] = load %main.cacheKey, ptr %[[TMP15]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP26:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// DARWIN-ARM64-NEXT:   store %main.cacheKey %[[TMP25]], ptr %[[TMP26]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP27:[0-9]+]] = call [2 x i64] @"{{.*}}/runtime/internal/runtime.MapAccess2"(ptr @"map[_llgo_main.cacheKey]_llgo_string", ptr %[[TMP1]], ptr %[[TMP26]])
// DARWIN-ARM64-NEXT:   store [2 x i64] %[[TMP27]], ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP28:[0-9]+]] = load { ptr, i1 }, ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP29:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP28]], 0
// DARWIN-ARM64-NEXT:   %[[TMP30:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP29]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP31:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP28]], 1
// DARWIN-ARM64-NEXT:   %[[TMP32:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } undef, %"{{.*}}/runtime/internal/runtime.String" %[[TMP30]], 0
// DARWIN-ARM64-NEXT:   %[[TMP33:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP32]], i1 %[[TMP31]], 1
// DARWIN-ARM64-NEXT:   %[[TMP34:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP33]], 0
// DARWIN-ARM64-NEXT:   %[[TMP35:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP33]], 1
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(%"{{.*}}/runtime/internal/runtime.String" %[[TMP34]])
// LINUX-AMD64-NEXT:   %[[TMP26:[0-9]+]] = load %main.cacheKey, ptr %[[TMP16]], align 8
// LINUX-AMD64-NEXT:   %[[TMP27:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 48)
// LINUX-AMD64-NEXT:   store %main.cacheKey %[[TMP26]], ptr %[[TMP27]], align 8
// LINUX-AMD64-NEXT:   %[[TMP28:[0-9]+]] = call { ptr, i1 } @"{{.*}}/runtime/internal/runtime.MapAccess2"(ptr @"map[_llgo_main.cacheKey]_llgo_string", ptr %[[TMP2]], ptr %[[TMP27]])
// LINUX-AMD64-NEXT:   store { ptr, i1 } %[[TMP28]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP29:[0-9]+]] = load { ptr, i1 }, ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP30:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP29]], 0
// LINUX-AMD64-NEXT:   %[[TMP31:[0-9]+]] = load %"{{.*}}/runtime/internal/runtime.String", ptr %[[TMP30]], align 8
// LINUX-AMD64-NEXT:   %[[TMP32:[0-9]+]] = extractvalue { ptr, i1 } %[[TMP29]], 1
// LINUX-AMD64-NEXT:   %[[TMP33:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } undef, %"{{.*}}/runtime/internal/runtime.String" %[[TMP31]], 0
// LINUX-AMD64-NEXT:   %[[TMP34:[0-9]+]] = insertvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP33]], i1 %[[TMP32]], 1
// LINUX-AMD64-NEXT:   %[[TMP35:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP34]], 0
// LINUX-AMD64-NEXT:   %[[TMP36:[0-9]+]] = extractvalue { %"{{.*}}/runtime/internal/runtime.String", i1 } %[[TMP34]], 1
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" %[[TMP35]], ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   %[[TMP37:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP38:[0-9]+]] = load ptr, ptr %[[TMP37]], align 8
// LINUX-AMD64-NEXT:   %[[TMP39:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP0]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP40:[0-9]+]] = load i64, ptr %[[TMP39]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintString"(ptr %[[TMP38]], i64 %[[TMP40]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP35]])
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP36]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
