// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E|\Qmain.(*outer).M$thunk\E|\Qmain.(*InnerInt).M$thunk\E) --check-globals=smart
package main

// Method expressions use signature-specific thunks. In particular, the two
// M methods below must not become interchangeable closure types.

// CHECK: {{^}}@[[GLOB17:[0-9]+]] = private unnamed_addr constant [47 x i8] c"type assertion should have failed but succeeded", align 1{{$}}

type inner struct {
	x int
}

type outer struct {
	y int
	inner
}

func (*inner) M() {}

type InnerInt struct {
	X int
}

type OuterInt struct {
	Y int
	InnerInt
}

func (i *InnerInt) M() int {
	return i.X
}

func main() {
	var v1 any = (*outer).M
	var v2 any = (*InnerInt).M
	f1, ok := v1.(func(*outer))
	println(f1, ok)
	f2, ok := v2.(func(*outer))
	println(f2, ok)
	if ok {
		panic("type assertion should have failed but succeeded")
	}
}

func (m *outer) M() {}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store { ptr, ptr } { ptr @"main.(*outer).M$thunk", ptr null }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_closure$p06T23YeLPAu3v8p2hFtiY7Rlq6V9sr5dXePfqXtx6M", ptr undef }, ptr %[[TMP0]], 1
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store { ptr, ptr } { ptr @"main.(*InnerInt).M$thunk", ptr null }, ptr %[[TMP2]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_closure$WmZDdXg-2mo-o0lqY2QOZoNsd6Ks2TbzdX4upfVJ3j8", ptr undef }, ptr %[[TMP2]], 1
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP1]], 0
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.MatchesClosure"(ptr @"_llgo_closure$p06T23YeLPAu3v8p2hFtiY7Rlq6V9sr5dXePfqXtx6M", ptr %[[TMP4]])
// CHECK-NEXT:   br i1 %[[TMP5]], label %_llgo_[[BB3:[0-9]+]], label %_llgo_[[BB4:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB1:[0-9]+]]:
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 16)
// CHECK-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB17]], i64 47 }, ptr %[[TMP6]], align 8
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @_llgo_string, ptr undef }, ptr %[[TMP6]], 1
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.Panic"(%"{{.*}}/runtime/internal/runtime.eface" %[[TMP7]])
// CHECK-NEXT:   unreachable
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB2:[0-9]+]]:
// CHECK-NEXT:   ret void
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB3]]:
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP1]], 1
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP8]], align 8
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } undef, { ptr, ptr } %[[TMP9]], 0
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } %[[TMP10]], i1 true, 1
// CHECK-NEXT:   br label %_llgo_[[BB5:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB4]]:
// CHECK-NEXT:   br label %_llgo_[[BB5]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB5]]:
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = phi { { ptr, ptr }, i1 } [ %[[TMP11]], %_llgo_[[BB3]] ], [ zeroinitializer, %_llgo_[[BB4]] ]
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = extractvalue { { ptr, ptr }, i1 } %[[TMP12]], 0
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = extractvalue { { ptr, ptr }, i1 } %[[TMP12]], 1
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP13]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP15]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP14]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP3]], 0
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = call i1 @"{{.*}}/runtime/internal/runtime.MatchesClosure"(ptr @"_llgo_closure$p06T23YeLPAu3v8p2hFtiY7Rlq6V9sr5dXePfqXtx6M", ptr %[[TMP16]])
// CHECK-NEXT:   br i1 %[[TMP17]], label %_llgo_[[BB6:[0-9]+]], label %_llgo_[[BB7:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB6]]:
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = extractvalue %"{{.*}}/runtime/internal/runtime.eface" %[[TMP3]], 1
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP18]], align 8
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } undef, { ptr, ptr } %[[TMP19]], 0
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = insertvalue { { ptr, ptr }, i1 } %[[TMP20]], i1 true, 1
// CHECK-NEXT:   br label %_llgo_[[BB8:[0-9]+]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB7]]:
// CHECK-NEXT:   br label %_llgo_[[BB8]]
// CHECK-EMPTY:
// CHECK-NEXT: _llgo_[[BB8]]:
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = phi { { ptr, ptr }, i1 } [ %[[TMP21]], %_llgo_[[BB6]] ], [ zeroinitializer, %_llgo_[[BB7]] ]
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = extractvalue { { ptr, ptr }, i1 } %[[TMP22]], 0
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = extractvalue { { ptr, ptr }, i1 } %[[TMP22]], 1
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = extractvalue { ptr, ptr } %[[TMP23]], 0
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintPointer"(ptr %[[TMP25]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 32)
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintBool"(i1 %[[TMP24]])
// CHECK-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PrintByte"(i8 10)
// CHECK-NEXT:   br i1 %[[TMP24]], label %_llgo_[[BB1]], label %_llgo_[[BB2]]
// CHECK-NEXT: }

// CHECK-LABEL: define void @"main.(*outer).M$thunk"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   call void @"main.(*outer).M"(ptr %[[TMP0]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }

// CHECK-LABEL: define i64 @"main.(*InnerInt).M$thunk"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call i64 @"main.(*InnerInt).M"(ptr %[[TMP0]])
// CHECK-NEXT:   ret i64 %[[TMP1]]
// CHECK-NEXT: }
