name: Publish baseline benchmarks

on:
  workflow_run:
    workflows: [Baseline benchmarks]
    types: [completed]

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    uses: xgo-dev/setup-benchmark-go-action/.github/workflows/publish.yml@v1.0.5
    with:
      run_id: ${{ github.event.workflow_run.id }}
      config_path: .github/llgo-benchmark.yml
