name: Stdlib Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: stdlib-coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Check stdlib function coverage
        shell: bash
        run: bash doc/_readme/scripts/check_std_cover.sh
