// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\QBar\E|\QF\E|\QFoo.Pb\E|\Q(*Foo).Pb\E) --check-globals=smart
// NOTE: Autogenerated snapshot targets: DARWIN-ARM64 LINUX-AMD64
package foo

// CHECK: {{^}}@[[GLOB6:[0-9]+]] = private unnamed_addr constant [43 x i8] c"{{.*}}/cl/_testdata/foo.Foo", align 1{{$}}
// CHECK: {{^}}@[[GLOB7:[0-9]+]] = private unnamed_addr constant [2 x i8] c"Pb", align 1{{$}}

// DARWIN-ARM64-LABEL: define %"{{.*}}/runtime/internal/runtime.eface" @"{{.*}}/cl/_testdata/foo.Bar"(){{.*}} {
// LINUX-AMD64-LABEL: define { ptr, ptr } @"{{.*}}/cl/_testdata/foo.Bar"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = alloca { i64 }, align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP0]], i8 0, i64 8, i1 false)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds { i64 }, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   store i64 1, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load { i64 }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store { i64 } %[[TMP2]], ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"_llgo_struct$K-dZ9QotZfVPz2a0YdRa9vmZUuDXPTqZOlMShKEDJtk", ptr undef }, ptr %[[TMP3]], 1
// DARWIN-ARM64-NEXT:   ret %"{{.*}}/runtime/internal/runtime.eface" %[[TMP4]]
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP4]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   ret { ptr, ptr } %[[TMP6]]
// CHECK-NEXT: }

func Bar() any {
	return struct{ V int }{1}
}

// DARWIN-ARM64-LABEL: define %"{{.*}}/runtime/internal/runtime.eface" @"{{.*}}/cl/_testdata/foo.F"(){{.*}} {
// LINUX-AMD64-LABEL: define { ptr, ptr } @"{{.*}}/cl/_testdata/foo.F"(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = alloca { i64 }, align 8
// CHECK-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP0]], i8 0, i64 8, i1 false)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = getelementptr inbounds { i64 }, ptr %[[TMP0]], i32 0, i32 0
// CHECK-NEXT:   store i64 1, ptr %[[TMP1]], align 8
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = load { i64 }, ptr %[[TMP0]], align 8
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call ptr @"{{.*}}/runtime/internal/runtime.AllocU"(i64 8)
// CHECK-NEXT:   store { i64 } %[[TMP2]], ptr %[[TMP3]], align 8
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = insertvalue %"{{.*}}/runtime/internal/runtime.eface" { ptr @"{{.*}}/cl/_testdata/foo.struct$MYpsoM99ZwFY087IpUOkIw1zjBA_sgFXVodmn1m-G88", ptr undef }, ptr %[[TMP3]], 1
// DARWIN-ARM64-NEXT:   ret %"{{.*}}/runtime/internal/runtime.eface" %[[TMP4]]
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.eface", align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.eface" %[[TMP4]], ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load { ptr, ptr }, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   ret { ptr, ptr } %[[TMP6]]
// CHECK-NEXT: }

func F() any {
	return struct{ v int }{1}
}

type Foo struct {
	pb *byte
	F  float32
}

func (v Foo) Pb() *byte {
	return v.pb
}

type Gamer interface {
	initGame()
	Load()
}

type Game struct {
}

func (g *Game) initGame() {
}

func (g *Game) Load() {
	println("load")
}

// CHECK-LABEL: define ptr @"{{.*}}/cl/_testdata/foo.(*Foo).Pb"(
// CHECK-SAME: ptr %[[TMP0:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = alloca %"{{.*}}/cl/_testdata/foo.Foo", align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = icmp eq ptr %[[TMP0]], null
// DARWIN-ARM64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicWrapNilPointer"(i1 %[[TMP2]], %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB6]], i64 43 }, %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB7]], i64 2 })
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = load %"{{.*}}/cl/_testdata/foo.Foo", ptr %[[TMP0]], align 8
// DARWIN-ARM64-NEXT:   store %"{{.*}}/cl/_testdata/foo.Foo" %[[TMP3]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = load [2 x i64], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = call ptr @"{{.*}}/cl/_testdata/foo.Foo.Pb"([2 x i64] %[[TMP4]])
// DARWIN-ARM64-NEXT:   ret ptr %[[TMP5]]
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/runtime/internal/runtime.String", align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = icmp eq ptr %[[TMP0]], null
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB6]], i64 43 }, ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = load ptr, ptr %[[TMP5]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load i64, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/runtime/internal/runtime.String" { ptr @[[GLOB7]], i64 2 }, ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP9:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP10:[0-9]+]] = load ptr, ptr %[[TMP9]], align 8
// LINUX-AMD64-NEXT:   %[[TMP11:[0-9]+]] = getelementptr inbounds { ptr, i64 }, ptr %[[TMP3]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP12:[0-9]+]] = load i64, ptr %[[TMP11]], align 8
// LINUX-AMD64-NEXT:   call void @"{{.*}}/runtime/internal/runtime.PanicWrapNilPointer"(i1 %[[TMP4]], ptr %[[TMP6]], i64 %[[TMP8]], ptr %[[TMP10]], i64 %[[TMP12]])
// LINUX-AMD64-NEXT:   %[[TMP13:[0-9]+]] = load %"{{.*}}/cl/_testdata/foo.Foo", ptr %[[TMP0]], align 8
// LINUX-AMD64-NEXT:   store %"{{.*}}/cl/_testdata/foo.Foo" %[[TMP13]], ptr %[[TMP1]], align 8
// LINUX-AMD64-NEXT:   %[[TMP14:[0-9]+]] = getelementptr inbounds { ptr, float }, ptr %[[TMP1]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP15:[0-9]+]] = load ptr, ptr %[[TMP14]], align 8
// LINUX-AMD64-NEXT:   %[[TMP16:[0-9]+]] = getelementptr inbounds { ptr, float }, ptr %[[TMP1]], i32 0, i32 1
// LINUX-AMD64-NEXT:   %[[TMP17:[0-9]+]] = load float, ptr %[[TMP16]], align 4
// LINUX-AMD64-NEXT:   %[[TMP18:[0-9]+]] = call ptr @"{{.*}}/cl/_testdata/foo.Foo.Pb"(ptr %[[TMP15]], float %[[TMP17]])
// LINUX-AMD64-NEXT:   ret ptr %[[TMP18]]
// CHECK-NEXT: }

// CHECK-LABEL: define ptr @"{{.*}}/cl/_testdata/foo.Foo.Pb"(
// DARWIN-ARM64-SAME: [2 x i64] %[[TMP0:[0-9]+]]){{.*}} {
// LINUX-AMD64-SAME: ptr %[[TMP0:[0-9]+]], float %[[TMP1:[0-9]+]]){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// DARWIN-ARM64-NEXT:   %[[TMP1:[0-9]+]] = alloca [2 x i64], align 8
// DARWIN-ARM64-NEXT:   store [2 x i64] %[[TMP0]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP2:[0-9]+]] = load %"{{.*}}/cl/_testdata/foo.Foo", ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP3:[0-9]+]] = alloca %"{{.*}}/cl/_testdata/foo.Foo", align 8
// DARWIN-ARM64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP3]], i8 0, i64 16, i1 false)
// DARWIN-ARM64-NEXT:   store %"{{.*}}/cl/_testdata/foo.Foo" %[[TMP2]], ptr %[[TMP1]], align 8
// DARWIN-ARM64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/foo.Foo", ptr %[[TMP1]], i32 0, i32 0
// DARWIN-ARM64-NEXT:   %[[TMP5:[0-9]+]] = load ptr, ptr %[[TMP4]], align 8
// DARWIN-ARM64-NEXT:   ret ptr %[[TMP5]]
// LINUX-AMD64-NEXT:   %[[TMP2:[0-9]+]] = alloca { ptr, float }, align 8
// LINUX-AMD64-NEXT:   %[[TMP3:[0-9]+]] = getelementptr inbounds { ptr, float }, ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   store ptr %[[TMP0]], ptr %[[TMP3]], align 8
// LINUX-AMD64-NEXT:   %[[TMP4:[0-9]+]] = getelementptr inbounds { ptr, float }, ptr %[[TMP2]], i32 0, i32 1
// LINUX-AMD64-NEXT:   store float %[[TMP1]], ptr %[[TMP4]], align 4
// LINUX-AMD64-NEXT:   %[[TMP5:[0-9]+]] = load %"{{.*}}/cl/_testdata/foo.Foo", ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP6:[0-9]+]] = alloca %"{{.*}}/cl/_testdata/foo.Foo", align 8
// LINUX-AMD64-NEXT:   call void @llvm.memset.p0.i64(ptr %[[TMP6]], i8 0, i64 16, i1 false)
// LINUX-AMD64-NEXT:   store %"{{.*}}/cl/_testdata/foo.Foo" %[[TMP5]], ptr %[[TMP2]], align 8
// LINUX-AMD64-NEXT:   %[[TMP7:[0-9]+]] = getelementptr inbounds %"{{.*}}/cl/_testdata/foo.Foo", ptr %[[TMP2]], i32 0, i32 0
// LINUX-AMD64-NEXT:   %[[TMP8:[0-9]+]] = load ptr, ptr %[[TMP7]], align 8
// LINUX-AMD64-NEXT:   ret ptr %[[TMP8]]
// CHECK-NEXT: }
