// LITTEST
// NOTE: Assertions have been autogenerated by chore/litgen UTC_ARGS: --function=(?:\Qmain.main\E) --check-globals=smart
package main

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/py"
	"github.com/goplus/lib/py/numpy"
)

// CHECK: {{^}}@[[GLOB0:[0-9]+]] = private unnamed_addr constant [8 x i8] c"a = %s\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB1:[0-9]+]] = private unnamed_addr constant [8 x i8] c"a = %s\0A\00", align 1{{$}}
// CHECK: {{^}}@[[GLOB2:[0-9]+]] = private unnamed_addr constant [10 x i8] c"a+b = %s\0A\00", align 1{{$}}

// Build each row from its own scalar objects, then insert those rows into the
// corresponding outer matrix. This prevents a flat sequence of SetItem calls
// from accidentally satisfying the test with crossed lists or indices.
// Each printed C string must derive from the corresponding matrix/result.
func main() {
	a := py.List(
		py.List(1.0, 2.0, 3.0),
		py.List(4.0, 5.0, 6.0),
		py.List(7.0, 8.0, 9.0),
	)
	b := py.List(
		py.List(9.0, 8.0, 7.0),
		py.List(6.0, 5.0, 4.0),
		py.List(3.0, 2.0, 1.0),
	)
	x := numpy.Add(a, b)
	c.Printf(c.Str("a = %s\n"), a.Str().CStr())
	c.Printf(c.Str("a = %s\n"), b.Str().CStr())
	c.Printf(c.Str("a+b = %s\n"), x.Str().CStr())
}

// CHECK-LABEL: define void @main.main(){{.*}} {
// CHECK-NEXT: _llgo_[[BB0:[0-9]+]]:
// CHECK-NEXT:   %[[TMP0:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP1:[0-9]+]] = call ptr @PyFloat_FromDouble(double 1.000000e+00)
// CHECK-NEXT:   %[[TMP2:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP0]], i64 0, ptr %[[TMP1]])
// CHECK-NEXT:   %[[TMP3:[0-9]+]] = call ptr @PyFloat_FromDouble(double 2.000000e+00)
// CHECK-NEXT:   %[[TMP4:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP0]], i64 1, ptr %[[TMP3]])
// CHECK-NEXT:   %[[TMP5:[0-9]+]] = call ptr @PyFloat_FromDouble(double 3.000000e+00)
// CHECK-NEXT:   %[[TMP6:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP0]], i64 2, ptr %[[TMP5]])
// CHECK-NEXT:   %[[TMP7:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP8:[0-9]+]] = call ptr @PyFloat_FromDouble(double 4.000000e+00)
// CHECK-NEXT:   %[[TMP9:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 0, ptr %[[TMP8]])
// CHECK-NEXT:   %[[TMP10:[0-9]+]] = call ptr @PyFloat_FromDouble(double 5.000000e+00)
// CHECK-NEXT:   %[[TMP11:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 1, ptr %[[TMP10]])
// CHECK-NEXT:   %[[TMP12:[0-9]+]] = call ptr @PyFloat_FromDouble(double 6.000000e+00)
// CHECK-NEXT:   %[[TMP13:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP7]], i64 2, ptr %[[TMP12]])
// CHECK-NEXT:   %[[TMP14:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP15:[0-9]+]] = call ptr @PyFloat_FromDouble(double 7.000000e+00)
// CHECK-NEXT:   %[[TMP16:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP14]], i64 0, ptr %[[TMP15]])
// CHECK-NEXT:   %[[TMP17:[0-9]+]] = call ptr @PyFloat_FromDouble(double 8.000000e+00)
// CHECK-NEXT:   %[[TMP18:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP14]], i64 1, ptr %[[TMP17]])
// CHECK-NEXT:   %[[TMP19:[0-9]+]] = call ptr @PyFloat_FromDouble(double 9.000000e+00)
// CHECK-NEXT:   %[[TMP20:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP14]], i64 2, ptr %[[TMP19]])
// CHECK-NEXT:   %[[TMP21:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP22:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP21]], i64 0, ptr %[[TMP0]])
// CHECK-NEXT:   %[[TMP23:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP21]], i64 1, ptr %[[TMP7]])
// CHECK-NEXT:   %[[TMP24:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP21]], i64 2, ptr %[[TMP14]])
// CHECK-NEXT:   %[[TMP25:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP26:[0-9]+]] = call ptr @PyFloat_FromDouble(double 9.000000e+00)
// CHECK-NEXT:   %[[TMP27:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP25]], i64 0, ptr %[[TMP26]])
// CHECK-NEXT:   %[[TMP28:[0-9]+]] = call ptr @PyFloat_FromDouble(double 8.000000e+00)
// CHECK-NEXT:   %[[TMP29:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP25]], i64 1, ptr %[[TMP28]])
// CHECK-NEXT:   %[[TMP30:[0-9]+]] = call ptr @PyFloat_FromDouble(double 7.000000e+00)
// CHECK-NEXT:   %[[TMP31:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP25]], i64 2, ptr %[[TMP30]])
// CHECK-NEXT:   %[[TMP32:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP33:[0-9]+]] = call ptr @PyFloat_FromDouble(double 6.000000e+00)
// CHECK-NEXT:   %[[TMP34:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP32]], i64 0, ptr %[[TMP33]])
// CHECK-NEXT:   %[[TMP35:[0-9]+]] = call ptr @PyFloat_FromDouble(double 5.000000e+00)
// CHECK-NEXT:   %[[TMP36:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP32]], i64 1, ptr %[[TMP35]])
// CHECK-NEXT:   %[[TMP37:[0-9]+]] = call ptr @PyFloat_FromDouble(double 4.000000e+00)
// CHECK-NEXT:   %[[TMP38:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP32]], i64 2, ptr %[[TMP37]])
// CHECK-NEXT:   %[[TMP39:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP40:[0-9]+]] = call ptr @PyFloat_FromDouble(double 3.000000e+00)
// CHECK-NEXT:   %[[TMP41:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP39]], i64 0, ptr %[[TMP40]])
// CHECK-NEXT:   %[[TMP42:[0-9]+]] = call ptr @PyFloat_FromDouble(double 2.000000e+00)
// CHECK-NEXT:   %[[TMP43:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP39]], i64 1, ptr %[[TMP42]])
// CHECK-NEXT:   %[[TMP44:[0-9]+]] = call ptr @PyFloat_FromDouble(double 1.000000e+00)
// CHECK-NEXT:   %[[TMP45:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP39]], i64 2, ptr %[[TMP44]])
// CHECK-NEXT:   %[[TMP46:[0-9]+]] = call ptr @PyList_New(i64 3)
// CHECK-NEXT:   %[[TMP47:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP46]], i64 0, ptr %[[TMP25]])
// CHECK-NEXT:   %[[TMP48:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP46]], i64 1, ptr %[[TMP32]])
// CHECK-NEXT:   %[[TMP49:[0-9]+]] = call i32 @PyList_SetItem(ptr %[[TMP46]], i64 2, ptr %[[TMP39]])
// CHECK-NEXT:   %[[TMP50:[0-9]+]] = load ptr, ptr @__llgo_py.numpy.add, align 8
// CHECK-NEXT:   %[[TMP51:[0-9]+]] = call ptr (ptr, ...) @PyObject_CallFunctionObjArgs(ptr %[[TMP50]], ptr %[[TMP21]], ptr %[[TMP46]], ptr null)
// CHECK-NEXT:   %[[TMP52:[0-9]+]] = call ptr @PyObject_Str(ptr %[[TMP21]])
// CHECK-NEXT:   %[[TMP53:[0-9]+]] = call ptr @PyUnicode_AsUTF8(ptr %[[TMP52]])
// CHECK-NEXT:   %[[TMP54:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB0]], ptr %[[TMP53]])
// CHECK-NEXT:   %[[TMP55:[0-9]+]] = call ptr @PyObject_Str(ptr %[[TMP46]])
// CHECK-NEXT:   %[[TMP56:[0-9]+]] = call ptr @PyUnicode_AsUTF8(ptr %[[TMP55]])
// CHECK-NEXT:   %[[TMP57:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB1]], ptr %[[TMP56]])
// CHECK-NEXT:   %[[TMP58:[0-9]+]] = call ptr @PyObject_Str(ptr %[[TMP51]])
// CHECK-NEXT:   %[[TMP59:[0-9]+]] = call ptr @PyUnicode_AsUTF8(ptr %[[TMP58]])
// CHECK-NEXT:   %[[TMP60:[0-9]+]] = call i32 (ptr, ...) @printf(ptr @[[GLOB2]], ptr %[[TMP59]])
// CHECK-NEXT:   ret void
// CHECK-NEXT: }
